'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { CheckCircle2, Loader2, RefreshCw, WalletCards } from 'lucide-react'
import { tokenAtual } from '@/lib/auth'

type Conta={id:string;nf_id:string|null;fornecedor_nome:string|null;documento:string|null;parcela:string;descricao:string|null;data_emissao:string|null;vencimento:string|null;valor:number;status:string;data_pagamento:string|null;valor_pago:number|null;forma_pagamento:string|null}
const moeda=(v:number|null|undefined)=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const data=(v:string|null)=>v?new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR'):'Sem vencimento'
export default function ContasPagarPage(){
 const[contas,setContas]=useState<Conta[]>([]);const[loading,setLoading]=useState(true);const[erro,setErro]=useState('');const[acao,setAcao]=useState('')
 async function carregar(){setLoading(true);setErro('');try{const t=await tokenAtual();if(!t)throw new Error('Sessão expirada.');const r=await fetch('/api/financeiro/contas-pagar?limit=1000',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');setContas(j.contas||[])}catch(e){setErro(e instanceof Error?e.message:'Erro ao carregar.')}finally{setLoading(false)}}
 useEffect(()=>{carregar()},[])
 async function mudar(id:string,tipo:'pagar'|'reabrir'|'cancelar'){setAcao(id+tipo);try{const t=await tokenAtual();const r=await fetch('/api/financeiro/contas-pagar',{method:'PATCH',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({id,acao:tipo})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');await carregar()}catch(e){setErro(e instanceof Error?e.message:'Erro ao atualizar.')}finally{setAcao('')}}
 const hoje=new Date().toISOString().slice(0,10);const resumo=useMemo(()=>({aberto:contas.filter(c=>c.status==='aberto'||c.status==='pendente_vencimento').reduce((s,c)=>s+Number(c.valor),0),vencido:contas.filter(c=>c.status==='aberto'&&c.vencimento&&c.vencimento<hoje).reduce((s,c)=>s+Number(c.valor),0),pago:contas.filter(c=>c.status==='pago').reduce((s,c)=>s+Number(c.valor_pago??c.valor),0)}),[contas,hoje])
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-7xl space-y-5">
 <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">Financeiro</p><h1 className="mt-1 text-2xl font-bold">Contas a Pagar</h1><p className="mt-1 text-sm text-slate-600">Parcelas geradas pelas notas de compra e lançamentos financeiros.</p></div><div className="flex gap-2"><Link href="/compras" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Compras</Link><button onClick={carregar} className="rounded-xl border bg-white p-2.5"><RefreshCw size={18}/></button></div></header>
 {erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{erro}</div>}
 <section className="grid gap-3 sm:grid-cols-3"><Card t="Em aberto" v={moeda(resumo.aberto)}/><Card t="Vencido" v={moeda(resumo.vencido)}/><Card t="Pago" v={moeda(resumo.pago)}/></section>
 <section className="rounded-2xl border bg-white p-5">{loading?<div className="py-12 text-center"><Loader2 className="mx-auto animate-spin"/></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-2">Fornecedor</th><th className="p-2">Documento</th><th className="p-2">Parcela</th><th className="p-2">Vencimento</th><th className="p-2 text-right">Valor</th><th className="p-2">Status</th><th className="p-2 text-right">Ações</th></tr></thead><tbody>{contas.map(c=>{const vencida=c.status==='aberto'&&!!c.vencimento&&c.vencimento<hoje;return <tr key={c.id} className="border-b last:border-0"><td className="p-2 font-medium">{c.fornecedor_nome||'—'}</td><td className="p-2">{c.documento||c.descricao||'—'}</td><td className="p-2">{c.parcela}</td><td className={`p-2 ${vencida?'font-semibold text-red-600':''}`}>{data(c.vencimento)}</td><td className="p-2 text-right font-semibold">{moeda(c.valor)}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs ${c.status==='pago'?'bg-emerald-100 text-emerald-700':c.status==='cancelado'?'bg-slate-100 text-slate-500':vencida?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{c.status.replace('_',' ')}</span></td><td className="p-2 text-right">{c.status==='pago'?<button disabled={!!acao} onClick={()=>mudar(c.id,'reabrir')} className="rounded-lg border px-2 py-1 text-xs">Reabrir</button>:c.status!=='cancelado'?<div className="flex justify-end gap-1"><button disabled={!!acao} onClick={()=>mudar(c.id,'pagar')} className="rounded-lg bg-emerald-600 px-2 py-1 text-xs font-semibold text-white"><CheckCircle2 size={13} className="mr-1 inline"/>Pagar</button><button disabled={!!acao} onClick={()=>mudar(c.id,'cancelar')} className="rounded-lg border px-2 py-1 text-xs">Cancelar</button></div>:null}</td></tr>})}</tbody></table>{!contas.length&&<div className="py-10 text-center text-slate-500"><WalletCards className="mx-auto mb-2"/>Nenhuma conta a pagar registrada.</div>}</div>}</section>
 </div></main>
}
function Card({t,v}:{t:string;v:string}){return <div className="rounded-2xl border bg-white p-5"><div className="text-sm text-slate-500">{t}</div><div className="mt-1 text-2xl font-bold">{v}</div></div>}
