'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Boxes, Building2, Loader2, MapPin, RefreshCw, Search, Warehouse } from 'lucide-react'
import { tokenAtual } from '@/lib/auth'

type Unidade={id:string;codigo:string;nome:string;tipo:string;cidade:string|null}
type Saldo={id:string;produto_id:string;unidade:string|null;quantidade:number;quantidade_reservada:number;quantidade_disponivel:number;custo_medio:number|null;valor_estoque:number;updated_at:string;produto?:{id:string;codigo:string|null;nome:string;categoria:string}|null;local?:{id:string;codigo:string;nome:string;tipo:string;unidade?:Unidade|null}|null;endereco?:{id:string;codigo:string;zona:string|null;corredor:string|null;estante:string|null;prateleira:string|null;caixa:string|null;descricao:string|null}|null}
type Movimento={id:string;produto_id:string;tipo:string;quantidade:number;unidade:string|null;custo_unitario:number|null;valor_total:number|null;origem_tipo:string;criado_por_nome:string|null;created_at:string}
const moeda=(v:number|null|undefined)=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const numero=(v:number|null|undefined)=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:3})
function enderecoTexto(e:Saldo['endereco']){if(!e)return 'Sem endereço definido';const p=[e.zona&&`Zona ${e.zona}`,e.corredor&&`Corredor ${e.corredor}`,e.estante&&`Estante ${e.estante}`,e.prateleira&&`Prateleira ${e.prateleira}`,e.caixa&&`Caixa ${e.caixa}`].filter(Boolean);return p.length?p.join(' • '):e.codigo}

export default function EstoquePage(){
 const[saldos,setSaldos]=useState<Saldo[]>([]);const[movs,setMovs]=useState<Movimento[]>([]);const[unidades,setUnidades]=useState<Unidade[]>([]);const[busca,setBusca]=useState('');const[filtroUnidade,setFiltroUnidade]=useState('');const[loading,setLoading]=useState(true);const[erro,setErro]=useState('')
 async function carregar(){setLoading(true);setErro('');try{const t=await tokenAtual();if(!t)throw new Error('Sessão expirada.');const r=await fetch('/api/estoque?limit=1000',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');setSaldos(j.saldos||[]);setMovs(j.movimentos||[]);setUnidades(j.unidades||[])}catch(e){setErro(e instanceof Error?e.message:'Erro ao carregar estoque.')}finally{setLoading(false)}}
 useEffect(()=>{carregar()},[])
 const filtrados=useMemo(()=>{const q=busca.trim().toUpperCase();return saldos.filter(s=>{if(filtroUnidade&&s.local?.unidade?.id!==filtroUnidade)return false;if(!q)return true;return [s.produto?.codigo,s.produto?.nome,s.local?.nome,s.local?.unidade?.nome,s.endereco?.codigo,s.endereco?.corredor,s.endereco?.prateleira,s.endereco?.caixa].some(v=>String(v||'').toUpperCase().includes(q))})},[saldos,busca,filtroUnidade])
 const total=useMemo(()=>saldos.reduce((s,x)=>s+Number(x.valor_estoque||0),0),[saldos]);const reservado=useMemo(()=>saldos.reduce((s,x)=>s+Number(x.quantidade_reservada||0),0),[saldos])
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-7xl space-y-5">
  <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">Operações • Estoque</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Estoque da Rede</h1><p className="mt-1 text-sm text-slate-600">Um único cadastro de produtos, com saldo físico separado por unidade, local e endereço.</p></div><div className="flex flex-wrap gap-2"><Link href="/estoque/estrutura" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Estrutura do estoque</Link><Link href="/estoque/enderecar" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Endereçar produtos</Link><Link href="/estoque/transferencias" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Transferências</Link><Link href="/compras" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Compras</Link><button onClick={carregar} className="rounded-xl border bg-white p-2.5"><RefreshCw size={18}/></button></div></header>
  {erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{erro}</div>}
  <section className="grid gap-3 sm:grid-cols-4"><Card icon={<Boxes/>} t="Saldos por local" v={saldos.length}/><Card icon={<Building2/>} t="Unidades ativas" v={unidades.length}/><Card icon={<Warehouse/>} t="Valor em estoque" v={moeda(total)}/><Card icon={<MapPin/>} t="Qtd. reservada" v={numero(reservado)}/></section>
  <section className="rounded-2xl border bg-white p-5"><div className="mb-4 grid gap-3 md:grid-cols-[1fr_260px]"><div className="flex items-center gap-2 rounded-xl border px-3 py-2"><Search size={17} className="text-slate-400"/><input value={busca} onChange={e=>setBusca(e.target.value)} className="w-full outline-none" placeholder="Buscar código, produto, loja, corredor, prateleira ou caixa..."/></div><select value={filtroUnidade} onChange={e=>setFiltroUnidade(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="">Todas as unidades</option>{unidades.map(u=><option key={u.id} value={u.id}>{u.nome}</option>)}</select></div>
  {loading?<div className="py-12 text-center"><Loader2 className="mx-auto animate-spin"/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-2">Código</th><th className="p-2">Produto</th><th className="p-2">Unidade / Loja</th><th className="p-2">Local</th><th className="p-2">Endereço</th><th className="p-2 text-right">Físico</th><th className="p-2 text-right">Reservado</th><th className="p-2 text-right">Disponível</th><th className="p-2 text-right">Custo médio</th></tr></thead><tbody>{filtrados.map(s=><tr key={s.id} className="border-b last:border-0"><td className="p-2 font-mono">{s.produto?.codigo||'—'}</td><td className="p-2 font-medium">{s.produto?.nome||'Produto'}</td><td className="p-2"><div className="font-medium">{s.local?.unidade?.nome||'—'}</div><div className="text-xs text-slate-400">{s.local?.unidade?.cidade||''}</div></td><td className="p-2">{s.local?.nome||'—'}</td><td className="p-2"><div>{enderecoTexto(s.endereco)}</div>{s.endereco?.codigo&&<div className="text-xs font-mono text-slate-400">{s.endereco.codigo}</div>}</td><td className="p-2 text-right">{numero(s.quantidade)} {s.unidade||''}</td><td className="p-2 text-right text-amber-700">{numero(s.quantidade_reservada)}</td><td className="p-2 text-right font-bold text-emerald-700">{numero(s.quantidade_disponivel)}</td><td className="p-2 text-right">{moeda(s.custo_medio)}</td></tr>)}</tbody></table>{!filtrados.length&&<div className="py-10 text-center text-slate-500"><Boxes className="mx-auto mb-2"/>Nenhum saldo encontrado.</div>}</div>}</section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Regra da rede</h2><p className="mt-1 text-sm text-slate-600">A busca mostra o estoque de todas as unidades. O saldo disponível é o físico menos o que já foi reservado para vendas ou transferências, evitando prometer a mesma peça para dois clientes.</p><p className="mt-2 text-xs text-slate-400">Movimentos recentes registrados: {movs.length}</p></section>
 </div></main>
}
function Card({icon,t,v}:{icon:React.ReactNode;t:string;v:string|number}){return <div className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2 text-slate-500">{icon}<span className="text-sm">{t}</span></div><div className="mt-2 text-2xl font-bold">{v}</div></div>}
