'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { tokenAtual } from '@/lib/auth'

type Conta={id:string;documento?:string|null;cliente_nome?:string|null;parcela:number;total_parcelas:number;vencimento?:string|null;valor:number;status:string;forma?:string|null;valor_pago?:number|null;data_pagamento?:string|null}
function moeda(n:number){return Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
const formas=[['pix','PIX'],['dinheiro','Dinheiro'],['cartao_debito','Cartão débito'],['cartao_credito','Cartão crédito'],['outros','Outros']]
export default function ContasReceberBalcao(){const [status,setStatus]=useState('aberto'),[lista,setLista]=useState<Conta[]>([]),[erro,setErro]=useState(''),[msg,setMsg]=useState('')
 async function api(url:string,init?:RequestInit){const t=await tokenAtual();if(!t)throw new Error('Sessão expirada.');return fetch(url,{...init,headers:{...(init?.headers||{}),Authorization:`Bearer ${t}`}})}
 async function carregar(){setErro('');try{const r=await api(`/api/balcao/contas-receber?status=${status}`);const j=await r.json();if(!r.ok)throw new Error(j.error);setLista(j.contas||[])}catch(e){setErro(e instanceof Error?e.message:'Erro ao carregar contas.')}}useEffect(()=>{carregar()},[status])
 async function baixar(c:Conta){const forma=window.prompt('Forma de pagamento: pix, dinheiro, cartao_debito, cartao_credito ou outros','pix')||'pix';const valor=window.prompt('Valor recebido',String(c.valor))||'';if(!valor)return;try{const r=await api('/api/balcao/contas-receber',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:c.id,forma,valorPago:Number(valor.replace(',','.'))})});const j=await r.json();if(!r.ok)throw new Error(j.error);setMsg('Recebimento baixado com sucesso.');await carregar()}catch(e){setErro(e instanceof Error?e.message:'Erro ao baixar recebimento.')}}
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-4"><header className="flex items-center gap-3"><Link href="/balcao" className="rounded-lg border bg-white p-2"><ArrowLeft size={18}/></Link><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-slate-400">Venda Balcão • Financeiro</p><h1 className="text-2xl font-bold">Contas a Receber</h1><p className="text-sm text-slate-500">Parcelas geradas por boleto e venda a prazo.</p></div></header>{erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{msg&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</div>}<section className="rounded-2xl border bg-white p-4"><div className="mb-4 flex gap-2"><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="aberto">Abertas</option><option value="pago">Pagas</option><option value="todos">Todas</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Documento</th><th>Cliente</th><th>Parcela</th><th>Vencimento</th><th>Forma</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>{lista.map(c=><tr key={c.id} className="border-t"><td className="p-3 font-semibold">{c.documento||'—'}</td><td>{c.cliente_nome||'Cliente balcão'}</td><td>{c.parcela}/{c.total_parcelas}</td><td>{c.vencimento?new Date(`${c.vencimento}T12:00:00`).toLocaleDateString('pt-BR'):'Pendente'}</td><td className="capitalize">{(c.forma||'—').replaceAll('_',' ')}</td><td className="font-bold">{moeda(c.valor)}</td><td><span className={`rounded-full px-2 py-1 text-xs ${c.status==='pago'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{c.status}</span></td><td>{c.status!=='pago'&&<button onClick={()=>baixar(c)} className="rounded-lg bg-emerald-700 px-3 py-1.5 text-xs font-semibold text-white">Receber</button>}</td></tr>)}</tbody></table></div></section></div></main>}
