'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Search } from 'lucide-react'
import { tokenAtual } from '@/lib/auth'

type Produto={id:string;codigo:string;nome:string;descricao?:string|null;unidade:string;estoque:number;unidadeEstoque:string;preco:number;precoPromocional?:number|null;precoEfetivo:number;custo?:number|null;margem?:number|null;precoMinimo?:number|null}
function moeda(n:number){return Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
export default function ConsultaPreco(){const [q,setQ]=useState(''),[lista,setLista]=useState<Produto[]>([]),[gestao,setGestao]=useState(false),[erro,setErro]=useState('')
 async function carregar(v=''){try{const t=await tokenAtual();if(!t)throw new Error('Sessão expirada.');const r=await fetch(`/api/balcao/catalogo?tipo=produtos&q=${encodeURIComponent(v)}`,{headers:{Authorization:`Bearer ${t}`}});const j=await r.json();if(!r.ok)throw new Error(j.error);setLista(j.produtos||[]);setGestao(!!j.podeVerGestao)}catch(e){setErro(e instanceof Error?e.message:'Erro ao consultar produtos.')}}useEffect(()=>{carregar()},[]);useEffect(()=>{const h=setTimeout(()=>carregar(q),250);return()=>clearTimeout(h)},[q])
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-4"><header className="flex items-center gap-3"><Link href="/balcao" className="rounded-lg border bg-white p-2"><ArrowLeft size={18}/></Link><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-slate-400">Venda Balcão</p><h1 className="text-2xl font-bold">Consulta de preço</h1><p className="text-sm text-slate-500">Consulta sem gerar orçamento, venda ou movimento de estoque.</p></div></header>{erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}<section className="rounded-2xl border bg-white p-4"><div className="relative"><Search size={18} className="absolute left-3 top-3 text-slate-400"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Digite código, nome ou descrição..." className="w-full rounded-xl border py-2.5 pl-10 pr-3 text-sm"/></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Produto</th><th>Estoque</th><th>Preço normal</th><th>Preço atual</th>{gestao&&<><th>Custo</th><th>Margem</th><th>Mínimo</th></>}</tr></thead><tbody>{lista.map(p=><tr key={p.id} className="border-t"><td className="p-3"><strong>{p.codigo||'—'}</strong><div>{p.nome}</div><div className="max-w-xl truncate text-xs text-slate-400">{p.descricao}</div></td><td><span className={p.estoque>0?'text-emerald-700':'text-red-600'}>{p.estoque} {p.unidadeEstoque}</span></td><td>{moeda(p.preco)}</td><td><strong className="text-emerald-700">{moeda(p.precoEfetivo)}</strong>{p.precoPromocional!=null&&<div className="text-[10px] text-amber-600">promocional</div>}</td>{gestao&&<><td>{p.custo==null?'—':moeda(p.custo)}</td><td>{p.margem==null?'—':`${p.margem.toFixed(1)}%`}</td><td>{p.precoMinimo==null?'—':moeda(p.precoMinimo)}</td></>}</tr>)}</tbody></table></div></section></div></main>}
