'use client'
import { useEffect, useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { MessageCircle, Plus, Search, Send, Users, ArrowLeft, ClipboardList } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { usuarioAtual } from '@/lib/auth'
import { ChatConversa, ChatMensagem, criarConversa, enviarMensagem, listarConversas, listarMensagens } from '@/lib/chatInterno'

type UsuarioLista={id:string;nome:string}
export default function ChatInternoPage(){
 const [eu,setEu]=useState<UsuarioLista|null>(null),[conversas,setConversas]=useState<ChatConversa[]>([]),[ativa,setAtiva]=useState<ChatConversa|null>(null)
 const [mensagens,setMensagens]=useState<ChatMensagem[]>([]),[texto,setTexto]=useState(''),[busca,setBusca]=useState(''),[erro,setErro]=useState('')
 const [usuarios,setUsuarios]=useState<UsuarioLista[]>([]),[buscaUsuario,setBuscaUsuario]=useState(''),[novo,setNovo]=useState(false),[nomeGrupo,setNomeGrupo]=useState(''),[selecionados,setSelecionados]=useState<string[]>([])
 const fimMensagens=useRef<HTMLDivElement|null>(null)
 async function carregar(){const u=await usuarioAtual();if(!u)return;setEu(u);const [cs,us]=await Promise.all([listarConversas(u.id),supabase.from('usuarios').select('id,nome').order('nome')]);setConversas(cs);setUsuarios((us.data||[]) as UsuarioLista[]);if(!ativa&&cs[0])setAtiva(cs[0])}
 useEffect(()=>{void carregar()},[])
 useEffect(()=>{if(!ativa)return;listarMensagens(ativa.id).then(setMensagens);const canal=supabase.channel('chat-'+ativa.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_mensagens',filter:`conversa_id=eq.${ativa.id}`},p=>setMensagens(m=>m.some(x=>x.id===(p.new as any).id)?m:[...m,p.new as ChatMensagem])).subscribe();return()=>{void supabase.removeChannel(canal)}},[ativa?.id])
 useEffect(()=>{fimMensagens.current?.scrollIntoView({behavior:'smooth',block:'end'})},[mensagens.length,ativa?.id])
 const filtradas=useMemo(()=>conversas.filter(c=>(c.nome||'Conversa').toLowerCase().includes(busca.toLowerCase())),[conversas,busca])
 async function mandar(){if(!ativa||!texto.trim())return;const t=texto;setTexto('');setErro('');if(!await enviarMensagem(ativa.id,t)){setTexto(t);setErro('Não foi possível enviar a mensagem. Tente novamente.')}}
 const usuariosFiltrados=useMemo(()=>{const q=buscaUsuario.toLocaleLowerCase('pt-BR').trim();return usuarios.filter(u=>u.id!==eu?.id&&(!q||u.nome.toLocaleLowerCase('pt-BR').includes(q)))},[usuarios,buscaUsuario,eu?.id])
 async function criar(){const ps=usuarios.filter(u=>selecionados.includes(u.id));const c=await criarConversa(nomeGrupo||ps.map(p=>p.nome).join(', '),ps.length>1?'grupo':'direta',ps);if(c){setNovo(false);setNomeGrupo('');setBuscaUsuario('');setSelecionados([]);await carregar();setAtiva(c)}}
 return <main className="min-h-screen bg-slate-100 p-3 md:p-6"><div className="mx-auto max-w-7xl overflow-hidden rounded-2xl border bg-white shadow-sm">
  <header className="flex items-center justify-between border-b px-4 py-3"><div className="flex items-center gap-3"><Link href="/" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft size={19}/></Link><div><h1 className="font-bold text-slate-900">Chat interno</h1><p className="text-xs text-slate-500">Equipe Atlas One</p></div></div><div className="flex gap-2"><Link href="/compartilhar" className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold"><ClipboardList size={16}/>Enviar pedido</Link><button onClick={()=>setNovo(true)} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-sm font-bold text-white"><Plus size={16}/>Nova conversa</button></div></header>
  <div className="grid h-[calc(100dvh-120px)] min-h-[520px] md:grid-cols-[320px_1fr]">
   <aside className={(ativa?'hidden md:block ':'')+"border-r"}><div className="p-3"><div className="flex items-center gap-2 rounded-xl border px-3"><Search size={16} className="text-slate-400"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar conversa" className="w-full py-2.5 text-sm outline-none"/></div></div><div className="overflow-y-auto">{filtradas.map(c=><button key={c.id} onClick={()=>setAtiva(c)} className={"flex w-full items-center gap-3 border-t px-4 py-4 text-left hover:bg-slate-50 "+(ativa?.id===c.id?'bg-blue-50':'')}><span className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><MessageCircle size={18}/></span><div className="min-w-0"><p className="truncate text-sm font-bold">{c.nome||'Conversa'}</p><p className="text-xs text-slate-400">{c.tipo==='grupo'?'Grupo':'Conversa direta'}</p></div></button>)}</div></aside>
   <section className={(!ativa?'hidden md:flex ':'flex ')+"min-w-0 flex-col"}>{ativa?<><div className="flex items-center gap-3 border-b px-4 py-3"><button className="md:hidden" onClick={()=>setAtiva(null)}><ArrowLeft size={19}/></button><Users size={19}/><div><b>{ativa.nome||'Conversa'}</b><p className="text-xs text-slate-400">{ativa.tipo==='grupo'?'Grupo interno':'Conversa interna'}</p></div></div><div className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-4">{mensagens.map(m=>{const minha=m.usuario_id===eu?.id;return <div key={m.id} className={"flex "+(minha?'justify-end':'justify-start')}><div className={"max-w-[82%] rounded-2xl px-3 py-2 shadow-sm "+(minha?'bg-emerald-100':'bg-white')}><p className="mb-1 text-[10px] font-bold text-slate-500">{m.usuario_nome}</p><p className="whitespace-pre-wrap text-sm">{m.texto}</p>{m.cliente_id&&<Link href={`/clientes/${m.cliente_id}`} className="mt-2 block text-xs font-bold text-blue-600">Abrir Cliente 360</Link>}<p className="mt-1 text-right text-[10px] text-slate-400">{new Date(m.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</p></div></div>})}</div>{erro&&<div className="border-t bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">{erro}</div>}<div className="flex gap-2 border-t p-3"><textarea rows={1} value={texto} onChange={e=>setTexto(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void mandar()}}} placeholder="Mensagem" className="min-h-11 flex-1 resize-none rounded-xl border px-3 py-2.5 text-sm outline-none"/><button onClick={()=>void mandar()} className="grid h-11 w-11 place-items-center rounded-xl bg-blue-600 text-white"><Send size={18}/></button></div></>:<div className="m-auto text-center text-slate-400"><MessageCircle className="mx-auto mb-3" size={36}/><p>Escolha uma conversa</p></div>}</section>
  </div></div>
  {novo&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl"><div className="flex justify-between"><div><h2 className="font-bold">Nova conversa</h2><p className="text-xs text-slate-500">Individual ou grupo</p></div><button onClick={()=>setNovo(false)}>✕</button></div><input value={nomeGrupo} onChange={e=>setNomeGrupo(e.target.value)} placeholder="Nome do grupo (opcional)" className="mt-4 w-full rounded-xl border px-3 py-2.5 text-sm"/><div className="mt-3 flex items-center gap-2 rounded-xl border px-3"><Search size={15} className="text-slate-400"/><input value={buscaUsuario} onChange={e=>setBuscaUsuario(e.target.value)} placeholder="Buscar pessoa" className="w-full py-2.5 text-sm outline-none"/></div><div className="mt-3 max-h-64 overflow-y-auto rounded-xl border">{usuariosFiltrados.map(u=><label key={u.id} className="flex items-center gap-3 border-b px-3 py-3 text-sm"><input type="checkbox" checked={selecionados.includes(u.id)} onChange={()=>setSelecionados(s=>s.includes(u.id)?s.filter(x=>x!==u.id):[...s,u.id])}/>{u.nome}</label>)}</div><button disabled={!selecionados.length} onClick={()=>void criar()} className="mt-4 w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white disabled:opacity-40">Criar conversa</button></div></div>}
 </main>
}
