'use client'

import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, AlertTriangle, FileDown, Loader2, Plus, Printer, Search, ShoppingCart, Trash2, UserPlus, WalletCards } from 'lucide-react'
import { tokenAtual, usuarioAtual } from '@/lib/auth'
import CatalogoFiltros from '@/components/balcao/CatalogoFiltros'
import { abrirPdfParaImpressao, gerarPdfOrcamentoBalcao, type ItemPdfBalcao } from '@/lib/pdfOrcamentoBalcao'
import { lerConfiguracaoOrcamento, lerDadosEmpresa, type ConfiguracaoOrcamento, type DadosEmpresaCompleta } from '@/lib/configGeral'

type EstoqueRede={localId:string;unidadeId:string;unidadeCodigo:string;unidadeNome:string;localCodigo:string;localNome:string;fisico:number;reservado:number;disponivel:number;unidade:string}
type Produto={id:string;codigo:string;nome:string;descricao?:string|null;categoria?:string|null;grupo?:string|null;grupos?:string[];unidade:string;estoque:number;estoqueLocal:number;estoqueRede:number;estoquesRede:EstoqueRede[];unidadeEstoque:string;preco:number;precoPromocional?:number|null;precoEfetivo:number;fotoUrl?:string|null;custo?:number|null;margem?:number|null;precoMinimo?:number|null;permiteVendaSemEstoque:boolean;pesoKgM?:number|null;tamanhoBarraMm?:number|null}
type Cliente={id:string;nome:string;apelido?:string|null;cpf_cnpj?:string|null;telefone?:string|null;whatsapp?:string|null;email?:string|null;cidade?:string|null;bairro?:string|null;endereco?:string|null;cep?:string|null}
type ItemCarrinho=Produto&{chave:string;quantidade:number;precoUnitario:number;localOrigemId:string;origemLabel:string;atendimento:'imediato'|'posterior'|'sem_estoque';disponivelOrigem:number}
type Pagamento={forma:string;valor:string;parcelas:number;primeiroVencimento:string;intervaloDias:number}
type LocalAtual={id:string;nome:string;codigo:string;unidadeId:string;unidadeNome:string;unidadeCodigo:string}
type Caixa={id:string;status:string;aberto_em:string;saldo_inicial:number;operador_nome:string;ponto?:{codigo:string;nome:string;unidadeNome:string;localNome:string}|null}
type Categoria={valor:string;label:string}
type Sucesso={vendaId?:string;numero:number;total:number;atendimentoStatus?:string;reservasPendentes?:number;itensAguardandoEstoque?:number}

const FORMAS=[['pix','PIX'],['dinheiro','Dinheiro'],['cartao_debito','Cartão débito'],['cartao_credito','Cartão crédito'],['boleto','Boleto'],['a_prazo','A prazo'],['outros','Outros']]
const novoPagamento=():Pagamento=>({forma:'pix',valor:'',parcelas:1,primeiroVencimento:'',intervaloDias:30})
function moeda(n:number){return Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function num(v:string|number){const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:0}
function labelForma(chave:string){return FORMAS.find(f=>f[0]===chave)?.[1]||chave}
function pesoTexto(p:Produto){if(p.categoria!=='perfil'||p.pesoKgM==null)return null;const peso=Number(p.pesoKgM);if(!Number.isFinite(peso))return null;return `Peso: ${peso.toLocaleString('pt-BR',{maximumFractionDigits:4})} kg/m${peso>50?' • REVISAR CADASTRO':''}`}

export default function NovaVendaBalcao(){
 const [produtos,setProdutos]=useState<Produto[]>([]),[categorias,setCategorias]=useState<Categoria[]>([]),[grupos,setGrupos]=useState<string[]>([]),[categoria,setCategoria]=useState(''),[grupo,setGrupo]=useState(''),[busca,setBusca]=useState(''),[carregando,setCarregando]=useState(false),[localAtual,setLocalAtual]=useState<LocalAtual|null>(null),[vendaSemEstoqueGlobal,setVendaSemEstoqueGlobal]=useState(true)
 const [origemPorProduto,setOrigemPorProduto]=useState<Record<string,string>>({}),[carrinho,setCarrinho]=useState<Record<string,ItemCarrinho>>({})
 const [clienteBusca,setClienteBusca]=useState(''),[clientes,setClientes]=useState<Cliente[]>([]),[cliente,setCliente]=useState<Cliente|null>(null),[carregandoClientes,setCarregandoClientes]=useState(false)
 const [desconto,setDesconto]=useState('0'),[pagamentos,setPagamentos]=useState<Pagamento[]>([novoPagamento()]),[caixa,setCaixa]=useState<Caixa|null>(null)
 const [salvando,setSalvando]=useState(false),[erro,setErro]=useState(''),[sucesso,setSucesso]=useState<Sucesso|null>(null)
 const [empresa,setEmpresa]=useState<DadosEmpresaCompleta|null>(null),[config,setConfig]=useState<ConfiguracaoOrcamento|null>(null)
 const documentoRef=useRef<Awaited<ReturnType<typeof gerarPdfOrcamentoBalcao>>|null>(null),arquivoRef=useRef('venda-balcao.pdf')
 const buscaAbort=useRef<AbortController|null>(null),buscaSeq=useRef(0),clienteAbort=useRef<AbortController|null>(null),clienteSeq=useRef(0)

 async function api(url:string,init?:RequestInit){const token=await tokenAtual();if(!token)throw new Error('Sessão expirada.');return fetch(url,{...init,headers:{...(init?.headers||{}),Authorization:`Bearer ${token}`},cache:'no-store'})}
 async function carregarCatalogo(){
  const seq=++buscaSeq.current;buscaAbort.current?.abort();const controller=new AbortController();buscaAbort.current=controller;setCarregando(true)
  try{const params=new URLSearchParams();if(busca.trim().length>=2)params.set('q',busca.trim());if(categoria)params.set('categoria',categoria);if(grupo)params.set('grupo',grupo);const resp=await api(`/api/balcao/catalogo-v2?${params.toString()}`,{signal:controller.signal});const json=await resp.json();if(!resp.ok)throw new Error(json.error);if(seq!==buscaSeq.current)return;setProdutos(json.produtos||[]);setCategorias(json.categorias||[]);setGrupos(json.grupos||[]);setLocalAtual(json.localAtual||null);setVendaSemEstoqueGlobal(Boolean(json.vendaSemEstoqueGlobal))}catch(e){if((e as {name?:string})?.name!=='AbortError'&&seq===buscaSeq.current)setErro(e instanceof Error?e.message:'Erro ao carregar produtos.')}finally{if(seq===buscaSeq.current)setCarregando(false)}
 }
 async function carregarClientes(q:string){const seq=++clienteSeq.current;clienteAbort.current?.abort();const c=new AbortController();clienteAbort.current=c;setCarregandoClientes(true);try{const r=await api(`/api/balcao/catalogo?tipo=clientes&q=${encodeURIComponent(q)}`,{signal:c.signal});const j=await r.json();if(r.ok&&seq===clienteSeq.current)setClientes(j.clientes||[])}catch(e){if((e as {name?:string})?.name!=='AbortError')setErro('Erro ao pesquisar cliente.')}finally{if(seq===clienteSeq.current)setCarregandoClientes(false)}}
 async function carregarCaixa(){try{const r=await api('/api/balcao/caixa');const j=await r.json();if(r.ok)setCaixa(j.caixa||null)}catch{}}
 useEffect(()=>{carregarCatalogo();carregarCaixa();Promise.all([lerDadosEmpresa(),lerConfiguracaoOrcamento()]).then(([e,c])=>{setEmpresa(e);setConfig(c)})},[])
 useEffect(()=>{buscaAbort.current?.abort();buscaSeq.current++;const h=setTimeout(()=>carregarCatalogo(),80);return()=>clearTimeout(h)},[busca,categoria,grupo])
 useEffect(()=>{const termo=clienteBusca.trim();clienteAbort.current?.abort();clienteSeq.current++;if(termo.length<2||cliente){setClientes([]);setCarregandoClientes(false);return}const h=setTimeout(()=>carregarClientes(termo),80);return()=>clearTimeout(h)},[clienteBusca,cliente])

 const itens=Object.values(carrinho),subtotal=itens.reduce((s,i)=>s+i.quantidade*i.precoUnitario,0),descontoN=Math.min(subtotal,Math.max(0,num(desconto))),total=Math.max(0,subtotal-descontoN),pagos=pagamentos.reduce((s,p)=>s+num(p.valor),0),falta=Math.round((total-pagos)*100)/100
 const pesquisou=busca.trim().length>=2||Boolean(categoria)||Boolean(grupo)
 function origemSelecionada(p:Produto){const id=origemPorProduto[p.id]||'';return p.estoquesRede.find(e=>e.localId===id)||null}
 function origemPadrao(p:Produto){if(localAtual&&p.estoqueLocal>0)return p.estoquesRede.find(e=>e.localId===localAtual.id)||null;return p.estoquesRede.find(e=>e.disponivel>0)||null}
 function adicionar(p:Produto){setErro('');let origem=origemSelecionada(p)||origemPadrao(p);if(!origem||origem.disponivel<=0){if(!p.permiteVendaSemEstoque)return setErro('Produto sem estoque. A regra atual bloqueia venda sem saldo para este item.');if(!localAtual)return setErro('Nenhum local padrão configurado para registrar a venda.');const chave=`${p.id}|sem-estoque`;setCarrinho(a=>{const e=a[chave];return{...a,[chave]:e?{...e,quantidade:e.quantidade+1}:{...p,chave,quantidade:1,precoUnitario:p.precoEfetivo,localOrigemId:localAtual.id,origemLabel:`${localAtual.unidadeNome} • ${localAtual.nome}`,atendimento:'sem_estoque',disponivelOrigem:0}}});return}const atendimento:ItemCarrinho['atendimento']=localAtual&&origem.localId===localAtual.id?'imediato':'posterior';const chave=`${p.id}|${origem.localId}`;setCarrinho(a=>{const e=a[chave];const qtd=Math.min(origem!.disponivel,(e?.quantidade||0)+1);return{...a,[chave]:e?{...e,quantidade:qtd}:{...p,chave,quantidade:1,precoUnitario:p.precoEfetivo,localOrigemId:origem!.localId,origemLabel:`${origem!.unidadeNome} • ${origem!.localNome}`,atendimento,disponivelOrigem:origem!.disponivel}}})}
 function mudarQuantidade(chave:string,q:number){setCarrinho(a=>{const item=a[chave];if(!item)return a;if(q<=0){const n={...a};delete n[chave];return n}const qtd=item.atendimento==='sem_estoque'?q:Math.min(item.disponivelOrigem,q);return{...a,[chave]:{...item,quantidade:qtd}}})}
 function mudarPreco(chave:string,v:string){setCarrinho(a=>a[chave]?{...a,[chave]:{...a[chave],precoUnitario:Math.max(0,num(v))}}:a)}
 function remover(chave:string){setCarrinho(a=>{const n={...a};delete n[chave];return n})}
 function mudarPagamento(i:number,patch:Partial<Pagamento>){setPagamentos(l=>l.map((p,x)=>x===i?{...p,...patch}:p))}
 function preencherRestante(i:number){setPagamentos(l=>{const outros=l.reduce((s,p,x)=>x===i?s:s+num(p.valor),0);return l.map((p,x)=>x===i?{...p,valor:String(Math.max(0,Math.round((total-outros)*100)/100))}:p)})}

 function itensPdf(snapshot:ItemCarrinho[]):ItemPdfBalcao[]{return snapshot.map(i=>({produto_id:i.id,codigo:i.codigo||null,nome:i.nome,categoria:i.categoria||'produto',descricao:i.descricao||null,foto_url:i.fotoUrl||null,unidade:i.unidade||'UN',quantidade:i.quantidade,preco_unit:i.precoUnitario,preco_total:i.quantidade*i.precoUnitario,peso_kg_m:i.pesoKgM??null,tamanho_barra_mm:i.tamanhoBarraMm??null,linha_nome:(i.grupos||[]).join(', ')||i.grupo||null}))}
 async function gerarDocumentoVenda(j:any,snapshotItens:ItemCarrinho[],snapshotPagamentos:Pagamento[],snapshotCliente:Cliente|null,snapshotDesconto:number){
  try{const usuario=await usuarioAtual();const cfg=config||await lerConfiguracaoOrcamento();const emp=empresa||await lerDadosEmpresa()||{nome:'ESQUADRIFÁCIO SOLUÇÕES EM ALUMÍNIO'};const formas=snapshotPagamentos.map(p=>`${labelForma(p.forma)} ${moeda(num(p.valor))}${p.parcelas>1?` (${p.parcelas}x)`:''}`).join(' + ');const doc=await gerarPdfOrcamentoBalcao(emp,{numero:Number(j.numero)||null,emissao:new Date().toLocaleDateString('pt-BR'),vendedorNome:usuario?.nome||'',clienteNome:snapshotCliente?.nome||'Consumidor',clienteTelefone:snapshotCliente?.telefone||null,clienteWhatsapp:snapshotCliente?.whatsapp||null,clienteEmail:snapshotCliente?.email||null,clienteCpfCnpj:snapshotCliente?.cpf_cnpj||null,clienteEndereco:[snapshotCliente?.endereco,snapshotCliente?.bairro,snapshotCliente?.cep].filter(Boolean).join(' · ')||null,clienteCidade:snapshotCliente?.cidade||null,itens:itensPdf(snapshotItens),desconto:snapshotDesconto,formaPagamento:formas,prazoEntregaDias:null,condicoes:j.itensAguardandoEstoque?`${j.itensAguardandoEstoque} item(ns) aguardando entrada de estoque.`:j.reservasPendentes?`${j.reservasPendentes} item(ns) reservado(s) em outra unidade.`:'Venda com atendimento imediato.'},{...cfg,tituloDocumento:'PEDIDO DE VENDA',mostrarFoto:true,mostrarAssinatura:true});documentoRef.current=doc;arquivoRef.current=`venda-${j.numero||'balcao'}.pdf`}catch(e){console.error('Erro ao gerar documento da venda',e)}
 }

 async function finalizar(){
  setErro('');setSucesso(null);documentoRef.current=null
  if(!caixa)return setErro('Abra o caixa antes de finalizar a venda.')
  if(!itens.length)return setErro('Adicione pelo menos um produto.')
  const semPreco=itens.find(i=>i.precoUnitario<=0);if(semPreco)return setErro(`Informe um preço válido para ${semPreco.nome}.`)
  if(Math.abs(falta)>0.01)return setErro(`Os pagamentos precisam fechar o total. Diferença: ${moeda(falta)}`)
  for(const p of pagamentos)if((p.forma==='boleto'||p.forma==='a_prazo')&&!p.primeiroVencimento)return setErro('Informe o primeiro vencimento.')
  const snapshotItens=[...itens],snapshotPagamentos=pagamentos.map(p=>({...p})),snapshotCliente=cliente?{...cliente}:null,snapshotDesconto=descontoN
  setSalvando(true)
  try{const r=await api('/api/balcao/vendas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clienteId:cliente?.id||null,clienteNome:cliente?.nome||null,desconto:descontoN,itens:itens.map(i=>({produtoId:i.id,quantidade:i.quantidade,precoUnitario:i.precoUnitario,localOrigemId:i.localOrigemId,atendimento:i.atendimento})),pagamentos:pagamentos.map(p=>({forma:p.forma,valor:num(p.valor),parcelas:p.parcelas,primeiroVencimento:p.primeiroVencimento,intervaloDias:p.intervaloDias}))})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Não foi possível finalizar.');await gerarDocumentoVenda(j,snapshotItens,snapshotPagamentos,snapshotCliente,snapshotDesconto);setSucesso({vendaId:j.vendaId,numero:Number(j.numero),total:Number(j.total),atendimentoStatus:j.atendimentoStatus,reservasPendentes:Number(j.reservasPendentes||0),itensAguardandoEstoque:Number(j.itensAguardandoEstoque||0)});setCarrinho({});setDesconto('0');setPagamentos([novoPagamento()]);setCliente(null);setClienteBusca('');await carregarCatalogo();await carregarCaixa()}catch(e){setErro(e instanceof Error?e.message:'Erro ao finalizar a venda.')}finally{setSalvando(false)}
 }

 return <main className="min-h-screen bg-slate-50 p-3"><div className="mx-auto max-w-[1540px] space-y-3">
  <header className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-3"><Link href="/balcao" className="rounded-lg border bg-white p-2"><ArrowLeft size={18}/></Link><div><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-slate-400">Venda Balcão</p><h1 className="text-xl font-bold">Nova venda</h1><p className="text-[11px] text-slate-500">{localAtual?`${localAtual.unidadeNome} • ${localAtual.nome}`:'Carregando local...'}</p></div></div><div className="flex gap-2"><Link href="/balcao/configuracoes" className="rounded-lg border bg-white px-3 py-2 text-xs font-semibold">Configurações</Link><Link href="/balcao/caixa" className={`rounded-lg px-3 py-2 text-xs font-semibold ${caixa?'border border-emerald-300 bg-emerald-50 text-emerald-800':'bg-amber-500 text-white'}`}><WalletCards size={13} className="mr-1 inline"/>{caixa?'Caixa aberto':'Abrir caixa'}</Link></div></header>
  {!vendaSemEstoqueGlobal&&<div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">Venda sem estoque está bloqueada no geral. Produtos com exceção individual ainda podem ser liberados.</div>}{erro&&<div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{erro}</div>}
  {sucesso&&<div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-800"><span>Venda #{sucesso.numero} finalizada • {moeda(sucesso.total)}{sucesso.itensAguardandoEstoque?` • ${sucesso.itensAguardandoEstoque} item(ns) aguardando estoque.`:sucesso.reservasPendentes?` • ${sucesso.reservasPendentes} reserva(s) pendente(s).`:' • atendimento imediato.'}</span><span className="flex gap-2">{documentoRef.current&&<><button onClick={()=>documentoRef.current?.save(arquivoRef.current)} className="inline-flex items-center gap-1 rounded-lg border border-emerald-300 bg-white px-2.5 py-1.5 font-semibold"><FileDown size={13}/>Baixar PDF</button><button onClick={()=>documentoRef.current&&abrirPdfParaImpressao(documentoRef.current)} className="inline-flex items-center gap-1 rounded-lg bg-emerald-700 px-2.5 py-1.5 font-semibold text-white"><Printer size={13}/>Imprimir</button></>}</span></div>}
  <section className="rounded-xl border bg-white p-3"><div className="grid gap-2 lg:grid-cols-[1fr_auto]"><div className="relative"><Search size={15} className="absolute left-3 top-2.5 text-slate-400"/><input value={cliente?cliente.nome:clienteBusca} onInput={e=>{setCliente(null);setClienteBusca(e.currentTarget.value)}} placeholder="Cliente opcional — nome, apelido, CPF/CNPJ ou telefone" className="w-full rounded-lg border py-2 pl-9 pr-3 text-xs"/>{!cliente&&carregandoClientes&&<Loader2 size={13} className="absolute right-3 top-2.5 animate-spin text-slate-400"/>}{!cliente&&clientes.length>0&&<div className="absolute z-30 mt-1 max-h-44 w-full overflow-auto rounded-lg border bg-white shadow-lg">{clientes.map(c=><button key={c.id} onClick={()=>{setCliente(c);setClienteBusca(c.nome);setClientes([])}} className="block w-full border-b px-3 py-2 text-left text-xs hover:bg-slate-50"><strong>{c.nome}</strong>{c.apelido&&<span className="ml-1 text-[9px] text-sky-700">({c.apelido})</span>}<div className="text-[10px] text-slate-400">{[c.cpf_cnpj,c.whatsapp||c.telefone,c.cidade,c.bairro].filter(Boolean).join(' • ')}</div></button>)}</div>}</div><Link href="/balcao/clientes/novo" className="inline-flex items-center justify-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-semibold"><UserPlus size={14}/>Novo cliente</Link></div></section>
  <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_400px]"><section className="min-w-0 rounded-xl border bg-white p-3"><div className="flex items-end justify-between gap-2"><div><h2 className="text-sm font-semibold">Adicionar produtos</h2><p className="text-[10px] text-slate-500">Filtre por categoria, grupo/linha ou pesquise em código, nome e descrição.</p></div><span className="text-[10px] text-slate-400">{carregando?'Filtrando...':`${produtos.length} resultado(s)`}</span></div><div className="relative mt-2"><Search size={15} className="absolute left-3 top-2.5 text-slate-400"/><input value={busca} onInput={e=>setBusca(e.currentTarget.value)} placeholder="Buscar produto... Ex.: SUPREMA ROLDANA" className="w-full rounded-lg border py-2 pl-9 pr-3 text-xs"/></div><div className="mt-3"><CatalogoFiltros categorias={categorias} grupos={grupos} categoria={categoria} grupo={grupo} onCategoria={setCategoria} onGrupo={setGrupo}/></div>
   {!pesquisou?<div className="py-10 text-center text-xs text-slate-400">Digite pelo menos 2 caracteres ou escolha um filtro.</div>:<div className="mt-3 max-h-[52vh] space-y-2 overflow-y-auto pr-1">{produtos.map(p=>{const origem=origemSelecionada(p)||origemPadrao(p);const semEstoque=p.estoqueRede<=0;return <div key={p.id} className="rounded-xl border p-3"><div className="flex gap-3">{p.fotoUrl?<img src={p.fotoUrl} alt="" className="h-11 w-11 rounded-lg object-contain"/>:<div className="h-11 w-11 rounded-lg bg-slate-100"/>}<div className="min-w-0 flex-1"><div className="text-xs font-semibold text-slate-800">{p.codigo?`${p.codigo} — `:''}{p.nome}</div>{p.descricao&&<div className="truncate text-[10px] text-slate-400">{p.descricao}</div>}<div className="mt-1 flex flex-wrap gap-2 text-[10px]"><span className={p.estoqueLocal>0?'text-emerald-700':'font-semibold text-red-600'}>Estoque local: {p.estoqueLocal} {p.unidadeEstoque}</span><span className="text-sky-700">Rede: {p.estoqueRede}</span><span className="font-semibold text-emerald-700">{moeda(p.precoEfetivo)}</span>{pesoTexto(p)&&<span className={Number(p.pesoKgM)>50?'font-semibold text-amber-700':'text-slate-500'}>{pesoTexto(p)}</span>}{semEstoque&&p.permiteVendaSemEstoque&&<span className="rounded bg-amber-50 px-1.5 py-0.5 font-semibold text-amber-700">Estoque 0 • venda liberada</span>}{semEstoque&&!p.permiteVendaSemEstoque&&<span className="rounded bg-red-50 px-1.5 py-0.5 font-semibold text-red-700">Estoque 0 • bloqueado</span>}</div>{p.grupos&&p.grupos.length>0&&<div className="mt-1 text-[9px] text-slate-400">{p.grupos.slice(0,4).join(' • ')}</div>}</div><button onClick={()=>adicionar(p)} disabled={semEstoque&&!p.permiteVendaSemEstoque} className="self-center rounded-lg bg-emerald-600 p-2 text-white disabled:bg-slate-200 disabled:text-slate-400"><Plus size={16}/></button></div>{p.estoquesRede.length>1&&<select value={origemPorProduto[p.id]||origem?.localId||''} onChange={e=>setOrigemPorProduto(a=>({...a,[p.id]:e.target.value}))} className="mt-2 w-full rounded-lg border px-2 py-1.5 text-[10px]"><option value="">Origem automática</option>{p.estoquesRede.map(e=><option key={e.localId} value={e.localId}>{e.unidadeNome} • {e.localNome} — {e.disponivel} {e.unidade}</option>)}</select>}</div>})}{!carregando&&produtos.length===0&&<div className="py-8 text-center text-xs text-slate-400">Nenhum produto encontrado.</div>}</div>}
  </section><section className="rounded-xl border bg-white p-3"><div className="mb-2 flex items-center gap-2"><ShoppingCart size={17}/><h2 className="text-sm font-semibold">Itens ({itens.length})</h2></div>{!itens.length?<div className="py-8 text-center text-xs text-slate-400">Nenhum item.</div>:<div className="max-h-[34vh] space-y-2 overflow-auto">{itens.map(i=><div key={i.chave} className={`rounded-lg border p-2 ${i.atendimento==='sem_estoque'?'border-amber-200 bg-amber-50':''}`}><div className="flex gap-2"><div className="min-w-0 flex-1"><strong className="text-[11px]">{i.codigo?`${i.codigo} — `:''}{i.nome}</strong><div className="text-[9px] text-slate-400">{i.atendimento==='sem_estoque'?'Aguardando estoque':i.origemLabel}</div></div><button onClick={()=>remover(i.chave)} className="text-red-500"><Trash2 size={14}/></button></div>{i.atendimento==='sem_estoque'&&<div className="mt-1 flex items-center gap-1 text-[9px] font-semibold text-amber-700"><AlertTriangle size={11}/>Venda sem saldo: não haverá saída de estoque.</div>}<div className="mt-2 grid grid-cols-[70px_1fr] gap-2"><input type="number" min="1" value={i.quantidade} onChange={e=>mudarQuantidade(i.chave,Math.max(1,num(e.target.value)))} className="rounded border px-2 py-1 text-xs"/><input type="number" min="0" step="any" value={i.precoUnitario} onChange={e=>mudarPreco(i.chave,e.target.value)} className="rounded border px-2 py-1 text-right text-xs"/></div></div>)}</div>}
   <div className="mt-3 border-t pt-3 text-xs"><div className="flex justify-between"><span>Subtotal</span><strong>{moeda(subtotal)}</strong></div><div className="mt-2 flex items-center justify-between gap-2"><span>Desconto</span><input value={desconto} onChange={e=>setDesconto(e.target.value)} className="w-24 rounded border px-2 py-1 text-right"/></div><div className="mt-3 flex justify-between border-t pt-2 text-base"><strong>Total</strong><strong className="text-emerald-700">{moeda(total)}</strong></div></div><div className="mt-4"><div className="mb-2 flex items-center justify-between text-xs font-semibold"><span>Pagamento</span><button onClick={()=>setPagamentos(p=>[...p,novoPagamento()])} className="text-emerald-700">+ Forma</button></div>{pagamentos.map((p,i)=><div key={i} className="mb-2 grid grid-cols-[1fr_90px_auto] gap-1"><select value={p.forma} onChange={e=>mudarPagamento(i,{forma:e.target.value})} className="rounded border px-2 py-2 text-xs">{FORMAS.map(f=><option key={f[0]} value={f[0]}>{f[1]}</option>)}</select><input value={p.valor} onChange={e=>mudarPagamento(i,{valor:e.target.value})} placeholder="Valor" className="rounded border px-2 text-xs"/><button onClick={()=>preencherRestante(i)} className="rounded border px-2 text-[9px]">resto</button>{(p.forma==='boleto'||p.forma==='a_prazo')&&<input type="date" value={p.primeiroVencimento} onChange={e=>mudarPagamento(i,{primeiroVencimento:e.target.value})} className="col-span-3 rounded border px-2 py-1 text-xs"/>}</div>)}</div><div className={`mt-2 text-right text-[10px] ${Math.abs(falta)<=.01?'text-emerald-700':'text-amber-700'}`}>{Math.abs(falta)<=.01?'Pagamento confere':`Falta ${moeda(falta)}`}</div><button onClick={finalizar} disabled={salvando||!caixa} className="mt-3 w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">{salvando?'Finalizando...':'Finalizar venda'}</button>{!caixa&&<p className="mt-1 text-center text-[9px] text-amber-600">Abra o caixa para finalizar.</p>}</section></div>
 </div></main>
}
