'use client'

import { useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Building2, MapPin, Plus, RefreshCw, Warehouse } from 'lucide-react'
import { tokenAtual } from '@/lib/auth'

type Endereco={id:string;codigo:string;zona:string|null;corredor:string|null;estante:string|null;prateleira:string|null;caixa:string|null;descricao:string|null;ativo:boolean}
type Local={id:string;codigo:string;nome:string;tipo:string;permite_venda:boolean;ativo:boolean;enderecos:Endereco[]}
type Unidade={id:string;codigo:string;nome:string;tipo:string;cidade:string|null;endereco:string|null;ativo:boolean;locais:Local[]}

export default function EstruturaEstoque(){
 const[unidades,setUnidades]=useState<Unidade[]>([]),[podeEditar,setPodeEditar]=useState(false),[erro,setErro]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true)
 const[unidadeForm,setUnidadeForm]=useState({codigo:'',nome:'',tipo:'loja',cidade:'',endereco:''})
 const[localForm,setLocalForm]=useState({unidadeId:'',codigo:'',nome:'',tipo:'geral',permiteVenda:true})
 const[endForm,setEndForm]=useState({localId:'',codigo:'',zona:'',corredor:'',estante:'',prateleira:'',caixa:'',descricao:''})
 async function api(init?:RequestInit){const t=await tokenAtual();if(!t)throw new Error('Sessão expirada.');return fetch('/api/estoque/estrutura',{...init,headers:{...(init?.headers||{}),Authorization:`Bearer ${t}`}})}
 async function carregar(){setLoading(true);setErro('');try{const r=await api();const j=await r.json();if(!r.ok)throw new Error(j.error);setUnidades(j.unidades||[]);setPodeEditar(!!j.podeEditar)}catch(e){setErro(e instanceof Error?e.message:'Erro ao carregar.')}finally{setLoading(false)}}
 useEffect(()=>{carregar()},[])
 const locais=useMemo(()=>unidades.flatMap(u=>(u.locais||[]).map(l=>({...l,unidadeNome:u.nome}))),[unidades])
 async function salvar(body:Record<string,unknown>){setErro('');setMsg('');try{const r=await api({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);setMsg('Cadastro salvo.');await carregar()}catch(e){setErro(e instanceof Error?e.message:'Erro ao salvar.')}}
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-7xl space-y-5">
  <header className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href="/estoque" className="rounded-xl border bg-white p-2.5"><ArrowLeft size={18}/></Link><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">Estoque • Configuração</p><h1 className="text-2xl font-bold">Estrutura física</h1><p className="text-sm text-slate-600">Unidades, estoques e endereços: corredor, estante, prateleira e caixa.</p></div></div><button onClick={carregar} className="rounded-xl border bg-white p-2.5"><RefreshCw size={18}/></button></header>
  {erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{msg&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</div>}
  {podeEditar&&<section className="grid gap-4 xl:grid-cols-3">
   <FormCard icon={<Building2/>} titulo="Nova unidade / loja"><Campo label="Código" v={unidadeForm.codigo} set={v=>setUnidadeForm({...unidadeForm,codigo:v})}/><Campo label="Nome" v={unidadeForm.nome} set={v=>setUnidadeForm({...unidadeForm,nome:v})}/><select value={unidadeForm.tipo} onChange={e=>setUnidadeForm({...unidadeForm,tipo:e.target.value})} className="w-full rounded-xl border px-3 py-2 text-sm"><option value="matriz">Matriz</option><option value="fabrica">Fábrica</option><option value="loja">Loja</option><option value="deposito">Depósito</option><option value="unidade">Unidade</option></select><Campo label="Cidade" v={unidadeForm.cidade} set={v=>setUnidadeForm({...unidadeForm,cidade:v})}/><button onClick={()=>salvar({acao:'unidade',...unidadeForm})} className="w-full rounded-xl bg-slate-900 px-3 py-2.5 text-sm font-semibold text-white"><Plus size={15} className="mr-1 inline"/>Criar unidade</button></FormCard>
   <FormCard icon={<Warehouse/>} titulo="Novo local de estoque"><select value={localForm.unidadeId} onChange={e=>setLocalForm({...localForm,unidadeId:e.target.value})} className="w-full rounded-xl border px-3 py-2 text-sm"><option value="">Escolha a unidade</option>{unidades.map(u=><option key={u.id} value={u.id}>{u.nome}</option>)}</select><Campo label="Código" v={localForm.codigo} set={v=>setLocalForm({...localForm,codigo:v})}/><Campo label="Nome" v={localForm.nome} set={v=>setLocalForm({...localForm,nome:v})}/><select value={localForm.tipo} onChange={e=>setLocalForm({...localForm,tipo:e.target.value})} className="w-full rounded-xl border px-3 py-2 text-sm"><option value="geral">Geral</option><option value="materia_prima">Matéria-prima</option><option value="produto_acabado">Produto acabado</option><option value="loja">Loja</option><option value="deposito">Depósito</option><option value="transito">Trânsito</option><option value="avariado">Avariado</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={localForm.permiteVenda} onChange={e=>setLocalForm({...localForm,permiteVenda:e.target.checked})}/>Permite venda</label><button onClick={()=>salvar({acao:'local',...localForm})} className="w-full rounded-xl bg-slate-900 px-3 py-2.5 text-sm font-semibold text-white"><Plus size={15} className="mr-1 inline"/>Criar local</button></FormCard>
   <FormCard icon={<MapPin/>} titulo="Novo endereço"><select value={endForm.localId} onChange={e=>setEndForm({...endForm,localId:e.target.value})} className="w-full rounded-xl border px-3 py-2 text-sm"><option value="">Escolha o local</option>{locais.map(l=><option key={l.id} value={l.id}>{l.unidadeNome} • {l.nome}</option>)}</select><Campo label="Código do endereço" v={endForm.codigo} set={v=>setEndForm({...endForm,codigo:v})}/><div className="grid grid-cols-2 gap-2"><Campo label="Zona" v={endForm.zona} set={v=>setEndForm({...endForm,zona:v})}/><Campo label="Corredor" v={endForm.corredor} set={v=>setEndForm({...endForm,corredor:v})}/><Campo label="Estante" v={endForm.estante} set={v=>setEndForm({...endForm,estante:v})}/><Campo label="Prateleira" v={endForm.prateleira} set={v=>setEndForm({...endForm,prateleira:v})}/><Campo label="Caixa / gaveta" v={endForm.caixa} set={v=>setEndForm({...endForm,caixa:v})}/></div><button onClick={()=>salvar({acao:'endereco',...endForm})} className="w-full rounded-xl bg-slate-900 px-3 py-2.5 text-sm font-semibold text-white"><Plus size={15} className="mr-1 inline"/>Criar endereço</button></FormCard>
  </section>}
  <section className="space-y-4">{loading?<div className="rounded-2xl border bg-white p-8 text-center">Carregando...</div>:unidades.map(u=><div key={u.id} className="rounded-2xl border bg-white p-5"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><Building2 size={18}/><h2 className="font-bold">{u.nome}</h2><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs">{u.codigo}</span></div><p className="mt-1 text-xs text-slate-500">{u.tipo}{u.cidade?` • ${u.cidade}`:''}</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2">{(u.locais||[]).map(l=><div key={l.id} className="rounded-xl border bg-slate-50 p-4"><div className="flex items-center justify-between"><div><div className="font-semibold">{l.nome}</div><div className="text-xs text-slate-500">{l.codigo} • {l.tipo}</div></div><span className={`rounded-full px-2 py-1 text-[11px] ${l.permite_venda?'bg-emerald-100 text-emerald-800':'bg-slate-200 text-slate-600'}`}>{l.permite_venda?'Venda permitida':'Sem venda'}</span></div><div className="mt-3 space-y-2">{(l.enderecos||[]).map(e=><div key={e.id} className="rounded-lg bg-white p-2 text-xs"><strong className="font-mono">{e.codigo}</strong><span className="ml-2 text-slate-500">{[e.zona&&`Zona ${e.zona}`,e.corredor&&`C${e.corredor}`,e.estante&&`E${e.estante}`,e.prateleira&&`P${e.prateleira}`,e.caixa&&`Cx ${e.caixa}`].filter(Boolean).join(' • ')||'Endereço sem detalhamento'}</span></div>)}{!(l.enderecos||[]).length&&<div className="text-xs text-slate-400">Nenhum corredor/prateleira cadastrado.</div>}</div></div>)}</div></div>)}</section>
 </div></main>
}
function FormCard({icon,titulo,children}:{icon:React.ReactNode;titulo:string;children:React.ReactNode}){return <div className="space-y-3 rounded-2xl border bg-white p-5"><div className="flex items-center gap-2 font-bold">{icon}{titulo}</div>{children}</div>}
function Campo({label,v,set}:{label:string;v:string;set:(v:string)=>void}){return <label className="block text-xs font-medium text-slate-500">{label}<input value={v} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></label>}
