'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ClipboardList, Search, Send, MessageCircle } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { anexarAoPedido, criarPedidoCompartilhado } from '@/lib/chatInterno'

type Cliente={id:string;nome:string;cidade?:string|null;whatsapp?:string|null}
type Pedido={id:string;numero?:number|null;cliente_id?:string|null;created_at:string;observacoes?:string|null}
export default function CompartilharPage(){
 const [texto,setTexto]=useState(''),[clientes,setClientes]=useState<Cliente[]>([]),[clienteId,setClienteId]=useState(''),[busca,setBusca]=useState('')
 const [pedidos,setPedidos]=useState<Pedido[]>([]),[modo,setModo]=useState<'novo'|'existente'>('novo'),[pedidoId,setPedidoId]=useState(''),[salvando,setSalvando]=useState(false),[ok,setOk]=useState('')
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setTexto(q.get('text')||q.get('title')||'');supabase.from('clientes').select('id,nome,cidade,whatsapp').order('nome').limit(1000).then(r=>setClientes((r.data||[]) as Cliente[]))},[])
 useEffect(()=>{if(!clienteId){setPedidos([]);return}supabase.from('orcamentos').select('id,numero,cliente_id,created_at,observacoes').eq('cliente_id',clienteId).order('created_at',{ascending:false}).limit(20).then(r=>setPedidos((r.data||[]) as Pedido[]))},[clienteId])
 const filtrados=useMemo(()=>{const q=busca.toLocaleLowerCase('pt-BR').trim();if(q.length<2)return clientes.slice(0,30);return clientes.filter(c=>(c.nome+' '+(c.cidade||'')+' '+(c.whatsapp||'')).toLocaleLowerCase('pt-BR').includes(q)).slice(0,30)},[clientes,busca])
 async function enviar(){if(!clienteId||!texto.trim())return;setSalvando(true);setOk('');if(modo==='existente'&&pedidoId){const certo=await anexarAoPedido(pedidoId,texto);setOk(certo?'Informação adicionada ao pedido existente.':'Não foi possível adicionar.')}else{const r=await criarPedidoCompartilhado({clienteId,texto});setOk(r.ok?'Pedido criado no Kanban em Fazer orçamento.':r.error||'Não foi possível criar o pedido.')}setSalvando(false)}
 return <main className="min-h-screen bg-slate-100 p-4"><div className="mx-auto max-w-2xl rounded-2xl border bg-white shadow-sm"><header className="flex items-center justify-between border-b p-4"><div className="flex items-center gap-3"><Link href="/" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft size={19}/></Link><div><h1 className="font-bold">Enviar para o Atlas</h1><p className="text-xs text-slate-500">WhatsApp → cliente → Kanban</p></div></div><Link href="/chat" className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold"><MessageCircle size={16}/>Chat</Link></header>
 <div className="space-y-5 p-4 md:p-6"><section><label className="text-xs font-bold uppercase text-slate-500">1. Conteúdo recebido</label><textarea value={texto} onChange={e=>setTexto(e.target.value)} rows={7} placeholder="Cole aqui a mensagem, pedido, medidas ou observações que vieram do WhatsApp." className="mt-2 w-full rounded-xl border p-3 text-sm outline-none focus:ring-2 focus:ring-blue-200"/></section>
 <section><label className="text-xs font-bold uppercase text-slate-500">2. Vincular cliente</label><div className="mt-2 flex items-center gap-2 rounded-xl border px-3"><Search size={16} className="text-slate-400"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Digite nome, cidade ou telefone" className="w-full py-3 text-sm outline-none"/></div><div className="mt-2 max-h-52 overflow-y-auto rounded-xl border">{filtrados.map(c=><button key={c.id} onClick={()=>setClienteId(c.id)} className={"flex w-full justify-between border-b px-3 py-3 text-left text-sm "+(clienteId===c.id?'bg-blue-50':'hover:bg-slate-50')}><span><b>{c.nome}</b><small className="block text-slate-400">{c.cidade||'Cidade não informada'} {c.whatsapp?' · '+c.whatsapp:''}</small></span>{clienteId===c.id&&<span className="font-bold text-blue-600">Selecionado</span>}</button>)}</div></section>
 {clienteId&&<section><label className="text-xs font-bold uppercase text-slate-500">3. Destino</label><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>setModo('novo')} className={"rounded-xl border p-3 text-sm font-bold "+(modo==='novo'?'border-blue-500 bg-blue-50 text-blue-700':'')}>Novo pedido</button><button onClick={()=>setModo('existente')} className={"rounded-xl border p-3 text-sm font-bold "+(modo==='existente'?'border-blue-500 bg-blue-50 text-blue-700':'')}>Pedido já aberto</button></div>{modo==='existente'&&<select value={pedidoId} onChange={e=>setPedidoId(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm"><option value="">Selecione o pedido</option>{pedidos.map(p=><option key={p.id} value={p.id}>#{p.numero||'—'} · {new Date(p.created_at).toLocaleDateString('pt-BR')}</option>)}</select>}</section>}
 {ok&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{ok}</div>}
 <button onClick={()=>void enviar()} disabled={salvando||!clienteId||!texto.trim()||(modo==='existente'&&!pedidoId)} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3.5 font-bold text-white disabled:opacity-40">{modo==='novo'?<ClipboardList size={18}/>:<Send size={18}/>} {salvando?'Enviando...':modo==='novo'?'Enviar para Fazer orçamento':'Adicionar ao pedido'}</button></div></div></main>
}
