'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { ArrowLeft, Calculator, Check, CircleDollarSign, Loader2, Plus, RefreshCw, Save, Settings2, Shuffle, Trash2, TriangleAlert } from 'lucide-react'
import {
  adicionarComponenteOrcamento,
  adicionarCustoExtra,
  carregarPrecificacaoOrcamento,
  excluirComponentePrecificacao,
  gerarBasePrecificacao,
  removerComponenteOrcamento,
  salvarCustoComponente,
  salvarPoliticaGeral,
  salvarPoliticaItem,
  trocarComponenteOrcamento,
  type CategoriaPrecificacao,
  type ComponentePrecificacao,
  type PrecificacaoOrcamento,
  type ProdutoPrecificacao,
} from '@/lib/orcamentoPrecificacao'

const ABAS: Array<{id:string;label:string;cats:CategoriaPrecificacao[]}> = [
  { id:'perfis', label:'Perfis', cats:['perfil'] },
  { id:'acessorios', label:'Acessórios', cats:['acessorio'] },
  { id:'vidros', label:'Vidros', cats:['vidro'] },
  { id:'servicos', label:'Serviços / Despesas', cats:['mao_obra','instalacao','deslocamento','frete','pintura','terceiro','consumivel','outro'] },
  { id:'resumo', label:'Resumo', cats:[] },
]
const EXTRA_CATS: Array<{value:CategoriaPrecificacao;label:string}> = [
  {value:'mao_obra',label:'Mão de obra fabricação'},{value:'instalacao',label:'Instalação'},{value:'deslocamento',label:'Deslocamento'},
  {value:'frete',label:'Frete'},{value:'pintura',label:'Pintura / beneficiamento'},{value:'terceiro',label:'Terceiros'},
  {value:'consumivel',label:'Consumíveis'},{value:'outro',label:'Outros'},
]
function money(v:any){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function pct(v:any){return Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2})}
function itemRef(item:any,index:number){return String(item?.id||`item-${index+1}`)}
function itemLabel(item:any,index:number){return item?.ambiente ? `${item.ambiente} · ${item.tipo_outro_texto||item.tipo_esquadria||item.tipo||`Item ${index+1}`}` : (item?.tipo_outro_texto||item?.tipo_esquadria||item?.tipo||`Item ${index+1}`)}

export default function PrecificacaoOrcamentoPage(){
  const params=useParams(); const orcamentoId=String(params?.id||'')
  const [dados,setDados]=useState<PrecificacaoOrcamento|null>(null)
  const [aba,setAba]=useState('perfis'),[carregando,setCarregando]=useState(true),[ocupado,setOcupado]=useState(false)
  const [erro,setErro]=useState(''),[mensagem,setMensagem]=useState('')
  const [margemGeral,setMargemGeral]=useState('40'),[sobraGeral,setSobraGeral]=useState(false)
  const [perdaCorte,setPerdaCorte]=useState('0'),[sobraMinima,setSobraMinima]=useState('300')
  const [extra,setExtra]=useState({categoria:'mao_obra' as CategoriaPrecificacao,item_ref:'',descricao:'',quantidade:'1',custo:'0'})
  const [troca,setTroca]=useState<{componente:ComponentePrecificacao;produtoId:string;escopo:'orcamento'|'tipologia_definitiva';justificativa:string}|null>(null)
  const [adicao,setAdicao]=useState<{item_ref:string;tipo:'perfil'|'acessorio'|'vidro'|'outro';produtoId:string;descricao:string;quantidade:string;comprimento:string;justificativa:string}|null>(null)

  useEffect(()=>{if(orcamentoId)void carregar(true)},[orcamentoId])
  async function carregar(gerarSeVazio=false){
    setCarregando(true);setErro('')
    let d=await carregarPrecificacaoOrcamento(orcamentoId)
    if(d&&!d.pacote&&gerarSeVazio){const g=await gerarBasePrecificacao(orcamentoId,{perdaCorteMm:0,minimoSobraReaproveitavelMm:300});if(!g.ok)setErro(g.error);d=await carregarPrecificacaoOrcamento(orcamentoId)}
    setDados(d)
    if(d){setMargemGeral(String(d.orcamento.margem_padrao_pct??40));setSobraGeral(Boolean(d.orcamento.cobrar_sobra_padrao));setPerdaCorte(String(d.pacote?.perda_corte_mm??0));setSobraMinima(String(d.pacote?.minimo_sobra_reaproveitavel_mm??300))}
    setCarregando(false)
  }
  async function recalcular(){setOcupado(true);setErro('');setMensagem('');const r=await gerarBasePrecificacao(orcamentoId,{perdaCorteMm:Number(perdaCorte.replace(',','.'))||0,minimoSobraReaproveitavelMm:Number(sobraMinima.replace(',','.'))||0});setOcupado(false);if(!r.ok){setErro(r.error);return}setMensagem('Otimização e precificação recalculadas.');await carregar()}
  async function salvarGeral(){setOcupado(true);const r=await salvarPoliticaGeral(orcamentoId,Number(margemGeral.replace(',','.'))||0,sobraGeral);setOcupado(false);if(!r.ok){setErro(r.error);return}setMensagem('Política geral atualizada.');await carregar()}

  const itens=Array.isArray(dados?.orcamento?.itens)?dados!.orcamento.itens:[]
  const politicas=useMemo(()=>new Map((dados?.politicas||[]).map(p=>[p.item_ref,p])),[dados?.politicas])
  const componentesAba=useMemo(()=>{const cfg=ABAS.find(a=>a.id===aba);return (dados?.componentes||[]).filter(c=>cfg?.cats.includes(c.categoria))},[dados?.componentes,aba])
  const produtosTroca=useMemo(()=>{if(!troca||!dados)return[];const cat=troca.componente.categoria==='perfil'?'perfil':'acessorio';return dados.produtos.filter(p=>p.categoria===cat)},[troca,dados])
  const totalCusto=(dados?.politicas||[]).reduce((s,p)=>s+Number(p.custo_total||0),0)+(dados?.componentes||[]).filter(c=>!c.item_ref).reduce((s,c)=>s+Number(c.custo_total||0),0)
  const totalVenda=Number(dados?.orcamento?.valor_estimado||0)
  const margemReal=totalVenda>0?(1-totalCusto/totalVenda)*100:0

  async function mudarPoliticaItem(ref:string,patch:any){setOcupado(true);const r=await salvarPoliticaItem(orcamentoId,ref,patch);setOcupado(false);if(!r.ok)setErro(r.error);else await carregar()}
  async function editarCusto(c:ComponentePrecificacao){const atual=String(c.custo_unitario||0).replace('.',',');const valor=window.prompt(`Custo unitário de ${c.codigo||c.descricao}:`,atual);if(valor==null)return;const n=Number(valor.replace(',','.'));if(!Number.isFinite(n)||n<0)return;const salvar=window.confirm('Salvar este custo no catálogo para os próximos orçamentos?');setOcupado(true);const r=await salvarCustoComponente(c,n,salvar);setOcupado(false);if(!r.ok)setErro(r.error);else{setMensagem(salvar?'Custo atualizado e salvo no catálogo.':'Custo alterado somente neste orçamento.');await carregar()}}
  async function remover(c:ComponentePrecificacao){if(c.incluido_manual){if(!window.confirm(`Remover ${c.descricao} deste orçamento?`))return;setOcupado(true);const r=await excluirComponentePrecificacao(c.id,orcamentoId);setOcupado(false);if(!r.ok)setErro(r.error);else await carregar();return}
    const motivo=window.prompt(`Motivo para retirar ${c.codigo||c.descricao} deste orçamento:`,'')||'';if(motivo.trim().length<3)return
    const item=itens.find((x:any,i:number)=>itemRef(x,i)===c.item_ref);const tipo=c.categoria==='perfil'?'perfil':c.categoria==='acessorio'?'acessorio':c.categoria==='vidro'?'vidro':'outro'
    setOcupado(true);const r=await removerComponenteOrcamento({orcamentoId,itemRef:c.item_ref||'',tipologiaId:item?.tipologia_id||item?.tipologiaId||null,formulaId:item?.tipologia_id?dados?.formulas[item.tipologia_id]?.id:null,componenteTipo:tipo,codigoOrigem:c.codigo||null,produtoOrigemId:c.produto_id||null,justificativa:motivo});setOcupado(false);if(!r.ok)setErro(r.error);else{setMensagem('Componente retirado somente deste orçamento, com histórico.');await carregar()}}
  async function confirmarTroca(){if(!troca||!dados)return;const destino=dados.produtos.find(p=>p.id===troca.produtoId);if(!destino){setErro('Escolha o novo componente.');return}if(troca.justificativa.trim().length<3){setErro('Informe o motivo da troca.');return}
    const item=itens.find((x:any,i:number)=>itemRef(x,i)===troca.componente.item_ref);const tipologiaId=item?.tipologia_id||item?.tipologiaId||null;const formulaId=tipologiaId?dados.formulas[tipologiaId]?.id:null
    setOcupado(true);const r=await trocarComponenteOrcamento({orcamentoId,itemRef:troca.componente.item_ref||'',tipologiaId,formulaId,componenteTipo:troca.componente.categoria==='perfil'?'perfil':'acessorio',codigoOrigem:troca.componente.codigo||'',produtoOrigemId:troca.componente.produto_id||null,produtoDestino:destino,justificativa:troca.justificativa,escopo:troca.escopo});setOcupado(false);if(!r.ok){setErro(r.error);return}setTroca(null);setMensagem(troca.escopo==='tipologia_definitiva'?'Tipologia atualizada em nova versão. Histórico preservado.':'Troca aplicada apenas neste orçamento.');await carregar()}
  async function confirmarAdicao(){if(!adicao||!dados)return;const prod=adicao.produtoId?dados.produtos.find(p=>p.id===adicao.produtoId):null;if(adicao.justificativa.trim().length<3){setErro('Informe o motivo da inclusão.');return}const item=itens.find((x:any,i:number)=>itemRef(x,i)===adicao.item_ref);const tipologiaId=item?.tipologia_id||item?.tipologiaId||null
    setOcupado(true);const r=await adicionarComponenteOrcamento({orcamentoId,itemRef:adicao.item_ref,tipologiaId,formulaId:tipologiaId?dados.formulas[tipologiaId]?.id:null,componenteTipo:adicao.tipo,produto:prod||null,descricao:adicao.descricao,quantidade:Number(adicao.quantidade.replace(',','.'))||1,comprimentoMm:adicao.comprimento?Number(adicao.comprimento.replace(',','.')):null,justificativa:adicao.justificativa});setOcupado(false);if(!r.ok){setErro(r.error);return}setAdicao(null);setMensagem('Componente adicional incluído neste orçamento com histórico.');await carregar()}
  async function adicionarExtra(){if(!extra.descricao.trim())return;setOcupado(true);const r=await adicionarCustoExtra({orcamentoId,itemRef:extra.item_ref||null,categoria:extra.categoria,descricao:extra.descricao,quantidade:Number(extra.quantidade.replace(',','.'))||1,custoUnitario:Number(extra.custo.replace(',','.'))||0});setOcupado(false);if(!r.ok){setErro(r.error);return}setExtra({categoria:'mao_obra',item_ref:'',descricao:'',quantidade:'1',custo:'0'});await carregar()}

  if(carregando)return <div className="grid min-h-screen place-items-center bg-slate-50 text-slate-500"><Loader2 className="animate-spin"/></div>
  if(!dados)return <div className="grid min-h-screen place-items-center bg-slate-50 text-slate-500">Orçamento não encontrado.</div>

  return <main className="min-h-screen bg-slate-50 p-4 md:p-7"><div className="mx-auto max-w-7xl space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/kanban" className="mb-2 inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={16}/> Voltar</Link><div className="flex items-center gap-3"><Calculator className="text-emerald-600"/><div><h1 className="text-2xl font-bold text-slate-900">Otimização e Precificação</h1><p className="text-sm text-slate-500">Orçamento #{dados.orcamento.numero||'—'} · {dados.orcamento.clientes?.nome||dados.orcamento.cliente_nome||'Cliente'} · tipologias → otimização → preço.</p></div></div></div><div className="flex gap-2"><Link href="/engenharia/historico-tipologias" className="rounded-xl border bg-white px-3 py-2 text-sm font-semibold">Histórico de tipologias</Link><button disabled={ocupado} onClick={()=>void recalcular()} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{ocupado?<Loader2 size={15} className="animate-spin"/>:<RefreshCw size={15}/>} Recalcular</button></div></header>
    {erro&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{erro}</div>}{mensagem&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{mensagem}</div>}

    <section className="grid gap-3 rounded-2xl border bg-white p-5 lg:grid-cols-[1fr_1fr_1fr_1fr_auto]"><label className="text-xs font-semibold text-slate-600">Margem geral %<input value={margemGeral} onChange={e=>setMargemGeral(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></label><label className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-3 text-sm font-semibold"><input type="checkbox" checked={sobraGeral} onChange={e=>setSobraGeral(e.target.checked)}/> Cobrar sobra por padrão</label><label className="text-xs font-semibold text-slate-600">Perda de serra por corte (mm)<input value={perdaCorte} onChange={e=>setPerdaCorte(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Sobra mínima reaproveitável (mm)<input value={sobraMinima} onChange={e=>setSobraMinima(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></label><button onClick={()=>void salvarGeral()} disabled={ocupado} className="self-end rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white"><Save size={15} className="mr-1 inline"/>Salvar</button></section>

    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border bg-white p-4"><p className="text-xs uppercase text-slate-400">Preço do orçamento</p><p className="mt-1 text-xl font-bold">{money(totalVenda)}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs uppercase text-slate-400">Custo otimizado</p><p className="mt-1 text-xl font-bold">{money(dados.orcamento.custo_otimizado||totalCusto)}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs uppercase text-slate-400">Sobra cobrada</p><p className="mt-1 text-xl font-bold">{money(dados.orcamento.custo_sobra_cobrada)}</p><p className="text-[11px] text-slate-400">entra a custo, sem margem</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-xs uppercase text-slate-400">Margem estimada</p><p className="mt-1 text-xl font-bold">{pct(margemReal)}%</p></div></section>

    {dados.pendencias.length>0&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-center gap-2 font-bold text-amber-800"><TriangleAlert size={17}/> Pendências antes de fechar o preço</div><div className="mt-2 grid gap-1 text-xs text-amber-800">{dados.pendencias.slice(0,12).map((p,i)=><p key={i}>• {p}</p>)}</div></section>}

    <section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><Settings2 size={17}/><h2 className="font-bold">Margem e sobra por tipologia/item</h2></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{itens.map((item:any,i:number)=>{const ref=itemRef(item,i);const p:any=politicas.get(ref)||{};return <div key={ref} className="rounded-xl border p-4"><div className="font-semibold text-slate-800">{itemLabel(item,i)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={p.margem_herda_geral!==false} onChange={e=>void mudarPoliticaItem(ref,{margem_herda_geral:e.target.checked})}/> Usar margem geral</label>{p.margem_herda_geral===false&&<input defaultValue={p.margem_pct??dados.orcamento.margem_padrao_pct} onBlur={e=>void mudarPoliticaItem(ref,{margem_pct:Number(e.target.value.replace(',','.'))||0})} className="mt-2 w-full rounded-lg border px-2 py-1.5 text-sm"/>}</div><div><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={p.sobra_herda_geral!==false} onChange={e=>void mudarPoliticaItem(ref,{sobra_herda_geral:e.target.checked})}/> Usar regra geral de sobra</label>{p.sobra_herda_geral===false&&<label className="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(p.cobrar_sobra)} onChange={e=>void mudarPoliticaItem(ref,{cobrar_sobra:e.target.checked})}/> Cobrar sobra deste item</label>}</div></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div className="rounded-lg bg-slate-50 p-2"><span className="text-slate-400">Custo</span><b className="block">{money(p.custo_total)}</b></div><div className="rounded-lg bg-slate-50 p-2"><span className="text-slate-400">Sobra</span><b className="block">{money(p.custo_sobra)}</b></div><div className="rounded-lg bg-emerald-50 p-2"><span className="text-emerald-600">Venda</span><b className="block text-emerald-800">{money(p.preco_venda)}</b></div></div></div>})}</div></section>

    <div className="overflow-x-auto border-b"><div className="flex min-w-max gap-1">{ABAS.map(a=><button key={a.id} onClick={()=>setAba(a.id)} className={`border-b-2 px-4 py-3 text-sm font-semibold ${aba===a.id?'border-emerald-600 text-emerald-700':'border-transparent text-slate-500'}`}>{a.label}</button>)}</div></div>

    {aba!=='resumo'&&<section className="rounded-2xl border bg-white overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><h2 className="font-bold">{ABAS.find(a=>a.id===aba)?.label}</h2><p className="text-xs text-slate-500">Edite custo sem sair do orçamento. Custo salvo no catálogo vale para os próximos.</p></div>{aba!=='servicos'&&<button onClick={()=>setAdicao({item_ref:itemRef(itens[0],0),tipo:aba==='perfis'?'perfil':aba==='acessorios'?'acessorio':aba==='vidros'?'vidro':'outro',produtoId:'',descricao:'',quantidade:'1',comprimento:'',justificativa:''})} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-sm font-semibold"><Plus size={14}/> Adicionar componente</button>}</div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th className="px-4 py-3">Item</th><th className="px-4 py-3">Código / descrição</th><th className="px-4 py-3">Qtd.</th><th className="px-4 py-3">Custo unit.</th><th className="px-4 py-3">Custo total</th><th className="px-4 py-3">Margem</th><th className="px-4 py-3">Venda</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y">{componentesAba.map(c=><tr key={c.id} className={c.custo_pendente?'bg-amber-50/60':''}><td className="px-4 py-3 text-xs">{c.item_ref?(()=>{const idx=itens.findIndex((x:any,i:number)=>itemRef(x,i)===c.item_ref);return idx>=0?itemLabel(itens[idx],idx):c.item_ref})():'Geral'}</td><td className="px-4 py-3"><b>{c.codigo||'—'}</b><div className="text-xs text-slate-500">{c.descricao}</div>{c.custo_pendente&&<span className="text-[11px] font-semibold text-amber-700">Custo pendente</span>}</td><td className="px-4 py-3">{c.quantidade} {c.unidade}</td><td className="px-4 py-3"><button onClick={()=>void editarCusto(c)} className="rounded-lg border px-2 py-1 font-semibold hover:bg-slate-50">{money(c.custo_unitario)}</button></td><td className="px-4 py-3">{money(c.custo_total)}</td><td className="px-4 py-3">{pct(c.margem_pct)}%</td><td className="px-4 py-3 font-semibold text-emerald-700">{money(c.preco_venda)}</td><td className="px-4 py-3"><div className="flex gap-1">{(c.categoria==='perfil'||c.categoria==='acessorio')&&c.codigo&&c.item_ref&&<button onClick={()=>setTroca({componente:c,produtoId:'',escopo:'orcamento',justificativa:''})} title="Trocar" className="rounded-lg border p-2"><Shuffle size={14}/></button>}<button onClick={()=>void remover(c)} title="Remover" className="rounded-lg border p-2 text-red-600"><Trash2 size={14}/></button></div></td></tr>)}{componentesAba.length===0&&<tr><td colSpan={8} className="px-5 py-8 text-center text-slate-400">Nenhum componente nesta aba.</td></tr>}</tbody></table></div></section>}

    {aba==='servicos'&&<section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Adicionar mão de obra / despesa</h3><div className="mt-3 grid gap-3 md:grid-cols-5"><select value={extra.categoria} onChange={e=>setExtra({...extra,categoria:e.target.value as CategoriaPrecificacao})} className="rounded-xl border px-3 py-2 text-sm">{EXTRA_CATS.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><select value={extra.item_ref} onChange={e=>setExtra({...extra,item_ref:e.target.value})} className="rounded-xl border px-3 py-2 text-sm"><option value="">Geral do orçamento</option>{itens.map((it:any,i:number)=><option key={itemRef(it,i)} value={itemRef(it,i)}>{itemLabel(it,i)}</option>)}</select><input placeholder="Descrição" value={extra.descricao} onChange={e=>setExtra({...extra,descricao:e.target.value})} className="rounded-xl border px-3 py-2 text-sm"/><input placeholder="Qtd." value={extra.quantidade} onChange={e=>setExtra({...extra,quantidade:e.target.value})} className="rounded-xl border px-3 py-2 text-sm"/><div className="flex gap-2"><input placeholder="Custo" value={extra.custo} onChange={e=>setExtra({...extra,custo:e.target.value})} className="min-w-0 flex-1 rounded-xl border px-3 py-2 text-sm"/><button onClick={()=>void adicionarExtra()} className="rounded-xl bg-slate-900 px-3 text-white"><Plus size={16}/></button></div></div></section>}

    {aba==='resumo'&&<section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Aproveitamento das barras</h2><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-50 p-3">Barras novas<b className="block text-xl">{dados.barras.filter(b=>b.fonte_tipo==='barra_nova').length}</b></div><div className="rounded-xl bg-slate-50 p-3">Sobras reutilizadas<b className="block text-xl">{dados.barras.filter(b=>b.fonte_tipo==='sobra_estoque').length}</b></div><div className="rounded-xl bg-slate-50 p-3">Sobra total<b className="block text-xl">{Math.round(dados.barras.reduce((s,b)=>s+Number(b.sobra_final_mm||0),0))} mm</b></div><div className="rounded-xl bg-slate-50 p-3">Peças de corte<b className="block text-xl">{dados.cortes.length}</b></div></div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Fechamento</h2><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span>Custo otimizado</span><b>{money(dados.orcamento.custo_otimizado)}</b></div><div className="flex justify-between"><span>Sobra repassada a custo</span><b>{money(dados.orcamento.custo_sobra_cobrada)}</b></div><div className="flex justify-between border-t pt-3 text-lg"><span>Preço final</span><b className="text-emerald-700">{money(dados.orcamento.valor_estimado)}</b></div></div><p className="mt-3 text-xs text-slate-500">A simulação do orçamento não reserva estoque. A reserva física acontece depois da venda e da conferência do projeto.</p></div></section>}
  </div>

  {troca&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-xl"><h2 className="font-bold">Trocar {troca.componente.categoria==='perfil'?'perfil':'acessório'}</h2><p className="mt-1 text-sm text-slate-500">Atual: {troca.componente.codigo} · {troca.componente.descricao}</p><label className="mt-4 block text-xs font-semibold">Novo componente<select value={troca.produtoId} onChange={e=>setTroca({...troca,produtoId:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"><option value="">Selecione...</option>{produtosTroca.map(p=><option key={p.id} value={p.id}>{p.codigo} · {p.nome}</option>)}</select></label><div className="mt-4 grid gap-2 sm:grid-cols-2"><label className={`rounded-xl border p-3 text-sm ${troca.escopo==='orcamento'?'border-emerald-500 bg-emerald-50':''}`}><input type="radio" checked={troca.escopo==='orcamento'} onChange={()=>setTroca({...troca,escopo:'orcamento'})}/> <b>Só neste orçamento</b><span className="mt-1 block text-xs text-slate-500">A tipologia original não muda.</span></label><label className={`rounded-xl border p-3 text-sm ${troca.escopo==='tipologia_definitiva'?'border-violet-500 bg-violet-50':''}`}><input type="radio" checked={troca.escopo==='tipologia_definitiva'} onChange={()=>setTroca({...troca,escopo:'tipologia_definitiva'})}/> <b>Alterar tipologia definitivamente</b><span className="mt-1 block text-xs text-slate-500">Cria nova versão e mantém histórico/rollback.</span></label></div><textarea value={troca.justificativa} onChange={e=>setTroca({...troca,justificativa:e.target.value})} placeholder="Motivo obrigatório da troca" rows={3} className="mt-4 w-full rounded-xl border px-3 py-2 text-sm"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setTroca(null)} className="rounded-xl border px-4 py-2 text-sm">Cancelar</button><button disabled={ocupado} onClick={()=>void confirmarTroca()} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Confirmar troca</button></div></div></div>}

  {adicao&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-5"><h2 className="font-bold">Adicionar componente neste orçamento</h2><div className="mt-4 grid gap-3"><select value={adicao.item_ref} onChange={e=>setAdicao({...adicao,item_ref:e.target.value})} className="rounded-xl border px-3 py-2 text-sm">{itens.map((it:any,i:number)=><option key={itemRef(it,i)} value={itemRef(it,i)}>{itemLabel(it,i)}</option>)}</select>{(adicao.tipo==='perfil'||adicao.tipo==='acessorio')&&<select value={adicao.produtoId} onChange={e=>setAdicao({...adicao,produtoId:e.target.value})} className="rounded-xl border px-3 py-2 text-sm"><option value="">Escolha do catálogo ou descreva manualmente</option>{dados.produtos.filter(p=>p.categoria===adicao.tipo).map(p=><option key={p.id} value={p.id}>{p.codigo} · {p.nome}</option>)}</select>}<input value={adicao.descricao} onChange={e=>setAdicao({...adicao,descricao:e.target.value})} placeholder="Descrição se não escolher do catálogo" className="rounded-xl border px-3 py-2 text-sm"/><div className="grid grid-cols-2 gap-3"><input value={adicao.quantidade} onChange={e=>setAdicao({...adicao,quantidade:e.target.value})} placeholder="Quantidade" className="rounded-xl border px-3 py-2 text-sm"/><input value={adicao.comprimento} onChange={e=>setAdicao({...adicao,comprimento:e.target.value})} placeholder="Comprimento mm (se aplicável)" className="rounded-xl border px-3 py-2 text-sm"/></div><textarea value={adicao.justificativa} onChange={e=>setAdicao({...adicao,justificativa:e.target.value})} placeholder="Motivo da inclusão" rows={3} className="rounded-xl border px-3 py-2 text-sm"/></div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setAdicao(null)} className="rounded-xl border px-4 py-2 text-sm">Cancelar</button><button onClick={()=>void confirmarAdicao()} disabled={ocupado} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white"><Check size={14} className="mr-1 inline"/>Adicionar</button></div></div></div>}
  </main>
}
