'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Pencil, Plus, ShieldAlert, Trash2, Truck } from 'lucide-react'
import Link from 'next/link'
import { usuarioAtual } from '@/lib/auth'
import { listarFornecedores, criarFornecedor, atualizarFornecedor, alternarAtivoFornecedor, excluirFornecedor } from '@/lib/fornecedores'
import { Fornecedor } from '@/lib/tipos'
import BuscaAtlasInput from '@/components/system/BuscaAtlasInput'
import { correspondeBuscaAtlas } from '@/lib/buscaAtlas'

type FormFornecedor={nome:string;cnpj_cpf:string;contato:string;telefone:string;email:string;endereco:string;cidade:string;observacoes:string;pedido_minimo:string;prazo_entrega_dias:string}
const vazio:FormFornecedor={nome:'',cnpj_cpf:'',contato:'',telefone:'',email:'',endereco:'',cidade:'',observacoes:'',pedido_minimo:'',prazo_entrega_dias:''}

export default function Fornecedores(){
 const[carregando,setCarregando]=useState(true),[euSouMaster,setEuSouMaster]=useState<boolean|null>(null),[fornecedores,setFornecedores]=useState<Fornecedor[]>([]),[busca,setBusca]=useState(''),[novoAberto,setNovoAberto]=useState(false),[form,setForm]=useState<FormFornecedor>(vazio),[editandoId,setEditandoId]=useState<string|null>(null),[editForm,setEditForm]=useState<Record<string,FormFornecedor>>({}),[salvando,setSalvando]=useState(false),[salvandoEdicaoId,setSalvandoEdicaoId]=useState<string|null>(null),[erro,setErro]=useState(''),[sucesso,setSucesso]=useState('')
 useEffect(()=>{carregar()},[])
 async function carregar(){setCarregando(true);const me=await usuarioAtual();setEuSouMaster(me?.role==='master');if(me?.role==='master')setFornecedores(await listarFornecedores());setCarregando(false)}
 const filtrados=useMemo(()=>!busca.trim()?fornecedores:fornecedores.filter(f=>correspondeBuscaAtlas(busca,f.nome,f.cnpj_cpf,f.contato,f.telefone,f.email,f.endereco,f.cidade,f.observacoes,f.ativo?'ativo':'inativo')),[fornecedores,busca])
 function campo(c:keyof FormFornecedor,v:string){setForm(p=>({...p,[c]:v}))}
 function iniciarEdicao(f:Fornecedor){setEditandoId(f.id);setEditForm(p=>({...p,[f.id]:{nome:f.nome,cnpj_cpf:f.cnpj_cpf||'',contato:f.contato||'',telefone:f.telefone||'',email:f.email||'',endereco:f.endereco||'',cidade:f.cidade||'',observacoes:f.observacoes||'',pedido_minimo:f.pedido_minimo!=null?String(f.pedido_minimo):'',prazo_entrega_dias:f.prazo_entrega_dias!=null?String(f.prazo_entrega_dias):''}}))}
 function campoEd(id:string,c:keyof FormFornecedor,v:string){setEditForm(p=>({...p,[id]:{...p[id],[c]:v}}))}
 async function cadastrar(e:React.FormEvent){e.preventDefault();setErro('');setSucesso('');if(!form.nome.trim())return setErro('Preencha o nome do fornecedor.');setSalvando(true);const me=await usuarioAtual();const{error}=await criarFornecedor({nome:form.nome.trim(),cnpj_cpf:form.cnpj_cpf.trim()||null,contato:form.contato.trim()||null,telefone:form.telefone.trim()||null,email:form.email.trim()||null,endereco:form.endereco.trim()||null,cidade:form.cidade.trim()||null,observacoes:form.observacoes.trim()||null,pedido_minimo:form.pedido_minimo?Number(form.pedido_minimo):null,prazo_entrega_dias:form.prazo_entrega_dias?Number(form.prazo_entrega_dias):null,criado_por_id:me?.id||null,criado_por_nome:me?.nome||null});setSalvando(false);if(error)return setErro('Erro ao cadastrar fornecedor.');setSucesso(`Fornecedor ${form.nome} cadastrado com sucesso.`);setForm(vazio);setNovoAberto(false);setFornecedores(await listarFornecedores())}
 async function salvarEd(id:string){const d=editForm[id];if(!d?.nome.trim())return;setSalvandoEdicaoId(id);await atualizarFornecedor(id,{nome:d.nome.trim(),cnpj_cpf:d.cnpj_cpf.trim()||null,contato:d.contato.trim()||null,telefone:d.telefone.trim()||null,email:d.email.trim()||null,endereco:d.endereco.trim()||null,cidade:d.cidade.trim()||null,observacoes:d.observacoes.trim()||null,pedido_minimo:d.pedido_minimo?Number(d.pedido_minimo):null,prazo_entrega_dias:d.prazo_entrega_dias?Number(d.prazo_entrega_dias):null});setFornecedores(await listarFornecedores());setSalvandoEdicaoId(null);setEditandoId(null)}
 async function alternar(f:Fornecedor){await alternarAtivoFornecedor(f.id,!f.ativo);setFornecedores(await listarFornecedores())}
 async function excluir(f:Fornecedor){if(!window.confirm(`Excluir o fornecedor "${f.nome}"?`))return;await excluirFornecedor(f.id);setFornecedores(await listarFornecedores())}
 if(carregando)return <div className="min-h-screen flex items-center justify-center text-slate-400">Carregando...</div>
 if(!euSouMaster)return <div className="min-h-screen flex flex-col items-center justify-center gap-3 text-center"><ShieldAlert size={40} className="text-slate-300"/><p className="text-slate-500">Só o usuário master pode acessar Fornecedores.</p><Link href="/cadastro" className="text-brand-navy text-sm">Voltar</Link></div>
 return <div className="min-h-screen bg-gradient-to-br from-slate-50 to-brand-navyLight"><header className="bg-white border-b"><div className="max-w-4xl mx-auto px-4 py-4 flex items-center gap-4"><Link href="/cadastro" className="p-2 rounded-lg hover:bg-slate-100"><ArrowLeft size={20}/></Link><Truck size={22} className="text-brand-navy"/><div className="flex-1"><h1 className="text-lg font-bold">Fornecedores</h1><p className="text-sm text-slate-500">Cadastro compartilhado de compras e estoque</p></div><button onClick={()=>setNovoAberto(v=>!v)} className="inline-flex items-center gap-2 rounded-xl bg-brand-navy px-3 py-2 text-sm font-semibold text-white"><Plus size={15}/>Novo</button></div></header>
 <main className="max-w-4xl mx-auto px-4 py-6 space-y-4">{erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{sucesso&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{sucesso}</div>}
 {novoAberto&&<form onSubmit={cadastrar} className="rounded-2xl border bg-white p-4 space-y-3"><h2 className="font-semibold">Novo fornecedor</h2><Form dados={form} onCampo={campo}/><div className="flex gap-2"><button disabled={salvando} className="rounded-xl bg-brand-navy px-4 py-2.5 text-sm font-semibold text-white">{salvando?'Salvando...':'Cadastrar'}</button><button type="button" onClick={()=>setNovoAberto(false)} className="rounded-xl border px-4 py-2.5 text-sm">Cancelar</button></div></form>}
 <section className="rounded-2xl border bg-white p-4"><div className="mb-3 flex items-center justify-between gap-3"><BuscaAtlasInput value={busca} onValueChange={setBusca} placeholder="Buscar nome, CNPJ/CPF, contato, telefone, e-mail, cidade, endereço ou observação..." containerClassName="flex-1" inputClassName="w-full rounded-xl border py-2.5 pr-3 text-sm"/><span className="text-xs text-slate-400">{filtrados.length} resultado(s)</span></div><div className="space-y-2">{filtrados.map(f=><div key={f.id} className="rounded-xl border p-3">{editandoId===f.id?<div className="space-y-3"><Form dados={editForm[f.id]||vazio} onCampo={(c,v)=>campoEd(f.id,c,v)}/><div className="flex gap-2"><button onClick={()=>salvarEd(f.id)} disabled={salvandoEdicaoId===f.id} className="rounded-lg bg-brand-navy px-3 py-2 text-xs font-semibold text-white">{salvandoEdicaoId===f.id?'Salvando...':'Salvar'}</button><button onClick={()=>setEditandoId(null)} className="rounded-lg border px-3 py-2 text-xs">Cancelar</button></div></div>:<><div className="flex items-start justify-between gap-3"><div><div className={`font-semibold ${f.ativo?'text-slate-800':'text-slate-400 line-through'}`}>{f.nome}</div><div className="mt-1 text-xs text-slate-500">{[f.cnpj_cpf,f.contato,f.telefone,f.email,f.cidade].filter(Boolean).join(' • ')||'Sem dados adicionais'}</div>{(f.pedido_minimo||f.prazo_entrega_dias)&&<div className="mt-1 text-xs text-slate-500">{f.pedido_minimo?`Pedido mínimo: R$ ${Number(f.pedido_minimo).toLocaleString('pt-BR',{minimumFractionDigits:2})}`:''}{f.pedido_minimo&&f.prazo_entrega_dias?' • ':''}{f.prazo_entrega_dias?`Prazo de entrega: ${f.prazo_entrega_dias} dia(s)`:''}</div>}{f.endereco&&<div className="text-xs text-slate-400">{f.endereco}</div>}{f.observacoes&&<div className="text-xs text-slate-400">{f.observacoes}</div>}</div><span className={`rounded-full px-2 py-1 text-xs ${f.ativo?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{f.ativo?'Ativo':'Inativo'}</span></div><div className="mt-3 flex gap-4 text-xs"><Link href={`/fornecedores/${f.id}`} className="inline-flex items-center gap-1 text-brand-navy font-semibold"><Truck size={12}/>Ver 360</Link><button onClick={()=>iniciarEdicao(f)} className="inline-flex items-center gap-1 text-brand-navy"><Pencil size={12}/>Editar</button><button onClick={()=>alternar(f)} className="text-slate-500">{f.ativo?'Desativar':'Ativar'}</button><button onClick={()=>excluir(f)} className="inline-flex items-center gap-1 text-red-500"><Trash2 size={12}/>Excluir</button></div></>}</div>)}{!filtrados.length&&<p className="py-8 text-center text-sm text-slate-400">Nenhum fornecedor encontrado.</p>}</div></section>
 </main></div>
}
function Form({dados,onCampo}:{dados:FormFornecedor;onCampo:(c:keyof FormFornecedor,v:string)=>void}){return <div className="grid gap-2 sm:grid-cols-2"><Campo label="Nome / razão social *" valor={dados.nome} onChange={v=>onCampo('nome',v)}/><Campo label="CNPJ / CPF" valor={dados.cnpj_cpf} onChange={v=>onCampo('cnpj_cpf',v)}/><Campo label="Contato" valor={dados.contato} onChange={v=>onCampo('contato',v)}/><Campo label="Telefone / WhatsApp" valor={dados.telefone} onChange={v=>onCampo('telefone',v)}/><Campo label="E-mail" valor={dados.email} onChange={v=>onCampo('email',v)}/><Campo label="Cidade" valor={dados.cidade} onChange={v=>onCampo('cidade',v)}/><Campo label="Pedido mínimo (R$)" valor={dados.pedido_minimo} onChange={v=>onCampo('pedido_minimo',v)}/><Campo label="Prazo de entrega (dias)" valor={dados.prazo_entrega_dias} onChange={v=>onCampo('prazo_entrega_dias',v)}/><label className="sm:col-span-2 text-xs text-slate-500">Endereço<input value={dados.endereco} onChange={e=>onCampo('endereco',e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 text-sm"/></label><label className="sm:col-span-2 text-xs text-slate-500">Observações<textarea value={dados.observacoes} onChange={e=>onCampo('observacoes',e.target.value)} rows={2} className="mt-1 w-full rounded-xl border p-2.5 text-sm"/></label></div>}
function Campo({label,valor,onChange}:{label:string;valor:string;onChange:(v:string)=>void}){return <label className="text-xs text-slate-500">{label}<input value={valor} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 text-sm"/></label>}
