'use client'

import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Loader2, Plus, Save, Search, Settings, Trash2 } from 'lucide-react'
import { tokenAtual } from '@/lib/auth'

type Produto = { id:string; codigo?:string|null; nome:string; descricao?:string|null; categoria?:string|null; grupo?:string|null; permite_venda_sem_estoque:boolean|null }
type Categoria = { valor:string; label:string; ordem:number }

export default function ConfiguracoesBalcao(){
 const [permitir,setPermitir]=useState(true),[grupos,setGrupos]=useState<string[]>([]),[categorias,setCategorias]=useState<Categoria[]>([]),[novoGrupo,setNovoGrupo]=useState(''),[novaCategoria,setNovaCategoria]=useState('')
 const [q,setQ]=useState(''),[produtos,setProdutos]=useState<Produto[]>([]),[carregando,setCarregando]=useState(true),[buscando,setBuscando]=useState(false),[salvando,setSalvando]=useState(''),[erro,setErro]=useState(''),[ok,setOk]=useState('')
 const abortRef=useRef<AbortController|null>(null)
 async function api(url:string,init?:RequestInit){const token=await tokenAtual();if(!token)throw new Error('Sessão expirada.');return fetch(url,{...init,headers:{...(init?.headers||{}),Authorization:`Bearer ${token}`,'Content-Type':'application/json'},cache:'no-store'})}
 async function carregar(){setCarregando(true);setErro('');try{const r=await api('/api/balcao/configuracoes');const j=await r.json();if(!r.ok)throw new Error(j.error);setPermitir(Boolean(j.permitirVendaSemEstoque));setGrupos(j.grupos||[]);setCategorias(j.categorias||[])}catch(e){setErro(e instanceof Error?e.message:'Erro ao carregar configurações.')}finally{setCarregando(false)}}
 useEffect(()=>{carregar()},[])
 useEffect(()=>{const termo=q.trim();abortRef.current?.abort();if(termo.length<2){setProdutos([]);setBuscando(false);return}const c=new AbortController();abortRef.current=c;setBuscando(true);const h=setTimeout(async()=>{try{const token=await tokenAtual();if(!token)return;const r=await fetch(`/api/balcao/configuracoes?q=${encodeURIComponent(termo)}`,{headers:{Authorization:`Bearer ${token}`},signal:c.signal,cache:'no-store'});const j=await r.json();if(r.ok)setProdutos(j.produtos||[])}catch(e){if((e as {name?:string})?.name!=='AbortError')setErro('Não foi possível pesquisar produtos.')}finally{if(!c.signal.aborted)setBuscando(false)}},100);return()=>{clearTimeout(h);c.abort()}},[q])
 async function postar(body:any,id:string){setSalvando(id);setErro('');setOk('');try{const r=await api('/api/balcao/configuracoes',{method:'POST',body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);setOk('Configuração salva.');return j}catch(e){setErro(e instanceof Error?e.message:'Não foi possível salvar.');return null}finally{setSalvando('')}}
 async function toggleGlobal(){const novo=!permitir;const j=await postar({acao:'estoque-global',permitir:novo},'global');if(j)setPermitir(novo)}
 async function adicionarGrupo(){const nome=novoGrupo.trim();if(!nome)return;const j=await postar({acao:'adicionar-grupo',nome},'grupo');if(j){setGrupos(j.grupos||[]);setNovoGrupo('')}}
 async function removerGrupo(nome:string){const j=await postar({acao:'remover-grupo',nome},`grupo-${nome}`);if(j)setGrupos(j.grupos||[])}
 async function adicionarCategoria(){const nome=novaCategoria.trim();if(!nome)return;const j=await postar({acao:'adicionar-categoria',nome},'categoria');if(j){setCategorias(j.categorias||[]);setNovaCategoria('')}}
 async function mudarProduto(p:Produto,valor:boolean|null){const j=await postar({acao:'produto-estoque',produtoId:p.id,valor},p.id);if(j)setProdutos(lista=>lista.map(x=>x.id===p.id?{...x,permite_venda_sem_estoque:valor}:x))}
 if(carregando)return <div className="min-h-screen flex items-center justify-center text-slate-400">Carregando...</div>
 return <main className="min-h-screen bg-slate-50 p-4"><div className="mx-auto max-w-5xl space-y-4">
  <header className="flex items-center gap-3"><Link href="/balcao" className="rounded-lg border bg-white p-2"><ArrowLeft size={18}/></Link><Settings size={21} className="text-emerald-700"/><div><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-slate-400">Venda Balcão</p><h1 className="text-xl font-bold">Configurações</h1><p className="text-xs text-slate-500">Estoque, categorias e grupos do catálogo compartilhado.</p></div></header>
  {erro&&<div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{erro}</div>}{ok&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-800">{ok}</div>}
  <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold text-slate-800">Venda sem estoque</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-500">Quando liberada, produto com saldo zero pode ser vendido e fica como <strong>Aguardando estoque</strong>. O Atlas não cria estoque negativo nem registra uma saída que não aconteceu.</p></div><button onClick={toggleGlobal} disabled={salvando==='global'} className={`rounded-full px-4 py-2 text-xs font-semibold ${permitir?'bg-emerald-600 text-white':'bg-slate-200 text-slate-700'}`}>{salvando==='global'?'Salvando...':permitir?'Liberada no geral':'Bloqueada no geral'}</button></div></section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold text-slate-800">Filtros do catálogo</h2><p className="mt-1 text-xs text-slate-500">Categoria é o primeiro nível (Acessório, Perfil, Vidro...). Grupo/filtro é o segundo nível (Suprema, Gold, 30, 42, Tela Mosquiteira, Espelho, Box, Cobertura, Policarbonato, ACM...).</p><div className="mt-4 grid gap-5 lg:grid-cols-2"><div><label className="text-xs font-semibold text-slate-600">Novo grupo / filtro</label><div className="mt-1 flex gap-2"><input value={novoGrupo} onChange={e=>setNovoGrupo(e.target.value)} placeholder="Ex.: Tela Mosquiteira" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm"/><button onClick={adicionarGrupo} disabled={salvando==='grupo'} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={14}/>Criar</button></div><div className="mt-3 flex flex-wrap gap-2">{grupos.map(g=><span key={g} className="inline-flex items-center gap-1 rounded-full border bg-slate-50 px-2.5 py-1 text-xs">{g}<button title="Remover filtro da lista" onClick={()=>removerGrupo(g)} className="text-slate-400 hover:text-red-500"><Trash2 size={11}/></button></span>)}{!grupos.length&&<span className="text-xs text-slate-400">Nenhum grupo personalizado.</span>}</div></div><div><label className="text-xs font-semibold text-slate-600">Nova categoria principal</label><div className="mt-1 flex gap-2"><input value={novaCategoria} onChange={e=>setNovaCategoria(e.target.value)} placeholder="Ex.: Policarbonato" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm"/><button onClick={adicionarCategoria} disabled={salvando==='categoria'} className="inline-flex items-center gap-1 rounded-lg border border-emerald-600 px-3 py-2 text-xs font-semibold text-emerald-700"><Plus size={14}/>Criar</button></div><div className="mt-3 flex flex-wrap gap-2">{categorias.map(c=><span key={c.valor} className="rounded-full bg-sky-50 px-2.5 py-1 text-xs text-sky-800">{c.label}</span>)}{!categorias.length&&<span className="text-xs text-slate-400">As categorias padrão continuam disponíveis.</span>}</div></div></div></section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold text-slate-800">Regra por produto</h2><p className="mt-1 text-xs text-slate-500">Um produto pode herdar a regra geral, ser sempre liberado ou ser sempre bloqueado.</p><div className="relative mt-3"><Search size={16} className="absolute left-3 top-2.5 text-slate-400"/><input value={q} onInput={e=>setQ(e.currentTarget.value)} placeholder="Buscar código, produto, descrição, categoria ou grupo..." className="w-full rounded-lg border py-2 pl-9 pr-10 text-sm"/>{buscando&&<Loader2 size={15} className="absolute right-3 top-2.5 animate-spin text-slate-400"/>}</div><div className="mt-3 space-y-2">{produtos.map(p=><div key={p.id} className="flex flex-wrap items-center gap-3 rounded-xl border p-3"><div className="min-w-[220px] flex-1"><strong className="text-sm text-slate-800">{p.codigo?`${p.codigo} — `:''}{p.nome}</strong><div className="text-[11px] text-slate-400">{[p.categoria,p.grupo].filter(Boolean).join(' • ')||'Sem grupo definido'}</div></div><select value={p.permite_venda_sem_estoque===null?'herdar':p.permite_venda_sem_estoque?'sim':'nao'} onChange={e=>mudarProduto(p,e.target.value==='herdar'?null:e.target.value==='sim')} disabled={salvando===p.id} className="rounded-lg border px-3 py-2 text-xs"><option value="herdar">Herdar regra geral</option><option value="sim">Permitir sem estoque</option><option value="nao">Bloquear sem estoque</option></select></div>)}{q.trim().length>=2&&!buscando&&!produtos.length&&<div className="py-5 text-center text-xs text-slate-400">Nenhum produto encontrado.</div>}</div></section>
 </div></main>
}
