'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Building2, CalendarDays, CheckCircle2, ExternalLink, MapPin, MessageCircle, Pencil, Phone, Plus, Save, UserRound, Users, X } from 'lucide-react'
import { usuarioAtual } from '@/lib/auth'
import { adicionarContato, atualizarProspeccao, buscarClientesSemelhantes, buscarProspeccao, converterProspeccao, listarEquipeProspeccao, moverProspeccao, PAPEIS_CONTATO, registrarInteracao, STATUS_PROSPECCAO, type ContatoProspeccao, type InteracaoProspeccao, type PapelContatoProspeccao, type Prospeccao, type StatusProspeccao, type TipoInteracaoProspeccao } from '@/lib/prospeccao'
import type { Cliente, Usuario } from '@/lib/tipos'

function dataHora(valor?:string|null){return valor?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(valor)):'—'}
const TIPOS:{id:TipoInteracaoProspeccao;label:string}[]=[{id:'ligacao',label:'Ligação'},{id:'whatsapp',label:'WhatsApp'},{id:'visita',label:'Visita'},{id:'nota',label:'Anotação'},{id:'outro',label:'Outro'}]

export default function ProspeccaoDetalhePage(){
  const id=String(useParams().id);const router=useRouter()
  const [usuario,setUsuario]=useState<Usuario|null>(null)
  const [p,setP]=useState<Prospeccao|null>(null);const [contatos,setContatos]=useState<ContatoProspeccao[]>([]);const [interacoes,setInteracoes]=useState<InteracaoProspeccao[]>([])
  const [carregando,setCarregando]=useState(true);const [erro,setErro]=useState('');const [salvando,setSalvando]=useState(false)
  const [tipo,setTipo]=useState<TipoInteracaoProspeccao>('ligacao');const [descricao,setDescricao]=useState('');const [proximaAcao,setProximaAcao]=useState('');const [proximaEm,setProximaEm]=useState('');const [statusNovo,setStatusNovo]=useState<StatusProspeccao|''>('')
  const [modalContato,setModalContato]=useState(false);const [papel,setPapel]=useState<PapelContatoProspeccao>('pedreiro');const [contatoNome,setContatoNome]=useState('');const [contatoTelefone,setContatoTelefone]=useState('');const [contatoEmpresa,setContatoEmpresa]=useState('')
  const [editando,setEditando]=useState(false);const [form,setForm]=useState<Record<string,string>>({});const [equipe,setEquipe]=useState<Pick<Usuario,'id'|'nome'>[]>([])
  const [modalConverter,setModalConverter]=useState(false);const [semelhantes,setSemelhantes]=useState<Cliente[]>([]);const [clienteEscolhido,setClienteEscolhido]=useState('');const [criarObra,setCriarObra]=useState(true)

  async function carregar(){setCarregando(true);const me=await usuarioAtual();setUsuario(me);const d=await buscarProspeccao(id);setP(d.prospeccao);setContatos(d.contatos);setInteracoes(d.interacoes);if(me?.role==='master')setEquipe(await listarEquipeProspeccao());setCarregando(false)}
  useEffect(()=>{void carregar()},[id])

  async function mudarStatus(valor:StatusProspeccao){if(!p)return;const anterior=p;setP({...p,status:valor});const r=await moverProspeccao(anterior,valor);if(!r.ok){setErro(r.error||'Erro ao mover.');await carregar()}else await carregar()}
  async function salvarInteracao(){if(!p)return;setErro('');setSalvando(true);const r=await registrarInteracao(p,{tipo,descricao,proxima_acao:proximaAcao,proxima_acao_em:proximaEm?new Date(proximaEm).toISOString():undefined,status_novo:statusNovo||undefined});setSalvando(false);if(!r.ok){setErro(r.error||'Não foi possível registrar.');return}setDescricao('');setProximaAcao('');setProximaEm('');setStatusNovo('');await carregar()}
  async function salvarContato(){if(!contatoNome.trim())return;setSalvando(true);const r=await adicionarContato(id,{papel,nome:contatoNome,telefone:contatoTelefone,empresa:contatoEmpresa,observacoes:null});setSalvando(false);if(!r.ok){setErro(r.error||'Erro ao salvar contato.');return}setModalContato(false);setContatoNome('');setContatoTelefone('');setContatoEmpresa('');await carregar()}
  function abrirEdicao(){if(!p)return;setForm({nome_cliente:p.nome_cliente,telefone:p.telefone||'',nome_obra:p.nome_obra||'',cidade:p.cidade||'',bairro:p.bairro||'',endereco:p.endereco||'',complemento:p.complemento||'',fase_obra:p.fase_obra||'',observacoes:p.observacoes||'',temperatura:p.temperatura,responsavel_id:p.responsavel_id,responsavel_nome:p.responsavel_nome});setEditando(true)}
  async function salvarEdicao(){if(!p||!form.nome_cliente?.trim())return;setSalvando(true);const patch:any={...form};if(form.responsavel_id!==p.responsavel_id){patch.responsavel_nome=equipe.find(u=>u.id===form.responsavel_id)?.nome||form.responsavel_nome}const r=await atualizarProspeccao(id,patch);setSalvando(false);if(!r.ok){setErro(r.error||'Erro ao atualizar.');return}setEditando(false);await carregar()}
  async function abrirConversao(){if(!p)return;setSemelhantes(await buscarClientesSemelhantes(p.nome_cliente,p.telefone));setClienteEscolhido('');setModalConverter(true)}
  async function converter(){setSalvando(true);const r=await converterProspeccao(id,clienteEscolhido||null,criarObra);setSalvando(false);if(!r.ok){setErro(r.error||'Não foi possível converter.');return}setModalConverter(false);router.push(`/clientes/${r.clienteId}`)}

  if(carregando)return <div className="min-h-screen grid place-items-center text-slate-400">Carregando prospecção...</div>
  if(!p)return <div className="min-h-screen grid place-items-center p-6 text-center"><div><p className="text-slate-500">Prospecção não encontrada ou sem acesso.</p><Link href="/prospeccao" className="mt-3 inline-block text-blue-600">Voltar</Link></div></div>
  const mapa=p.latitude!=null&&p.longitude!=null?`https://www.google.com/maps?q=${p.latitude},${p.longitude}`:null
  const status=STATUS_PROSPECCAO.find(s=>s.id===p.status)

  return <div className="min-h-screen bg-slate-50">
    <header className="border-b bg-white"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 px-4 py-4"><div className="flex items-center gap-3"><Link href="/prospeccao" className="rounded-xl border p-2"><ArrowLeft size={18}/></Link><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-600">Prospecção</p><h1 className="text-xl font-bold">{p.nome_cliente}</h1><p className="text-xs text-slate-500">Responsável: {p.responsavel_nome}</p></div></div><div className="flex flex-wrap gap-2"><button onClick={abrirEdicao} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold"><Pencil size={15}/>Editar cadastro</button>{p.status!=='convertido'&&<button onClick={()=>void abrirConversao()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-3 py-2 text-sm font-bold text-white"><CheckCircle2 size={16}/>Converter em cliente</button>}</div></div></header>
    <main className="mx-auto max-w-6xl space-y-4 px-4 py-5 pb-28">
      {erro&&<p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{erro}</p>}
      <section className="grid gap-4 lg:grid-cols-[1fr_320px]">
        <article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-bold ${status?.cor||'bg-slate-400'} text-white`}>{status?.label}</span>{p.nome_obra&&<h2 className="mt-3 text-lg font-bold">{p.nome_obra}</h2>}</div><select value={p.status} onChange={e=>void mudarStatus(e.target.value as StatusProspeccao)} className="rounded-xl border px-3 py-2 text-sm">{STATUS_PROSPECCAO.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><p className="flex items-center gap-2"><Phone size={15} className="text-slate-400"/>{p.telefone||'Telefone não informado'}</p><p className="flex items-center gap-2"><MapPin size={15} className="text-slate-400"/>{[p.endereco,p.bairro,p.cidade].filter(Boolean).join(' · ')||'Endereço não informado'}</p><p><b>Fase da obra:</b> {p.fase_obra||'Não informada'}</p><p><b>Temperatura:</b> {p.temperatura}</p><p className="sm:col-span-2"><b>Interesses:</b> {p.interesses?.length?p.interesses.join(', '):'Ainda não identificados'}</p>{p.observacoes&&<p className="rounded-xl bg-slate-50 p-3 sm:col-span-2">{p.observacoes}</p>}</div>{mapa&&<a href={mapa} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-50 px-3 py-2 text-sm font-bold text-blue-700"><MapPin size={15}/>Abrir localização no mapa<ExternalLink size={13}/></a>}</article>
        <aside className={`rounded-2xl border p-5 shadow-sm ${p.proxima_acao_em&&new Date(p.proxima_acao_em).getTime()<Date.now()?'border-red-200 bg-red-50':'bg-white'}`}><div className="flex items-center gap-2"><CalendarDays size={18} className="text-blue-600"/><h2 className="font-bold">Próxima ação</h2></div><p className="mt-4 text-sm font-semibold">{p.proxima_acao||'Nenhuma ação definida'}</p><p className="mt-1 text-xs text-slate-500">{dataHora(p.proxima_acao_em)}</p>{p.proxima_acao_em&&new Date(p.proxima_acao_em).getTime()<Date.now()&&<span className="mt-3 inline-block rounded-full bg-red-600 px-2 py-1 text-[10px] font-bold text-white">ATRASADA</span>}</aside>
      </section>

      <section className="grid gap-4 lg:grid-cols-[340px_1fr]">
        <article className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><Users size={17} className="text-violet-600"/><h2 className="font-bold">Pessoas da obra</h2></div><button onClick={()=>setModalContato(true)} className="rounded-lg border p-2 text-blue-600"><Plus size={15}/></button></div><div className="space-y-2">{contatos.map(c=><div key={c.id} className="rounded-xl border bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{PAPEIS_CONTATO.find(x=>x.id===c.papel)?.label}</p><p className="mt-1 text-sm font-bold">{c.nome}</p>{c.telefone&&<a href={`tel:${c.telefone}`} className="mt-1 block text-xs text-blue-600">{c.telefone}</a>}{c.empresa&&<p className="text-xs text-slate-500">{c.empresa}</p>}</div>)}{contatos.length===0&&<p className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-400">Nenhum contato registrado.</p>}</div></article>
        <div className="space-y-4"><article className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><MessageCircle size={17} className="text-blue-600"/><h2 className="font-bold">Registrar contato</h2></div><div className="mt-4 grid gap-3"><select value={tipo} onChange={e=>setTipo(e.target.value as TipoInteracaoProspeccao)} className="rounded-xl border px-3 py-2.5 text-sm">{TIPOS.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select><textarea value={descricao} onChange={e=>setDescricao(e.target.value)} rows={4} placeholder="O que o cliente falou? O que ficou combinado?" className="rounded-xl border px-3 py-3 text-sm"/><div className="grid gap-3 sm:grid-cols-3"><input value={proximaAcao} onChange={e=>setProximaAcao(e.target.value)} placeholder="Próxima ação" className="rounded-xl border px-3 py-2.5 text-sm"/><input type="datetime-local" value={proximaEm} onChange={e=>setProximaEm(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"/><select value={statusNovo} onChange={e=>setStatusNovo(e.target.value as StatusProspeccao|'')} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">Manter etapa atual</option>{STATUS_PROSPECCAO.filter(s=>s.id!==p.status).map(s=><option key={s.id} value={s.id}>Mover para: {s.label}</option>)}</select></div><button onClick={()=>void salvarInteracao()} disabled={salvando||!descricao.trim()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white disabled:opacity-50"><Save size={16}/>{salvando?'Salvando...':'Salvar no diário'}</button></div></article>
        <article className="overflow-hidden rounded-2xl border bg-white"><div className="border-b px-5 py-4"><h2 className="font-bold">Diário da prospecção</h2><p className="text-xs text-slate-500">Histórico cronológico de visitas, ligações e mudanças.</p></div><div className="divide-y">{interacoes.map(i=><div key={i.id} className="flex gap-3 px-5 py-4"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-blue-500"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm capitalize">{i.tipo}</strong><span className="text-[11px] text-slate-400">{dataHora(i.created_at)}</span></div><p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{i.descricao}</p><p className="mt-2 text-[11px] text-slate-400">{i.usuario_nome}</p>{i.proxima_acao&&<p className="mt-2 rounded-lg bg-blue-50 px-3 py-2 text-xs text-blue-700"><b>Próxima ação:</b> {i.proxima_acao} · {dataHora(i.proxima_acao_em)}</p>}</div></div>)}{interacoes.length===0&&<p className="p-8 text-center text-sm text-slate-400">Nenhum registro no diário.</p>}</div></article></div>
      </section>
    </main>

    {modalContato&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5"><div className="mb-4 flex justify-between"><h2 className="font-bold">Adicionar pessoa da obra</h2><button onClick={()=>setModalContato(false)}><X size={18}/></button></div><div className="space-y-3"><select value={papel} onChange={e=>setPapel(e.target.value as PapelContatoProspeccao)} className="w-full rounded-xl border px-3 py-2.5 text-sm">{PAPEIS_CONTATO.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input value={contatoNome} onChange={e=>setContatoNome(e.target.value)} placeholder="Nome" className="w-full rounded-xl border px-3 py-2.5"/><input value={contatoTelefone} onChange={e=>setContatoTelefone(e.target.value)} placeholder="Telefone" className="w-full rounded-xl border px-3 py-2.5"/><input value={contatoEmpresa} onChange={e=>setContatoEmpresa(e.target.value)} placeholder="Empresa / escritório" className="w-full rounded-xl border px-3 py-2.5"/><button onClick={()=>void salvarContato()} disabled={salvando||!contatoNome.trim()} className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white">Salvar contato</button></div></div></div>}
    {editando&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/50 p-4"><div className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5"><div className="mb-4 flex justify-between"><div><h2 className="font-bold">Completar pré-cadastro</h2><p className="text-xs text-slate-500">Atualize os dados descobertos depois da primeira visita.</p></div><button onClick={()=>setEditando(false)}><X size={18}/></button></div><div className="grid gap-3 sm:grid-cols-2"><input value={form.nome_cliente||''} onChange={e=>setForm({...form,nome_cliente:e.target.value})} placeholder="Nome do cliente" className="rounded-xl border px-3 py-2.5 sm:col-span-2"/><input value={form.telefone||''} onChange={e=>setForm({...form,telefone:e.target.value})} placeholder="Telefone" className="rounded-xl border px-3 py-2.5"/><input value={form.nome_obra||''} onChange={e=>setForm({...form,nome_obra:e.target.value})} placeholder="Nome da obra" className="rounded-xl border px-3 py-2.5"/><input value={form.cidade||''} onChange={e=>setForm({...form,cidade:e.target.value})} placeholder="Cidade" className="rounded-xl border px-3 py-2.5"/><input value={form.bairro||''} onChange={e=>setForm({...form,bairro:e.target.value})} placeholder="Bairro" className="rounded-xl border px-3 py-2.5"/><input value={form.endereco||''} onChange={e=>setForm({...form,endereco:e.target.value})} placeholder="Endereço" className="rounded-xl border px-3 py-2.5 sm:col-span-2"/><input value={form.fase_obra||''} onChange={e=>setForm({...form,fase_obra:e.target.value})} placeholder="Fase da obra" className="rounded-xl border px-3 py-2.5"/><select value={form.temperatura||'frio'} onChange={e=>setForm({...form,temperatura:e.target.value})} className="rounded-xl border px-3 py-2.5"><option value="frio">Frio</option><option value="morno">Morno</option><option value="quente">Quente</option></select>{usuario?.role==='master'&&<select value={form.responsavel_id||''} onChange={e=>setForm({...form,responsavel_id:e.target.value})} className="rounded-xl border px-3 py-2.5 sm:col-span-2">{equipe.map(u=><option key={u.id} value={u.id}>Responsável: {u.nome}</option>)}</select>}<textarea value={form.observacoes||''} onChange={e=>setForm({...form,observacoes:e.target.value})} rows={4} placeholder="Observações" className="rounded-xl border px-3 py-2.5 sm:col-span-2"/></div><button onClick={()=>void salvarEdicao()} disabled={salvando} className="mt-4 w-full rounded-xl bg-slate-900 py-3 font-bold text-white">Salvar alterações</button></div></div>}
    {modalConverter&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5"><div className="mb-4 flex justify-between"><div><h2 className="font-bold">Converter em Cliente 360</h2><p className="text-xs text-slate-500">Confira se este cliente já existe antes de criar outro.</p></div><button onClick={()=>setModalConverter(false)}><X size={18}/></button></div>{semelhantes.length>0?<div className="space-y-2"><p className="text-xs font-bold text-amber-700">Possíveis clientes já cadastrados</p>{semelhantes.map(c=><label key={c.id} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 ${clienteEscolhido===c.id?'border-blue-500 bg-blue-50':''}`}><input type="radio" name="cliente" checked={clienteEscolhido===c.id} onChange={()=>setClienteEscolhido(c.id)}/><span><strong className="block text-sm">{c.nome}</strong><small className="text-slate-500">{c.whatsapp||c.telefone||'Sem telefone'} · {c.cidade||'Sem cidade'}</small></span></label>)}<label className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 ${clienteEscolhido===''?'border-blue-500 bg-blue-50':''}`}><input type="radio" checked={clienteEscolhido===''} onChange={()=>setClienteEscolhido('')}/><span className="text-sm font-semibold">Criar um novo Cliente 360</span></label></div>:<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Nenhum cliente semelhante foi encontrado. Um novo cadastro será criado.</p>}<label className="mt-4 flex items-start gap-3 rounded-xl border p-3"><input type="checkbox" checked={criarObra} onChange={e=>setCriarObra(e.target.checked)} className="mt-1"/><span><strong className="block text-sm">Criar também a obra</strong><small className="text-slate-500">Endereço, cidade e histórico serão vinculados ao Cliente 360.</small></span></label><button onClick={()=>void converter()} disabled={salvando} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 py-3 font-bold text-white"><Building2 size={17}/>{salvando?'Convertendo...':'Confirmar conversão'}</button></div></div>}
  </div>
}
