'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { carregarFichaProducao, type FichaProducao, type MaterialFichaProducao } from '@/lib/fichaProducao'

const texto = (v: any, fallback = '—') => v == null || String(v).trim() === '' ? fallback : String(v)
const dataBR = (v: any) => v ? new Date(v).toLocaleDateString('pt-BR') : '—'
const qtd = (m: any) => `${Number(m.quantidade || 0).toLocaleString('pt-BR')} ${texto(m.unidade, '')}`.trim()
function categoria(m: any) { const c = String(m.categoria || '').toLowerCase(); if (c.includes('perfil')) return 'Perfis'; if (c.includes('acess')) return 'Acessórios'; if (c.includes('vidro')) return 'Vidros'; return 'Outros' }
function Materiais({ titulo, lista }: { titulo: string; lista: MaterialFichaProducao[] }) {
  if (!lista.length) return null
  return <section className="sec"><h2>{titulo}</h2><table><thead><tr><th>Imagem</th><th>Código / descrição</th><th>Qtd.</th><th>Corte / registro técnico</th></tr></thead><tbody>{lista.map(m => <tr key={m.id}><td className="img">{m.imagem_url ? <img src={m.imagem_url} alt="Representação cadastrada" /> : '—'}</td><td><b>{texto((m as any).codigo, '')}</b>{(m as any).codigo ? ' — ' : ''}{texto((m as any).descricao || (m as any).nome)}{(m as any).posicao ? <div>Posição: {texto((m as any).posicao)}</div> : null}</td><td>{qtd(m)}</td><td>{m.cortes.length ? m.cortes.map(c => <div key={c.id}>{c.comprimento_mm} mm{c.perda_corte_mm ? ` • perda registrada ${c.perda_corte_mm} mm` : ''}{c.sobra_exclusiva_item && c.barra_sobra_final_mm != null ? ` • sobra exclusiva ${c.barra_sobra_final_mm} mm` : ''}</div>) : <span>Sem corte técnico registrado</span>}</td></tr>)}</tbody></table></section>
}
export default function FichaProducaoPage() {
  const params = useParams<{ id: string }>(); const [ficha, setFicha] = useState<FichaProducao | null>(null); const [erro, setErro] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { let ativo = true; carregarFichaProducao(String(params.id)).then(x => { if (!ativo) return; if (!x) setErro('Ordem de Produção não encontrada.'); else setFicha(x) }).catch(e => setErro(e?.message || 'Não foi possível carregar a ficha.')).finally(() => ativo && setLoading(false)); return () => { ativo = false } }, [params.id])
  if (loading) return <main className="estado">Carregando ficha de produção…</main>
  if (erro || !ficha) return <main className="estado">{erro || 'Ficha não encontrada.'}</main>
  const o:any=ficha.orcamento||{}; const obra:any=Array.isArray(o.obras)?o.obras[0]:o.obras; const cliente:any=Array.isArray(o.clientes)?o.clientes[0]:o.clientes; const item:any=ficha.item||{}
  const grupos = ['Perfis','Acessórios','Vidros','Outros'].map(nome => ({ nome, lista:ficha.materiais.filter(m => categoria(m) === nome) }))
  const configuracao = [['Ambiente',item.ambiente],['Linha',item.linha_nome||item.linha],['Cor',item.cor_nome||item.cor],['Largura',item.largura_mm||item.largura],['Altura',item.altura_mm||item.altura],['Quantidade',item.quantidade],['Folhas',item.folhas||item.numero_folhas],['Abertura',item.abertura||item.tipo_abertura]].filter(([,v]) => v != null && String(v).trim() !== '')
  return <><main className="folha"><header><div><h1>Lista Completa de Produção A4 por Tipologia</h1><p>Documento técnico rastreável — Atlas One</p></div><button className="no-print" onClick={() => window.print()}>Imprimir / Salvar PDF</button></header>
    <div className={`selo ${ficha.situacao}`}>{ficha.situacao === 'liberado' ? 'LIBERADO PARA PRODUÇÃO' : 'PRÉVIA — NÃO LIBERAR PRODUÇÃO'}</div>
    {ficha.motivosBloqueio.length ? <section className="alerta"><b>Bloqueios técnicos:</b><ul>{ficha.motivosBloqueio.map((m,i)=><li key={i}>{m}</li>)}</ul></section> : null}
    <section className="grade"><div><b>Cliente</b><span>{texto(cliente?.nome || o.cliente_nome)}</span></div><div><b>Obra</b><span>{texto(obra?.nome)}</span></div><div><b>Cidade</b><span>{texto(obra?.cidade || o.obra_cidade || o.cidade)}</span></div><div><b>Orçamento</b><span>{texto(o.numero || o.id)}</span></div><div><b>Revisão</b><span>{texto(ficha.revisoes[0]?.versao, 'Sem revisão registrada')}</span></div><div><b>Data</b><span>{dataBR(ficha.medicaoFinal?.aprovado_em || ficha.ordem.created_at)}</span></div><div><b>Responsável</b><span>{texto(ficha.medicaoFinal?.responsavel_nome || ficha.medicaoFinal?.aprovado_por_nome)}</span></div><div><b>Tipologia</b><span>{texto(ficha.tipologia?.label || item.tipologia_nome || item.descricao)}</span></div></section>
    <section className="sec"><h2>Tipologia e configuração cadastrada</h2><div className="tipologia">{ficha.tipologia?.foto_url ? <div><img className="desenho" src={ficha.tipologia.foto_url} alt="Representação cadastrada da tipologia"/><small>Representação cadastrada no Atlas</small></div> : <div className="sem">Sem representação cadastrada — nenhum desenho foi inventado.</div>}<div className="config">{configuracao.length ? configuracao.map(([k,v])=><p key={String(k)}><b>{k}:</b> {texto(v)}</p>) : <p>Sem variáveis adicionais cadastradas.</p>}</div></div></section>
    {ficha.observacoesProducao.length ? <section className="notas"><h2>Observações de produção</h2>{ficha.observacoesProducao.map((x,i)=><p key={i}>{x}</p>)}</section> : null}
    {grupos.map(g => <Materiais key={g.nome} titulo={g.nome} lista={g.lista}/>)}
    <section className="sec checklist"><h2>Checklist de produção</h2><p>☐ Conferir cliente, obra, ambiente e tipologia</p><p>☐ Conferir Medição Final aprovada</p><p>☐ Conferir perfis e cortes registrados</p><p>☐ Conferir acessórios registrados</p><p>☐ Conferir vidros registrados</p><p>☐ Conferir observações técnicas antes de produzir</p></section>
    <section className="sec"><h2>Rastreabilidade</h2><p><b>Link interno:</b> {ficha.linkInternoPath}</p><p><b>Pacote técnico:</b> {texto(ficha.pacote?.id)}</p><p><b>Situação técnica:</b> {texto(ficha.situacaoTecnica?.situacao_tecnica)}</p>{ficha.revisoes.length ? <table><thead><tr><th>Versão</th><th>Tipo</th><th>Responsável</th><th>Data</th><th>Justificativa</th></tr></thead><tbody>{ficha.revisoes.map(r=><tr key={r.id}><td>{r.versao}</td><td>{r.tipo}</td><td>{texto(r.criado_por_nome)}</td><td>{dataBR(r.created_at)}</td><td>{texto(r.justificativa)}</td></tr>)}</tbody></table> : <p>Sem histórico de revisão registrado.</p>}<p className="qr">QR Code: pendente de implementação local segura. O link interno acima permanece disponível para rastreabilidade.</p></section>
  </main><style jsx global>{`*{box-sizing:border-box}body{background:#eef1f4;color:#111;font-family:Arial,sans-serif}.folha{width:210mm;min-height:297mm;margin:16px auto;background:white;padding:12mm;font-size:10.5pt}header{display:flex;justify-content:space-between;gap:16px;align-items:start;border-bottom:2px solid #111;padding-bottom:8px}h1{font-size:18pt;margin:0}h2{font-size:12pt;margin:0 0 8px}.selo{margin:10px 0;padding:10px;border:3px solid;text-align:center;font-weight:800;font-size:14pt}.selo.previa{border-style:double}.alerta,.notas{border:2px solid #111;padding:8px;margin:10px 0}.grade{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #333;margin:10px 0}.grade div{padding:6px;border:1px solid #bbb}.grade b,.grade span{display:block}.sec{margin:12px 0;break-inside:auto}.tipologia{display:grid;grid-template-columns:1fr 1fr;gap:12px}.desenho{max-width:100%;max-height:65mm;object-fit:contain;border:1px solid #ccc}.sem{min-height:35mm;border:1px dashed #888;padding:12px}.config p{margin:4px 0}table{width:100%;border-collapse:collapse;font-size:9.5pt}th,td{border:1px solid #777;padding:5px;text-align:left;vertical-align:top}th{background:#eee}.img{width:22mm;text-align:center}.img img{max-width:18mm;max-height:18mm;object-fit:contain}.checklist p{margin:5px 0}.qr{border:1px dashed #888;padding:6px}.no-print{padding:8px 12px}.estado{padding:30px}.sec table tr{break-inside:avoid}@page{size:A4;margin:10mm}@media print{body{background:white}.folha{width:auto;min-height:auto;margin:0;padding:0}.no-print{display:none}header{break-after:avoid}.selo,.alerta,.grade,.tipologia,.notas,.checklist{break-inside:avoid}}@media(max-width:800px){.folha{width:100%;margin:0;padding:16px}.grade{grid-template-columns:1fr 1fr}.tipologia{grid-template-columns:1fr}header{flex-direction:column}}`}</style></>
}
