'use client'

import { useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, MapPin, PackageSearch, RefreshCw } from 'lucide-react'
import { tokenAtual } from '@/lib/auth'

type Saldo={id:string;produto_id:string;quantidade:number;quantidade_reservada:number;quantidade_disponivel:number;unidade:string|null;produto?:{codigo:string|null;nome:string}|null;local?:{id:string;nome:string;unidade?:{id:string;nome:string}|null}|null;endereco?:{id:string;codigo:string}|null}
type Endereco={id:string;codigo:string;zona:string|null;corredor:string|null;estante:string|null;prateleira:string|null;caixa:string|null}
type Local={id:string;nome:string;enderecos:Endereco[]}
type Unidade={id:string;nome:string;locais:Local[]}
const n=(v:number)=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:3})
function endereco(e:Endereco){return [e.zona&&`Zona ${e.zona}`,e.corredor&&`Corredor ${e.corredor}`,e.estante&&`Estante ${e.estante}`,e.prateleira&&`Prateleira ${e.prateleira}`,e.caixa&&`Caixa ${e.caixa}`].filter(Boolean).join(' • ')||e.codigo}

export default function Enderecar(){
 const[saldos,setSaldos]=useState<Saldo[]>([]),[unidades,setUnidades]=useState<Unidade[]>([]),[saldoId,setSaldoId]=useState(''),[enderecoId,setEnderecoId]=useState(''),[quantidade,setQuantidade]=useState(''),[busca,setBusca]=useState(''),[erro,setErro]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true)
 async function t(){const x=await tokenAtual();if(!x)throw new Error('Sessão expirada.');return x}
 async function carregar(){setLoading(true);setErro('');try{const tk=await t();const[r1,r2]=await Promise.all([fetch('/api/estoque?limit=1000',{headers:{Authorization:`Bearer ${tk}`},cache:'no-store'}),fetch('/api/estoque/estrutura',{headers:{Authorization:`Bearer ${tk}`},cache:'no-store'})]);const j1=await r1.json(),j2=await r2.json();if(!r1.ok)throw new Error(j1.error);if(!r2.ok)throw new Error(j2.error);setSaldos(j1.saldos||[]);setUnidades(j2.unidades||[])}catch(e){setErro(e instanceof Error?e.message:'Erro ao carregar.')}finally{setLoading(false)}}
 useEffect(()=>{carregar()},[])
 const saldo=useMemo(()=>saldos.find(s=>s.id===saldoId)||null,[saldos,saldoId])
 const destinos=useMemo(()=>{if(!saldo?.local?.id)return[] as Endereco[];for(const u of unidades)for(const l of u.locais||[])if(l.id===saldo.local.id)return(l.enderecos||[]).filter(e=>e.id!==saldo.endereco?.id);return[]},[unidades,saldo])
 const filtrados=useMemo(()=>{const q=busca.trim().toUpperCase();return saldos.filter(s=>Number(s.quantidade_disponivel)>0&&(!q||String(s.produto?.codigo||'').toUpperCase().includes(q)||String(s.produto?.nome||'').toUpperCase().includes(q)))},[saldos,busca])
 async function mover(){setErro('');setMsg('');if(!saldoId||!enderecoId||Number(quantidade)<=0)return setErro('Escolha o saldo, o endereço e a quantidade.');try{const tk=await t();const r=await fetch('/api/estoque/enderecar',{method:'POST',headers:{Authorization:`Bearer ${tk}`,'Content-Type':'application/json'},body:JSON.stringify({saldoOrigemId:saldoId,enderecoDestinoId:enderecoId,quantidade:Number(quantidade)})});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||j.motivo||'Não foi possível mover.');setMsg('Produto endereçado com sucesso.');setQuantidade('');setSaldoId('');setEnderecoId('');await carregar()}catch(e){setErro(e instanceof Error?e.message:'Erro ao endereçar.')}}
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-5">
  <header className="flex items-center justify-between"><div className="flex items-center gap-3"><Link href="/estoque" className="rounded-xl border bg-white p-2.5"><ArrowLeft size={18}/></Link><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">Estoque • Endereçamento</p><h1 className="text-2xl font-bold">Endereçar produtos</h1><p className="text-sm text-slate-600">Mova o saldo para corredor, estante, prateleira, caixa ou gaveta.</p></div></div><button onClick={carregar} className="rounded-xl border bg-white p-2.5"><RefreshCw size={18}/></button></header>
  {erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{msg&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</div>}
  <section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><PackageSearch size={20}/><h2 className="font-bold">1. Escolha o produto e saldo</h2></div><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar código ou produto..." className="mt-3 w-full rounded-xl border px-3 py-2"/><div className="mt-3 max-h-72 overflow-auto rounded-xl border">{loading?<div className="p-8 text-center">Carregando...</div>:filtrados.map(s=><button key={s.id} onClick={()=>{setSaldoId(s.id);setEnderecoId('');setQuantidade('')}} className={`flex w-full items-center justify-between border-b p-3 text-left last:border-0 ${saldoId===s.id?'bg-blue-50':'hover:bg-slate-50'}`}><div><div className="text-xs font-mono text-slate-500">{s.produto?.codigo||'—'}</div><div className="font-medium">{s.produto?.nome}</div><div className="text-xs text-slate-500">{s.local?.unidade?.nome} • {s.local?.nome} • {s.endereco?.codigo||'Sem endereço'}</div></div><div className="text-right"><div className="font-bold text-emerald-700">{n(s.quantidade_disponivel)} {s.unidade||''}</div><div className="text-xs text-slate-400">disponível</div></div></button>)}</div></section>
  {saldo&&<section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><MapPin size={20}/><h2 className="font-bold">2. Escolha o endereço de destino</h2></div><p className="mt-1 text-sm text-slate-500">O destino precisa estar no mesmo local de estoque. Para outra loja ou depósito, use Transferências.</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_180px_auto]"><select value={enderecoId} onChange={e=>setEnderecoId(e.target.value)} className="rounded-xl border px-3 py-2"><option value="">Escolha corredor/prateleira/caixa</option>{destinos.map(e=><option key={e.id} value={e.id}>{e.codigo} • {endereco(e)}</option>)}</select><input type="number" min="0" max={saldo.quantidade_disponivel} step="any" value={quantidade} onChange={e=>setQuantidade(e.target.value)} placeholder="Quantidade" className="rounded-xl border px-3 py-2"/><button onClick={mover} className="rounded-xl bg-slate-900 px-4 py-2.5 font-semibold text-white">Confirmar endereço</button></div>{!destinos.length&&<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Cadastre primeiro um endereço em <Link href="/estoque/estrutura" className="font-semibold underline">Estrutura do estoque</Link>.</div>}</section>}
 </div></main>
}
