from pathlib import Path

updates = {
    'docs/ai-handoff/CURRENT_STATE.md': '''\n\n## COLABORAÇÃO + NOTIFICAÇÕES V1 — preparada em branch (2026-08-18)\n\nBranch: `feat/colaboracao-notificacoes-v1`.\n\nAuditoria read-only de produção confirmou:\n- `tarefas` e `tarefa_colunas` ainda usavam `acesso_total_temporario` (`ALL using=true/check=true`);\n- `eventos` e `evento_convidados` já possuíam RLS por dono/convidado.\n\nImplementado na branch:\n- migration `20260818013000_colaboracao_notificacoes_v1.sql`;\n- `tarefas`: `solicitante_id`, `solicitante_nome`, `atribuida_em`, `prioridade`;\n- substituição da RLS permissiva de `tarefas`/`tarefa_colunas` por policies do próprio usuário;\n- API server-side autenticada `/api/tarefas/atribuir` para atribuição cross-user;\n- criação automática das colunas padrão do responsável quando necessário;\n- notificações persistentes por destinatário (`notificacoes`) com RLS própria;\n- preferências por usuário (`notificacao_preferencias`), incluindo `som_ativo` e volume;\n- Realtime para novas notificações;\n- trigger tarefa atribuída -> notificação;\n- trigger convite de agenda -> notificação;\n- sino do Topbar lê notificações persistentes, marca lidas e permite ativar/desativar som;\n- Home e tela `Minhas Tarefas` permitem escolher responsável; tarefa recebida mostra quem criou;\n- tarefa recorrente atribuída para outro usuário permanece bloqueada nesta V1;\n- automações de orçamento/assistência passaram a usar a API segura; existe fallback legado somente para a janela anterior ao apply da migration.\n\nValidações já concluídas na branch:\n- auditoria PostgreSQL READ ONLY registrada em `docs/tecnico/auditoria-rls-colaboracao-2026-08-17.md`;\n- migration executada integralmente em PostgreSQL 16 efêmero; triggers de tarefa/agenda geraram exatamente uma notificação cada; RLS temporária removida no teste; Realtime confirmado;\n- build Next.js completo verde após integração da UI.\n\nA migration ainda NÃO foi aplicada em produção. Próximo gate: PR -> Build + Vercel + Supabase dry-run oficiais -> merge. Depois pedir autorização explícita específica antes de `APPLY_PRODUCTION`. Chat e sincronização externa de calendário continuam fora desta V1.\n''',
    'docs/ai-handoff/IMPLEMENTATIONS.md': '''\n\n## 2026-08-18 — Colaboração de tarefas + notificações V1 (em validação)\n\nBranch `feat/colaboracao-notificacoes-v1`.\n\n- Auditoria read-only confirmou RLS temporária permissiva em `tarefas` e `tarefa_colunas`.\n- Migration preparada para fechar essa RLS e adicionar metadados auditáveis de atribuição.\n- Atribuição para outro usuário ocorre pela API autenticada server-side; o browser não recebe poder de escrever tarefas de terceiros.\n- Notificações persistentes com lido/não lido, origem, criador e destinatário.\n- Preferência de som por usuário; som usa Web Audio após interação do usuário e só toca quando habilitado.\n- Realtime em `notificacoes`.\n- Tarefa atribuída e convite de agenda geram notificação por trigger de banco.\n- Home e Minhas Tarefas permitem selecionar responsável; prioridade alta/urgente é registrada na atribuição.\n- Automações existentes de orçamento/assistência migradas para a rota segura com compatibilidade pré-migration.\n- Migration validada em PostgreSQL 16 efêmero; build completo verde.\n- Produção ainda não alterada.\n''',
    'docs/ai-handoff/NEXT_TASK.md': '''\n\n## Frente ativa — Colaboração e notificações\n\nConcluir PR da branch `feat/colaboracao-notificacoes-v1` pelos gates oficiais.\n\nSe Build + Vercel + Supabase dry-run ficarem verdes:\n1. mergear o código/migration na `main`;\n2. NÃO considerar a migration ativa;\n3. pedir autorização explícita para aplicar somente `20260818013000_colaboracao_notificacoes_v1.sql`;\n4. depois do apply, fazer pós-auditoria read-only de RLS, colunas, tabelas de notificação, publication realtime e triggers;\n5. testar funcionalmente atribuição entre dois usuários e convite de agenda com notificação.\n\nApós essa V1 estar ativa, próxima implementação separada: chat direto + chat contextual (orçamento/obra/tarefa). Depois, estudar sincronização Google/Outlook mantendo o Atlas como agenda operacional principal.\n\nA PR #166 (orçamento Linha -> Tipologia -> Configuração validada) continua separada; não aplicar sua migration sem autorização específica própria.\n''',
}

for name, addition in updates.items():
    p = Path(name)
    text = p.read_text(encoding='utf-8')
    marker = addition.strip().splitlines()[0]
    if marker not in text:
        p.write_text(text.rstrip() + addition, encoding='utf-8')
