from pathlib import Path

updates = {
    'docs/ai-handoff/CURRENT_STATE.md': '''\n\n## HOME OPERACIONAL V1 — implementação em validação (2026-08-17)\n\nBranch: `feat/home-operacional-v1`.\n\nDireção funcional aprovada pelo usuário: a Home passa a ser a central diária do Atlas, com tarefas, agenda/calendário, alertas e indicadores operacionais.\n\nImplementado nesta V1 sem migration:\n- Hero simplificado; removido o botão duplicado `Novo orçamento` de dentro do Hero; o `+ Novo` do Topbar continua sendo a entrada de orçamento rápido.\n- Ações rápidas `Nova tarefa` e `Novo compromisso`.\n- `Minhas tarefas` usa a tabela/helper existente `tarefas`; permite concluir e criar tarefa para o próprio usuário.\n- `Agenda / Calendário` usa `eventos` + `evento_convidados`; mostra compromissos próprios/convites e permite criar compromisso convidando usuários já cadastrados.\n- Alertas são derivados em tempo real de dados já existentes: tarefa vencida, tarefa para hoje, convite de agenda pendente e compromisso iniciando em até 60 minutos.\n- Topbar ganhou sino com badge desses alertas operacionais. Nesta V1 não existe persistência de lido/não lido e não existe som.\n- Indicadores inferiores usam critérios explícitos: orçamentos `rascunho/enviado`; medições ainda não `aprovado`; total de cards em `producao_itens`; tarefas vencidas do usuário logado.\n- Não foi criada tabela de chat e não foi simulada atribuição de tarefas entre usuários. O schema atual de `tarefas` não registra solicitante; colaboração formal fica para migration/PR separada.\n\nPróximo gate desta frente: PR -> Build Validation + Vercel verdes -> merge. Depois, em PR separada, desenhar colaboração auditável (solicitante/responsável), notificações persistentes, preferências de som, chat e posterior sincronização de agendas externas.\n''',
    'docs/ai-handoff/IMPLEMENTATIONS.md': '''\n\n## 2026-08-17 — Home Operacional V1 (em validação)\n\nBranch `feat/home-operacional-v1`, sem migration.\n\n- Home diária conecta dados reais de tarefas e eventos já existentes.\n- Criação rápida de tarefa pessoal e compromisso de agenda.\n- Compromisso pode convidar outros usuários pelo mecanismo existente `evento_convidados`.\n- Calendário mensal + agenda do dia.\n- Alertas derivados de tarefa vencida, tarefa de hoje, convite pendente e compromisso próximo.\n- Sino de alertas no Topbar.\n- Hero sem segundo botão de orçamento.\n- KPIs operacionais com critérios explícitos; Produção conta cards do quadro sem inferir coluna final.\n- Build completo local/temporário verde antes da PR.\n- Som, lido/não lido persistente, tarefa criada por outro usuário, chat e sync Google/Outlook NÃO fazem parte desta V1.\n''',
    'docs/ai-handoff/NEXT_TASK.md': '''\n\n## Frente ativa — Home Operacional\n\nA Home Operacional V1 está em `feat/home-operacional-v1` e deve passar pelos gates normais antes do merge.\n\nDepois da V1, criar uma implementação separada para colaboração e comunicação, sem atalhos de schema:\n1. registrar solicitante/atribuidor da tarefa e auditoria de atribuição antes de permitir tarefa formal para outro usuário;\n2. criar notificações persistentes com estado lido/não lido e vínculo ao objeto de origem;\n3. preferências por usuário para categorias de alerta e som;\n4. alertas sonoros somente com configuração/consentimento adequado do navegador;\n5. chat direto e chat contextual (orçamento/obra/tarefa) com participantes e histórico;\n6. estudar sincronização de agenda externa (Google/Outlook) sem substituir a agenda operacional do Atlas.\n\nNão declarar nenhum desses itens da fase seguinte como implementado até existir código/schema real e checks verdes.\n''',
}

for name, addition in updates.items():
    p = Path(name)
    text = p.read_text(encoding='utf-8')
    marker = addition.strip().splitlines()[0]
    if marker not in text:
        p.write_text(text.rstrip() + addition, encoding='utf-8')
