from pathlib import Path

entries = {
    Path('docs/ai-handoff/CURRENT_STATE.md'): '''\n\n## PRODUTOS — PROVENIÊNCIA DOS PERFIS W.VETRO PREPARADA E TESTADA — 2026-08-17\n\nA migration `20260817170000_reconciliar_proveniencia_perfis_wvetro_v1.sql` está preparada, mas **NÃO aplicada em produção**.\n\nEscopo:\n- reconcilia somente os 1.307 perfis W.Vetro já existentes no Atlas;\n- não insere produtos;\n- altera apenas `codigo_origem`, `origem`, `unidade_origem`, `tamanho_barra_mm_origem`, `ncm_origem`, `dados_origem` e `updated_at`;\n- todos os demais campos são congelados e comparados antes/depois dentro da própria transação;\n- `tamanho_barra_mm` operacional permanece sem promoção automática;\n- os 4 `NCM = 16` e os 68 `Nome Fabricante = 16` permanecem somente como dados crus de origem, sem promover NCM/marca operacional.\n\nProteções:\n- Gate 1 exige exatamente 1.307 perfis e o hash canônico do snapshot Atlas auditado;\n- Gate 2 reconstrói a fonte W.Vetro com 249 exceções explícitas e exige o hash canônico da planilha auditada;\n- os dois hashes usam `COLLATE "C"` para ordenação determinística independente da locale do PostgreSQL;\n- a migration aborta se qualquer campo operacional/protegido mudar.\n\nSHA-256 da migration preparada: `cc34865fdcd6e7856e13608ba13b065f2630f57c89e6079720027d385bd4a3cf`.\n\nValidação completa executada fora da produção no run `32048680317`:\n- snapshot atual de produção exportado em transação `READ ONLY`: 1.307 perfis;\n- snapshot antigo x atual comparado: 0 diferenças nos campos auditados;\n- migration executada integralmente em PostgreSQL 16 efêmero;\n- log: `UPDATE 1307`;\n- todos os pós-checks passaram e a transação efêmera terminou em `COMMIT`;\n- verificação final: 1.307 perfis com `origem = wvetro`, 1.307 tamanhos de origem preenchidos e 0 tamanhos promovidos para `tamanho_barra_mm`.\n\nUma primeira execução efêmera foi corretamente bloqueada por diferença de collation na ordenação do hash. A investigação comprovou 0 drift de dados; a correção foi somente tornar os dois `ORDER BY` dos hashes determinísticos com `COLLATE "C"`.\n\nPróximo gate: PR da migration + dry-run oficial. Apply em produção exige autorização explícita específica e confirmação `APPLY_PRODUCTION`.\n''',
    Path('docs/ai-handoff/IMPLEMENTATIONS.md'): '''\n\n## Perfis W.Vetro — proveniência preparada e validada fora de produção — 2026-08-17\n\n- criada `20260817170000_reconciliar_proveniencia_perfis_wvetro_v1.sql`;\n- sem INSERT: reconcilia os 1.307 perfis preexistentes;\n- somente campos de proveniência são atualizados; campos operacionais ficam protegidos por snapshot JSON antes/depois;\n- fonte compactada com 249 exceções explícitas e dois hashes canônicos de auditoria;\n- hashes tornados determinísticos com `COLLATE "C"`;\n- run efêmero `32048680317` executou a migration inteira sobre snapshot read-only da produção: `UPDATE 1307`, pós-checks aprovados e `COMMIT`;\n- resultado efêmero: 1.307 proveniências W.Vetro, 1.307 tamanhos de origem e 0 promoções de tamanho operacional;\n- produção permaneceu sem escrita; migration ainda não aplicada.\n''',
    Path('docs/ai-handoff/NEXT_TASK.md'): '''\n\n## GATE ATUAL — PERFIS W.VETRO / PROVENIÊNCIA — 2026-08-17\n\nA auditoria dos 1.307 perfis está concluída e a migration de proveniência está preparada/testada em banco efêmero, mas **não está aplicada em produção**.\n\nMigration:\n`supabase/migrations/20260817170000_reconciliar_proveniencia_perfis_wvetro_v1.sql`\n\nEstado:\n- 1.307 perfis da fonte = 1.307 perfis Atlas; 0 faltantes e 0 exclusivos;\n- migration sem INSERT e sem overwrite operacional;\n- SHA-256 `cc34865fdcd6e7856e13608ba13b065f2630f57c89e6079720027d385bd4a3cf`;\n- validação integral em PostgreSQL efêmero aprovada no run `32048680317`;\n- produção acessada somente em `READ ONLY`;\n- tamanho/NCM/fabricante suspeitos continuam não promovidos.\n\nPróximos passos obrigatórios:\n1. concluir/mergear a PR de auditoria #162 somente com checks exigidos verdes;\n2. abrir/validar PR separada da migration;\n3. exigir dry-run oficial do `Supabase Database Control`;\n4. mergear somente com Build Validation + Vercel + controle de migration verdes;\n5. depois do merge, solicitar autorização explícita para esta migration específica antes de `APPLY_PRODUCTION`;\n6. após apply, verificar run/log e pós-estado antes de documentar como ativo.\n\nNão interpretar `pode continuar` como autorização para apply em produção.\n'''
}

for path, block in entries.items():
    text = path.read_text(encoding='utf-8')
    marker = block.strip().splitlines()[0]
    if marker not in text:
        path.write_text(text.rstrip() + block, encoding='utf-8')
