import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabaseAdmin'
import { autenticarBalcao, parseNumero } from '@/lib/balcaoServer'

export const runtime='nodejs';export const dynamic='force-dynamic'
export async function GET(req:NextRequest){const u=await autenticarBalcao(req,'caixa-balcao','consulta');if(!u)return NextResponse.json({error:'Sem acesso ao Contas a Receber.'},{status:403});try{const status=req.nextUrl.searchParams.get('status')||'aberto';let q=supabaseAdmin.from('financeiro_contas_receber').select('*').order('vencimento',{ascending:true}).limit(300);if(status!=='todos')q=q.eq('status',status);const {data,error}=await q;if(error)throw error;return NextResponse.json({ok:true,contas:data||[]})}catch(e){console.error('Erro contas receber',e);return NextResponse.json({error:'Não foi possível carregar o Contas a Receber.'},{status:500})}}
export async function POST(req:NextRequest){const u=await autenticarBalcao(req,'caixa-balcao','edicao');if(!u)return NextResponse.json({error:'Sem permissão para baixar recebimentos.'},{status:403});try{const b=await req.json();const id=String(b.id||'');const valor=parseNumero(b.valorPago);const forma=String(b.forma||'pix');if(!id||valor<=0)return NextResponse.json({error:'Informe conta e valor recebido.'},{status:400});const {data:conta}=await supabaseAdmin.from('financeiro_contas_receber').select('*').eq('id',id).maybeSingle();if(!conta)return NextResponse.json({error:'Conta não encontrada.'},{status:404});if(conta.status==='pago')return NextResponse.json({error:'Conta já está paga.'},{status:409});const agora=new Date().toISOString();const {error}=await supabaseAdmin.from('financeiro_contas_receber').update({status:'pago',data_pagamento:agora.slice(0,10),valor_pago:valor,forma,updated_at:agora}).eq('id',id);if(error)throw error;
 if(['dinheiro','pix','cartao_debito','cartao_credito','outros'].includes(forma)){const {data:caixa}=await supabaseAdmin.from('balcao_caixas').select('id').eq('operador_id',u.id).eq('status','aberto').order('aberto_em',{ascending:false}).limit(1).maybeSingle();if(caixa){await supabaseAdmin.from('balcao_caixa_movimentos').insert({caixa_id:caixa.id,venda_id:conta.venda_balcao_id,tipo:'recebimento',forma_pagamento:forma,entrada:valor,saida:0,descricao:`Recebimento ${conta.documento||''} parcela ${conta.parcela}/${conta.total_parcelas}`,criado_por_id:u.id,criado_por_nome:u.nome})}}
 return NextResponse.json({ok:true})}catch(e){console.error('Erro baixa conta receber',e);return NextResponse.json({error:e instanceof Error?e.message:'Erro ao baixar recebimento.'},{status:500})}}
