'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Banknote, LockKeyhole, MinusCircle, PlusCircle, RefreshCw, Store, WalletCards } from 'lucide-react'
import { tokenAtual } from '@/lib/auth'

type PontoCaixa={id:string;codigo:string;nome:string;tipo:string;unidadeId:string;localEstoqueId:string;unidadeNome:string;localNome:string}
type Caixa={id:string;status:string;operador_nome:string;aberto_em:string;saldo_inicial:number;saldo_esperado?:number|null;saldo_contado?:number|null;diferenca?:number|null;ponto?:PontoCaixa|null}
type Mov={id:string;tipo:string;forma_pagamento?:string|null;entrada:number;saida:number;descricao?:string|null;criado_por_nome:string;created_at:string}
function moeda(n:number){return Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function hora(s:string){return new Date(s).toLocaleString('pt-BR')}

export default function CaixaBalcao(){
 const [caixa,setCaixa]=useState<Caixa|null>(null),[pontos,setPontos]=useState<PontoCaixa[]>([]),[pontoId,setPontoId]=useState(''),[movs,setMovs]=useState<Mov[]>([]),[resumo,setResumo]=useState<Record<string,{entradas:number;saidas:number}>>({}),[saldoEsperado,setSaldoEsperado]=useState(0)
 const [saldoInicial,setSaldoInicial]=useState('300'),[suprimentoValor,setSuprimentoValor]=useState(''),[suprimentoDescricao,setSuprimentoDescricao]=useState(''),[sangriaValor,setSangriaValor]=useState(''),[sangriaDescricao,setSangriaDescricao]=useState(''),[saldoContado,setSaldoContado]=useState(''),[obsFechamento,setObsFechamento]=useState(''),[erro,setErro]=useState(''),[msg,setMsg]=useState(''),[carregando,setCarregando]=useState(true)
 async function api(url:string,init?:RequestInit){const t=await tokenAtual();if(!t)throw new Error('Sessão expirada.');return fetch(url,{...init,headers:{...(init?.headers||{}),Authorization:`Bearer ${t}`}})}
 async function carregar(){setCarregando(true);try{const r=await api('/api/balcao/caixa');const j=await r.json();if(!r.ok)throw new Error(j.error);setCaixa(j.caixa||null);setPontos(j.pontosCaixa||[]);if(!pontoId&&j.pontosCaixa?.length)setPontoId(j.pontosCaixa[0].id);setMovs(j.movimentos||[]);setResumo(j.resumo||{});setSaldoEsperado(Number(j.saldoFisicoEsperado||0))}catch(e){setErro(e instanceof Error?e.message:'Erro ao carregar caixa.')}finally{setCarregando(false)}}
 useEffect(()=>{carregar()},[])
 async function acao(nome:string,extra:Record<string,unknown>={}){setErro('');setMsg('');try{const r=await api('/api/balcao/caixa',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({acao:nome,caixaId:caixa?.id,...extra})});const j=await r.json();if(!r.ok)throw new Error(j.error);setMsg(nome==='abrir'?'Caixa aberto com sucesso.':nome==='fechar'?`Caixa fechado. Diferença ${moeda(Number(j.diferenca||0))}.`:'Movimento registrado.');if(nome==='suprimento'){setSuprimentoValor('');setSuprimentoDescricao('')}if(nome==='sangria'){setSangriaValor('');setSangriaDescricao('')}await carregar()}catch(e){setErro(e instanceof Error?e.message:'Erro na operação.')}}
 const entradas=Object.values(resumo).reduce((s,x)=>s+Number(x.entradas||0),0),saidas=Object.values(resumo).reduce((s,x)=>s+Number(x.saidas||0),0)
 const pontoSelecionado=pontos.find(p=>p.id===pontoId)
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-7xl space-y-4">
  <header className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href="/balcao" className="rounded-lg border bg-white p-2"><ArrowLeft size={18}/></Link><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-slate-400">Venda Balcão</p><h1 className="text-2xl font-bold">Caixa</h1><p className="text-sm text-slate-500">Cada caixa pertence a uma unidade e a um estoque padrão.</p></div></div><button onClick={carregar} className="rounded-lg border bg-white p-2"><RefreshCw size={17}/></button></header>
  {erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{msg&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</div>}
  {!caixa&&!carregando?<section className="mx-auto max-w-xl rounded-2xl border bg-white p-6"><div className="text-center"><Store size={44} className="mx-auto text-emerald-600"/><h2 className="mt-3 text-xl font-bold">Abrir caixa</h2><p className="mt-1 text-sm text-slate-500">Escolha o caixa que será operado neste turno.</p></div><label className="mt-5 block text-xs font-medium text-slate-500">Ponto de caixa<select value={pontoId} onChange={e=>setPontoId(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2.5 text-sm"><option value="">Selecione...</option>{pontos.map(p=><option key={p.id} value={p.id}>{p.codigo} — {p.nome} • {p.unidadeNome}</option>)}</select></label>{pontoSelecionado&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><strong>{pontoSelecionado.unidadeNome}</strong><div className="text-xs text-slate-500">Estoque padrão: {pontoSelecionado.localNome}</div></div>}<label className="mt-4 block text-xs font-medium text-slate-500">Saldo inicial em dinheiro<input type="number" step="0.01" value={saldoInicial} onChange={e=>setSaldoInicial(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2.5 text-base"/></label><button disabled={!pontoId} onClick={()=>acao('abrir',{pontoCaixaId:pontoId,saldoInicial:Number(saldoInicial)||0})} className="mt-5 w-full rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white disabled:opacity-40">Abrir caixa</button></section>:caixa&&<>
   <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Caixa em operação</div><div className="mt-1 text-lg font-bold">{caixa.ponto?.codigo||'Caixa'} — {caixa.ponto?.nome||'Venda Balcão'}</div><div className="text-sm text-emerald-800">{caixa.ponto?.unidadeNome||'Unidade'} • estoque: {caixa.ponto?.localNome||'Local padrão'}</div></div><div className="text-right text-xs text-emerald-800">Aberto por <strong>{caixa.operador_nome}</strong><br/>{hora(caixa.aberto_em)}</div></div></section>
   <section className="grid gap-3 md:grid-cols-5"><Card t="Saldo inicial" v={moeda(caixa.saldo_inicial)} icon={<Banknote/>}/><Card t="Entradas" v={moeda(entradas)} icon={<PlusCircle/>}/><Card t="Saídas" v={moeda(saidas)} icon={<MinusCircle/>}/><Card t="Dinheiro esperado" v={moeda(saldoEsperado)} icon={<WalletCards/>}/><Card t="Operador" v={caixa.operador_nome} icon={<Store/>}/></section>
   <section className="grid gap-3 md:grid-cols-3"><Operacao titulo="Suprimento" subtitulo="Adicionar dinheiro para troco" icon={<PlusCircle className="text-emerald-600"/>} valor={suprimentoValor} setValor={setSuprimentoValor} descricao={suprimentoDescricao} setDescricao={setSuprimentoDescricao} onClick={()=>acao('suprimento',{valor:Number(suprimentoValor)||0,descricao:suprimentoDescricao})}/><Operacao titulo="Sangria" subtitulo="Retirar dinheiro do caixa" icon={<MinusCircle className="text-amber-600"/>} valor={sangriaValor} setValor={setSangriaValor} descricao={sangriaDescricao} setDescricao={setSangriaDescricao} onClick={()=>acao('sangria',{valor:Number(sangriaValor)||0,descricao:sangriaDescricao})}/><div className="rounded-2xl border border-red-200 bg-white p-5"><LockKeyhole className="text-red-500"/><h3 className="mt-2 font-bold">Fechar caixa</h3><p className="text-xs text-slate-500">Conte somente o dinheiro físico da gaveta.</p><input type="number" step="0.01" value={saldoContado} onChange={e=>setSaldoContado(e.target.value)} placeholder="Saldo contado" className="mt-4 w-full rounded-xl border px-3 py-2"/><input value={obsFechamento} onChange={e=>setObsFechamento(e.target.value)} placeholder="Observação do fechamento" className="mt-2 w-full rounded-xl border px-3 py-2 text-sm"/><button onClick={()=>acao('fechar',{saldoContado:Number(saldoContado)||0,observacoes:obsFechamento})} className="mt-3 w-full rounded-xl border border-red-300 bg-red-50 px-3 py-2.5 font-semibold text-red-700">Fechar caixa</button></div></section>
   <div className="grid gap-4 xl:grid-cols-[1.4fr_1fr]"><section className="rounded-2xl border bg-white p-4"><h2 className="font-semibold">Movimentações do caixa</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-2">Data/Hora</th><th>Tipo</th><th>Descrição</th><th>Forma</th><th>Entrada</th><th>Saída</th><th>Operador</th></tr></thead><tbody>{movs.map(m=><tr key={m.id} className="border-t"><td className="p-2">{hora(m.created_at)}</td><td>{m.tipo}</td><td>{m.descricao||'—'}</td><td>{m.forma_pagamento||'—'}</td><td className="font-medium text-emerald-700">{m.entrada?moeda(m.entrada):'—'}</td><td className="font-medium text-red-600">{m.saida?moeda(m.saida):'—'}</td><td>{m.criado_por_nome}</td></tr>)}</tbody></table></div></section><section className="rounded-2xl border bg-white p-4"><h2 className="font-semibold">Resumo por forma de pagamento</h2><div className="mt-3 space-y-2">{Object.entries(resumo).map(([f,r])=><div key={f} className="grid grid-cols-3 rounded-xl bg-slate-50 p-3 text-sm"><span className="font-medium capitalize">{f.replaceAll('_',' ')}</span><span className="text-right text-emerald-700">+ {moeda(r.entradas)}</span><span className="text-right text-red-600">- {moeda(r.saidas)}</span></div>)}<div className="grid grid-cols-3 border-t pt-3 font-bold"><span>Total</span><span className="text-right text-emerald-700">{moeda(entradas)}</span><span className="text-right text-red-600">{moeda(saidas)}</span></div></div></section></div>
  </>}
 </div></main>}
function Card({t,v,icon}:{t:string;v:string;icon:React.ReactNode}){return <div className="rounded-2xl border bg-white p-4"><div className="text-emerald-700">{icon}</div><div className="mt-2 text-xs text-slate-500">{t}</div><div className="mt-1 font-bold">{v}</div></div>}
function Operacao({titulo,subtitulo,icon,valor,setValor,descricao,setDescricao,onClick}:{titulo:string;subtitulo:string;icon:React.ReactNode;valor:string;setValor:(v:string)=>void;descricao:string;setDescricao:(v:string)=>void;onClick:()=>void}){return <div className="rounded-2xl border bg-white p-5">{icon}<h3 className="mt-2 font-bold">{titulo}</h3><p className="text-xs text-slate-500">{subtitulo}</p><input type="number" step="0.01" value={valor} onChange={e=>setValor(e.target.value)} placeholder="Valor" className="mt-4 w-full rounded-xl border px-3 py-2"/><input value={descricao} onChange={e=>setDescricao(e.target.value)} placeholder="Descrição / motivo" className="mt-2 w-full rounded-xl border px-3 py-2 text-sm"/><button onClick={onClick} className="mt-3 w-full rounded-xl bg-slate-900 px-3 py-2.5 font-semibold text-white">Registrar {titulo.toLowerCase()}</button></div>}
