'use client'

import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Loader2, UserPlus } from 'lucide-react'
import { obterOuCriarCliente } from '@/lib/clientes'

export default function NovoClienteBalcao(){
 const router=useRouter();const [nome,setNome]=useState(''),[whatsapp,setWhatsapp]=useState(''),[telefone,setTelefone]=useState(''),[cpf,setCpf]=useState(''),[cidade,setCidade]=useState(''),[salvando,setSalvando]=useState(false),[erro,setErro]=useState('')
 async function salvar(){setErro('');if(!nome.trim())return setErro('Informe o nome do cliente.');setSalvando(true);try{const id=await obterOuCriarCliente({nome:nome.trim().toUpperCase(),whatsapp:whatsapp.trim()||undefined,telefone:telefone.trim()||undefined,cpf_cnpj:cpf.trim()||undefined,cidade:cidade.trim().toUpperCase()||undefined,origem:'outros'});if(!id)throw new Error('Não foi possível salvar o cliente.');router.push('/balcao')}catch(e){setErro(e instanceof Error?e.message:'Erro ao salvar cliente.')}finally{setSalvando(false)}}
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-xl"><header className="flex items-center gap-3"><Link href="/balcao" className="rounded-lg border bg-white p-2"><ArrowLeft size={18}/></Link><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-slate-400">Venda Balcão</p><h1 className="text-2xl font-bold">Novo cliente</h1><p className="text-sm text-slate-500">Cadastro rápido para atendimento no balcão.</p></div></header><section className="mt-5 rounded-2xl border bg-white p-5"><div className="space-y-3"><Campo label="Nome *" value={nome} onChange={setNome}/><div className="grid gap-3 sm:grid-cols-2"><Campo label="WhatsApp" value={whatsapp} onChange={setWhatsapp}/><Campo label="Telefone" value={telefone} onChange={setTelefone}/></div><div className="grid gap-3 sm:grid-cols-2"><Campo label="CPF / CNPJ" value={cpf} onChange={setCpf}/><Campo label="Cidade" value={cidade} onChange={setCidade}/></div>{erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</div>}<button onClick={salvar} disabled={salvando} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white disabled:opacity-50">{salvando?<Loader2 size={18} className="animate-spin"/>:<UserPlus size={18}/>}Salvar cliente e voltar à venda</button></div></section></div></main>}
function Campo({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-xs font-medium text-slate-600">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2.5 text-sm"/></label>}
