-- Melhorias Atlas v1
-- Compatibiliza a central existente e adiciona anexos, áudio, índices e RLS.

create table if not exists public.atlas_melhorias (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  criado_por_id uuid not null references public.usuarios(id) on delete restrict,
  criado_por_nome text,
  tipo text not null default 'melhoria' check (tipo in ('bug','melhoria','ideia')),
  titulo text not null,
  descricao text not null,
  tela text,
  area text,
  resultado_atual text,
  resultado_esperado text,
  impacto text,
  urgencia text not null default 'media' check (urgencia in ('baixa','media','alta','critica')),
  status text not null default 'novo' check (status in (
    'novo','ia_analisando','informacao_necessaria','solucao_proposta',
    'aguardando_aprovacao','aprovado','em_desenvolvimento','teste',
    'pronto_publicar','publicado','rejeitado'
  )),
  risco text not null default 'nao_avaliado' check (
    risco in ('nao_avaliado','baixo','medio','alto','critico')
  ),
  exige_aprovacao boolean not null default true,
  justificativa_risco text,
  analise_ia jsonb not null default '{}'::jsonb,
  aprovacao_status text not null default 'pendente' check (
    aprovacao_status in ('pendente','aprovado','rejeitado')
  ),
  aprovado_por_id uuid references public.usuarios(id) on delete set null,
  aprovado_por_nome text,
  aprovado_em timestamptz,
  responsavel_id uuid references public.usuarios(id) on delete set null,
  responsavel_nome text,
  observacoes_admin text,
  origem text not null default 'atlas_ia',
  dedupe_key text,
  relatos_count integer not null default 1 check (relatos_count >= 1),
  contexto_json jsonb not null default '{}'::jsonb,
  anexo_storage_path text,
  anexo_nome text,
  anexo_media_type text,
  audio_storage_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.atlas_melhorias
  add column if not exists anexo_storage_path text,
  add column if not exists anexo_nome text,
  add column if not exists anexo_media_type text,
  add column if not exists audio_storage_path text;

create index if not exists atlas_melhorias_empresa_status_idx
  on public.atlas_melhorias (empresa_id, status, created_at desc);

create index if not exists atlas_melhorias_empresa_dedupe_idx
  on public.atlas_melhorias (empresa_id, dedupe_key)
  where dedupe_key is not null;

create index if not exists atlas_melhorias_criado_por_idx
  on public.atlas_melhorias (criado_por_id, created_at desc);

alter table public.atlas_melhorias enable row level security;

drop policy if exists atlas_melhorias_self_select on public.atlas_melhorias;
create policy atlas_melhorias_self_select
on public.atlas_melhorias for select to authenticated
using (
  criado_por_id = (select auth.uid())
  and empresa_id = (
    select u.empresa_id
    from public.usuarios u
    where u.id = (select auth.uid())
  )
);

insert into storage.buckets (id, name, public, file_size_limit)
values ('atlas-melhorias', 'atlas-melhorias', false, 12582912)
on conflict (id) do update
set public = false, file_size_limit = 12582912;

create table if not exists public.atlas_melhorias_eventos (
  id uuid primary key default gen_random_uuid(),
  melhoria_id uuid not null references public.atlas_melhorias(id) on delete cascade,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  usuario_id uuid references public.usuarios(id) on delete set null,
  usuario_nome text,
  evento text not null,
  detalhe jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists atlas_melhorias_eventos_melhoria_idx
  on public.atlas_melhorias_eventos (melhoria_id, created_at desc);

create index if not exists atlas_melhorias_eventos_empresa_idx
  on public.atlas_melhorias_eventos (empresa_id, created_at desc);

alter table public.atlas_melhorias_eventos enable row level security;

create or replace function public.atlas_melhorias_touch_updated_at()
returns trigger
language plpgsql
set search_path to 'public'
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_atlas_melhorias_updated_at on public.atlas_melhorias;
create trigger trg_atlas_melhorias_updated_at
before update on public.atlas_melhorias
for each row execute function public.atlas_melhorias_touch_updated_at();
