alter table public.linha_produtos add column if not exists empresa_id uuid references public.empresas(id);
alter table public.produto_linhas add column if not exists empresa_id uuid references public.empresas(id);
update public.linha_produtos lp set empresa_id=p.empresa_id from public.produtos p where p.id=lp.produto_id and lp.empresa_id is null;
update public.produto_linhas pl set empresa_id=p.empresa_id from public.produtos p where p.id=pl.produto_id and pl.empresa_id is null;
alter table public.linha_produtos alter column empresa_id set default private.current_empresa_id();
alter table public.produto_linhas alter column empresa_id set default private.current_empresa_id();
alter table public.linha_produtos alter column empresa_id set not null;
alter table public.produto_linhas alter column empresa_id set not null;
create or replace function private.guard_produto_relacao_empresa() returns trigger language plpgsql security definer set search_path='' as $$
declare v_empresa uuid;
begin
 select p.empresa_id into v_empresa from public.produtos p where p.id=new.produto_id;
 if v_empresa is null then raise exception 'Produto inválido ou sem empresa'; end if;
 if new.empresa_id is null then new.empresa_id:=v_empresa; end if;
 if new.empresa_id is distinct from v_empresa then raise exception 'Relação de produto com empresa divergente'; end if;
 return new;
end; $$;
revoke all on function private.guard_produto_relacao_empresa() from public,anon,authenticated;
drop trigger if exists trg_linha_produtos_empresa on public.linha_produtos;
create trigger trg_linha_produtos_empresa before insert or update of produto_id,empresa_id on public.linha_produtos for each row execute function private.guard_produto_relacao_empresa();
drop trigger if exists trg_produto_linhas_empresa on public.produto_linhas;
create trigger trg_produto_linhas_empresa before insert or update of produto_id,empresa_id on public.produto_linhas for each row execute function private.guard_produto_relacao_empresa();
drop policy if exists acesso_total_temporario on public.linha_produtos;
drop policy if exists produto_linhas_permissivo on public.produto_linhas;
drop policy if exists tenant_linha_produtos_select on public.linha_produtos;
drop policy if exists tenant_linha_produtos_insert on public.linha_produtos;
drop policy if exists tenant_linha_produtos_update on public.linha_produtos;
drop policy if exists tenant_linha_produtos_delete on public.linha_produtos;
create policy tenant_linha_produtos_select on public.linha_produtos for select to authenticated using (empresa_id=private.current_empresa_id());
create policy tenant_linha_produtos_insert on public.linha_produtos for insert to authenticated with check (empresa_id=private.current_empresa_id() and exists(select 1 from public.produtos p where p.id=produto_id and p.empresa_id=private.current_empresa_id()));
create policy tenant_linha_produtos_update on public.linha_produtos for update to authenticated using (empresa_id=private.current_empresa_id()) with check (empresa_id=private.current_empresa_id() and exists(select 1 from public.produtos p where p.id=produto_id and p.empresa_id=private.current_empresa_id()));
create policy tenant_linha_produtos_delete on public.linha_produtos for delete to authenticated using (empresa_id=private.current_empresa_id());
drop policy if exists tenant_produto_linhas_select on public.produto_linhas;
drop policy if exists tenant_produto_linhas_insert on public.produto_linhas;
drop policy if exists tenant_produto_linhas_update on public.produto_linhas;
drop policy if exists tenant_produto_linhas_delete on public.produto_linhas;
create policy tenant_produto_linhas_select on public.produto_linhas for select to authenticated using (empresa_id=private.current_empresa_id());
create policy tenant_produto_linhas_insert on public.produto_linhas for insert to authenticated with check (empresa_id=private.current_empresa_id() and exists(select 1 from public.produtos p where p.id=produto_id and p.empresa_id=private.current_empresa_id()));
create policy tenant_produto_linhas_update on public.produto_linhas for update to authenticated using (empresa_id=private.current_empresa_id()) with check (empresa_id=private.current_empresa_id() and exists(select 1 from public.produtos p where p.id=produto_id and p.empresa_id=private.current_empresa_id()));
create policy tenant_produto_linhas_delete on public.produto_linhas for delete to authenticated using (empresa_id=private.current_empresa_id());
