create table if not exists public.obras (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  cliente_id uuid not null references public.clientes(id) on delete cascade,
  nome text not null,
  status text not null default 'planejamento',
  endereco text,
  numero_endereco text,
  complemento text,
  bairro text,
  cidade text,
  uf text,
  cep text,
  responsavel text,
  data_inicio date,
  previsao_entrega date,
  observacoes text,
  criado_por_id uuid,
  criado_por_nome text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_obras_cliente_id on public.obras(cliente_id);
create index if not exists idx_obras_status on public.obras(status);
create index if not exists idx_obras_created_at on public.obras(created_at desc);

alter table public.obras enable row level security;
drop policy if exists "obras_select_total" on public.obras;
drop policy if exists "obras_insert_total" on public.obras;
drop policy if exists "obras_update_total" on public.obras;
drop policy if exists "obras_delete_total" on public.obras;
create policy "obras_select_total" on public.obras for select using (true);
create policy "obras_insert_total" on public.obras for insert with check (true);
create policy "obras_update_total" on public.obras for update using (true) with check (true);
create policy "obras_delete_total" on public.obras for delete using (true);
grant select, insert, update, delete on public.obras to anon, authenticated;

do $$ begin
  alter table public.orcamentos add column obra_id uuid references public.obras(id) on delete set null;
exception when duplicate_column then null; end $$;
do $$ begin
  alter table public.balcao_orcamentos add column obra_id uuid references public.obras(id) on delete set null;
exception when duplicate_column then null; end $$;
do $$ begin
  alter table public.balcao_vendas add column obra_id uuid references public.obras(id) on delete set null;
exception when duplicate_column then null; end $$;
do $$ begin
  alter table public.assistencias add column obra_id uuid references public.obras(id) on delete set null;
exception when duplicate_column then null; end $$;
do $$ begin
  alter table public.medicoes_finais add column obra_id uuid references public.obras(id) on delete set null;
exception when duplicate_column then null; end $$;
do $$ begin
  alter table public.financeiro_contas_receber add column obra_id uuid references public.obras(id) on delete set null;
exception when duplicate_column then null; end $$;
do $$ begin
  alter table public.financeiro_contas_receber add column orcamento_id uuid references public.orcamentos(id) on delete set null;
exception when duplicate_column then null; end $$;

create index if not exists idx_orcamentos_obra_id on public.orcamentos(obra_id);
create index if not exists idx_balcao_orcamentos_obra_id on public.balcao_orcamentos(obra_id);
create index if not exists idx_balcao_vendas_obra_id on public.balcao_vendas(obra_id);
create index if not exists idx_assistencias_obra_id on public.assistencias(obra_id);
create index if not exists idx_medicoes_finais_obra_id on public.medicoes_finais(obra_id);
create index if not exists idx_financeiro_receber_obra_id on public.financeiro_contas_receber(obra_id);
create index if not exists idx_financeiro_receber_orcamento_id on public.financeiro_contas_receber(orcamento_id);

create table if not exists public.financeiro_recebimentos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.clientes(id) on delete restrict,
  cliente_nome text not null,
  obra_id uuid references public.obras(id) on delete set null,
  data_recebimento date not null default current_date,
  valor numeric(14,2) not null check (valor > 0),
  forma text,
  referencia text,
  observacoes text,
  status text not null default 'registrado',
  criado_por_id uuid,
  criado_por_nome text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_fin_recebimentos_cliente on public.financeiro_recebimentos(cliente_id, data_recebimento desc);
create index if not exists idx_fin_recebimentos_obra on public.financeiro_recebimentos(obra_id);

alter table public.financeiro_recebimentos enable row level security;
drop policy if exists "financeiro_recebimentos_select_total" on public.financeiro_recebimentos;
drop policy if exists "financeiro_recebimentos_insert_total" on public.financeiro_recebimentos;
drop policy if exists "financeiro_recebimentos_update_total" on public.financeiro_recebimentos;
drop policy if exists "financeiro_recebimentos_delete_total" on public.financeiro_recebimentos;
create policy "financeiro_recebimentos_select_total" on public.financeiro_recebimentos for select using (true);
create policy "financeiro_recebimentos_insert_total" on public.financeiro_recebimentos for insert with check (true);
create policy "financeiro_recebimentos_update_total" on public.financeiro_recebimentos for update using (true) with check (true);
create policy "financeiro_recebimentos_delete_total" on public.financeiro_recebimentos for delete using (true);
grant select, insert, update, delete on public.financeiro_recebimentos to anon, authenticated;

create table if not exists public.financeiro_recebimento_alocacoes (
  id uuid primary key default gen_random_uuid(),
  recebimento_id uuid not null references public.financeiro_recebimentos(id) on delete cascade,
  conta_receber_id uuid references public.financeiro_contas_receber(id) on delete set null,
  obra_id uuid references public.obras(id) on delete set null,
  tipo text not null default 'conta',
  valor numeric(14,2) not null check (valor > 0),
  criado_por_id uuid,
  criado_por_nome text,
  created_at timestamptz not null default now()
);

create index if not exists idx_fin_alocacoes_recebimento on public.financeiro_recebimento_alocacoes(recebimento_id);
create index if not exists idx_fin_alocacoes_conta on public.financeiro_recebimento_alocacoes(conta_receber_id);
create index if not exists idx_fin_alocacoes_obra on public.financeiro_recebimento_alocacoes(obra_id);

alter table public.financeiro_recebimento_alocacoes enable row level security;
drop policy if exists "financeiro_alocacoes_select_total" on public.financeiro_recebimento_alocacoes;
drop policy if exists "financeiro_alocacoes_insert_total" on public.financeiro_recebimento_alocacoes;
drop policy if exists "financeiro_alocacoes_update_total" on public.financeiro_recebimento_alocacoes;
drop policy if exists "financeiro_alocacoes_delete_total" on public.financeiro_recebimento_alocacoes;
create policy "financeiro_alocacoes_select_total" on public.financeiro_recebimento_alocacoes for select using (true);
create policy "financeiro_alocacoes_insert_total" on public.financeiro_recebimento_alocacoes for insert with check (true);
create policy "financeiro_alocacoes_update_total" on public.financeiro_recebimento_alocacoes for update using (true) with check (true);
create policy "financeiro_alocacoes_delete_total" on public.financeiro_recebimento_alocacoes for delete using (true);
grant select, insert, update, delete on public.financeiro_recebimento_alocacoes to anon, authenticated;

create table if not exists public.cliente_documentos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.clientes(id) on delete cascade,
  obra_id uuid references public.obras(id) on delete set null,
  titulo text not null,
  nome_arquivo text,
  url text not null,
  tipo text,
  observacoes text,
  criado_por_id uuid,
  criado_por_nome text,
  created_at timestamptz not null default now()
);

create index if not exists idx_cliente_documentos_cliente on public.cliente_documentos(cliente_id, created_at desc);
create index if not exists idx_cliente_documentos_obra on public.cliente_documentos(obra_id);

alter table public.cliente_documentos enable row level security;
drop policy if exists "cliente_documentos_select_total" on public.cliente_documentos;
drop policy if exists "cliente_documentos_insert_total" on public.cliente_documentos;
drop policy if exists "cliente_documentos_update_total" on public.cliente_documentos;
drop policy if exists "cliente_documentos_delete_total" on public.cliente_documentos;
create policy "cliente_documentos_select_total" on public.cliente_documentos for select using (true);
create policy "cliente_documentos_insert_total" on public.cliente_documentos for insert with check (true);
create policy "cliente_documentos_update_total" on public.cliente_documentos for update using (true) with check (true);
create policy "cliente_documentos_delete_total" on public.cliente_documentos for delete using (true);
grant select, insert, update, delete on public.cliente_documentos to anon, authenticated;

create or replace function public.alocar_recebimento_cliente_em_obra(
  p_recebimento_id uuid,
  p_obra_id uuid,
  p_valor numeric,
  p_usuario_id uuid default null,
  p_usuario_nome text default null
) returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  r public.financeiro_recebimentos%rowtype;
  o public.obras%rowtype;
  c record;
  v_total_alocado numeric := 0;
  v_disponivel numeric := 0;
  v_restante numeric := 0;
  v_saldo_conta numeric := 0;
  v_aplicar numeric := 0;
begin
  if p_valor is null or p_valor <= 0 then
    raise exception 'Valor para alocação deve ser maior que zero.';
  end if;

  select * into r from public.financeiro_recebimentos where id = p_recebimento_id for update;
  if r.id is null then raise exception 'Recebimento não encontrado.'; end if;
  if r.status = 'cancelado' then raise exception 'Recebimento cancelado não pode ser alocado.'; end if;

  select * into o from public.obras where id = p_obra_id;
  if o.id is null then raise exception 'Obra não encontrada.'; end if;
  if o.cliente_id <> r.cliente_id then raise exception 'A obra não pertence a este cliente.'; end if;

  select coalesce(sum(a.valor),0) into v_total_alocado
  from public.financeiro_recebimento_alocacoes a
  where a.recebimento_id = r.id;

  v_disponivel := r.valor - v_total_alocado;
  if p_valor > v_disponivel + 0.009 then
    raise exception 'Valor maior que o saldo disponível do recebimento.';
  end if;

  v_restante := p_valor;

  for c in
    select cr.id, cr.valor, coalesce(cr.valor_pago,0) valor_pago
    from public.financeiro_contas_receber cr
    where cr.cliente_id = r.cliente_id
      and cr.obra_id = p_obra_id
      and cr.status not in ('pago','cancelado')
      and cr.valor > coalesce(cr.valor_pago,0)
    order by cr.vencimento nulls last, cr.data_emissao, cr.created_at
    for update
  loop
    exit when v_restante <= 0.009;
    v_saldo_conta := c.valor - c.valor_pago;
    v_aplicar := least(v_restante, v_saldo_conta);

    update public.financeiro_contas_receber
    set valor_pago = coalesce(valor_pago,0) + v_aplicar,
        data_pagamento = case when coalesce(valor_pago,0) + v_aplicar >= valor - 0.009 then r.data_recebimento else data_pagamento end,
        forma = coalesce(r.forma, forma),
        status = case when coalesce(valor_pago,0) + v_aplicar >= valor - 0.009 then 'pago' else 'parcial' end,
        updated_at = now()
    where id = c.id;

    insert into public.financeiro_recebimento_alocacoes(
      recebimento_id, conta_receber_id, obra_id, tipo, valor, criado_por_id, criado_por_nome
    ) values (
      r.id, c.id, p_obra_id, 'conta', v_aplicar, p_usuario_id, p_usuario_nome
    );

    v_restante := v_restante - v_aplicar;
  end loop;

  if v_restante > 0.009 then
    insert into public.financeiro_recebimento_alocacoes(
      recebimento_id, conta_receber_id, obra_id, tipo, valor, criado_por_id, criado_por_nome
    ) values (
      r.id, null, p_obra_id, 'credito_obra', v_restante, p_usuario_id, p_usuario_nome
    );
  end if;

  if r.obra_id is null then
    update public.financeiro_recebimentos set obra_id = p_obra_id, updated_at = now() where id = r.id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'recebimento_id', r.id,
    'obra_id', p_obra_id,
    'valor_alocado', p_valor,
    'credito_obra', greatest(v_restante,0)
  );
end;
$$;

grant execute on function public.alocar_recebimento_cliente_em_obra(uuid,uuid,numeric,uuid,text) to anon, authenticated;

create or replace function public.update_updated_at_cliente360()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists obras_updated_at on public.obras;
create trigger obras_updated_at before update on public.obras for each row execute function public.update_updated_at_cliente360();
drop trigger if exists financeiro_recebimentos_updated_at on public.financeiro_recebimentos;
create trigger financeiro_recebimentos_updated_at before update on public.financeiro_recebimentos for each row execute function public.update_updated_at_cliente360();