alter table public.engenharia_tipologia_formulas_corte
  add column if not exists acessorios jsonb not null default '[]'::jsonb;

-- Orientativos W.Vetro comparados em 22/08/2026, todos em 2000 x 2100 mm,
-- Suprema, trilho embutido, montante lateral largo com reforço de aba e
-- mão-amiga larga sem reforço. Fórmulas por quantidade de folhas ficam em
-- validação; consumos sem decomposição geométrica comprovada ficam referência.

with alvo as (
  select f.id, t.label
  from public.engenharia_tipologia_formulas_corte f
  join public.tipologias t on t.id = f.tipologia_id
  where f.configuracao_chave = 'mao_amiga_larga_sem_reforco'
    and t.label in (
      'Porta De Correr 02 Folhas (L. Suprema)',
      'Porta De Correr 03 Folhas (L. Suprema)',
      'Porta De Correr 04 Folhas (L. Suprema)'
    )
)
update public.engenharia_tipologia_formulas_corte f
set acessorios = case a.label
  when 'Porta De Correr 02 Folhas (L. Suprema)' then jsonb_build_array(
    jsonb_build_object('codigo','NYL335','descricao','VEDAÇÃO SUPERIOR','cor','PRETO','unidade','UN','formula_quantidade','Folhas - 1','quantidade_referencia',1,'status','em_validacao','composicao_calculo','1 por encontro: Folhas - 1','fonte','W.Vetro PC2 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL332','descricao','GUIA DESLIZANTE COM PLACA','cor','PRETO','unidade','UN','formula_quantidade','Folhas * 4','quantidade_referencia',8,'status','em_validacao','composicao_calculo','4 guias por folha móvel','fonte','W.Vetro PC2 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FRA820','descricao','FECHADURA BICO DE PAPAGAIO PARA PORTA','cor','PRETO','unidade','UN','quantidade_referencia',2,'status','referencia','composicao_calculo','Quantidade fixa observada nesta montagem com fechadura','fonte','W.Vetro PC2 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','CON409','descricao','CONTRAFECHO LATERAL DA FECHADURA','cor','PRETO','unidade','UN','quantidade_referencia',2,'status','referencia','composicao_calculo','Quantidade fixa observada nesta montagem com fechadura','fonte','W.Vetro PC2 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','RPCS100','descricao','ROLDANA SIMPLES CÔNCAVA SUPREMA/MEGA','cor','NATURAL','unidade','UN','formula_quantidade','Folhas * 2','quantidade_referencia',4,'status','em_validacao','composicao_calculo','2 roldanas por folha móvel','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FIT206','descricao','FITA DE VEDAÇÃO SEM BARREIRA PLÁSTICA 5','cor','PRETO','unidade','MT','formula_quantidade','SU243 * Encontros / 1000','quantidade_referencia',2.066,'status','em_validacao','composicao_calculo','Comprimento da mão-amiga × encontros ÷ 1000','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FIT246','descricao','FITA VEDADORA SEM BARREIRA PLÁSTICA 7,6','cor','PRETO','unidade','MT','formula_quantidade','SU280 * 4 / 1000','quantidade_referencia',8.264,'status','em_validacao','composicao_calculo','4 linhas verticais usando o comprimento do SU280','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FIT212','descricao','FITA DE VEDAÇÃO SEM BARREIRA PLÁSTICA 5','cor','PRETO','unidade','MT','formula_quantidade','Largura * 4 / 1000','quantidade_referencia',8.000,'status','em_validacao','composicao_calculo','4 vezes a largura nominal ÷ 1000','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','GUA258','descricao','GUARNIÇÃO ESPUMA ADESIVA 11 X 4,8 MM','cor','PRETO','unidade','MT','formula_quantidade','SU280 * Folhas * 2 / 1000','quantidade_referencia',8.264,'status','em_validacao','composicao_calculo','Duas laterais verticais por folha usando o comprimento do SU280','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','GUA171','descricao','GUARNIÇÃO ESPUMA ADESIVA 11 X 3,2 MM','cor','PRETO','unidade','MT','quantidade_referencia',3.623,'status','referencia','composicao_calculo','Consumo horizontal observado. A medida geométrica bruta da folha ainda precisa ser decomposta.','fonte','W.Vetro PC2 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','GUA259','descricao','GUARNIÇÃO CUNHA DO VIDRO 12 X 4,2 - EPDM','cor','PRETO','unidade','MT','formula_quantidade','GUA258 + GUA171','quantidade_referencia',11.887,'status','em_validacao','composicao_calculo','Vedação vertical + vedação horizontal do vidro','fonte','W.Vetro PC2 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR435','descricao','PARAFUSO AA CP PP 4,8 X 32 MM INOX - PAR MARCO','cor','NATURAL','unidade','UN','formula_quantidade','Folhas * 2','quantidade_referencia',4,'status','em_validacao','composicao_calculo','2 parafusos de marco por folha','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR435','descricao','PARAFUSO AA CP PP 4,8 X 32 MM INOX - MONTAR FOLHAS','cor','NATURAL','unidade','UN','formula_quantidade','Folhas * 6','quantidade_referencia',12,'status','em_validacao','composicao_calculo','6 parafusos de montagem por folha','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL042','descricao','BOTÃO TAMPA FURO 3/8 NYLON','cor','PRETO','unidade','UN','formula_quantidade','Folhas * 4','quantidade_referencia',8,'status','em_validacao','composicao_calculo','4 tapa-furos por folha','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR1023','descricao','PARAFUSO AA CP 3,9 X 9,5 MM INOX - FIXAR MATA-JUNTA','cor','NATURAL','unidade','UN','quantidade_referencia',12,'status','referencia','composicao_calculo','PC2/PC3/PC4 mantiveram 12 na mesma medida; regra por marco ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL-10005','descricao','CONEXÃO DE NYLON PARA CONTRAMARCO','cor','PRETO','unidade','UN','quantidade_referencia',2,'status','referencia','composicao_calculo','2 conectores nesta montagem de contramarco','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','CHU838','descricao','CHUMBADOR DE ALUMÍNIO MULTIUSO','cor','FOSCO','unidade','UN','quantidade_referencia',14,'status','referencia','composicao_calculo','PC2/PC3/PC4 mantiveram 14; fórmula por dimensão/espaçamento ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL190','descricao','BOTÃO DE NYL FIXAÇÃO DO ARREMATE','cor','PRETO','unidade','UN','quantidade_referencia',14,'status','referencia','composicao_calculo','Acompanha pontos do arremate; fórmula por dimensão ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR1025','descricao','PARAFUSO AA CP 4,2 X 16 MM INOX - ARREMATE','cor','NATURAL','unidade','UN','quantidade_referencia',14,'status','referencia','composicao_calculo','Acompanha NYL190; fórmula por dimensão ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','SIL-PU','descricao','SILICONE DE POLIURETANO','cor','PRETO','unidade','TB','quantidade_referencia',1.367,'status','referencia','composicao_calculo','Consumo externo observado; fórmula de rendimento ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026')
  )
  when 'Porta De Correr 03 Folhas (L. Suprema)' then jsonb_build_array(
    jsonb_build_object('codigo','NYL335','descricao','VEDAÇÃO SUPERIOR','cor','PRETO','unidade','UN','formula_quantidade','Folhas - 1','quantidade_referencia',2,'status','em_validacao','composicao_calculo','1 por encontro: Folhas - 1','fonte','W.Vetro PC3 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL332','descricao','GUIA DESLIZANTE COM PLACA','cor','PRETO','unidade','UN','formula_quantidade','Folhas * 4','quantidade_referencia',12,'status','em_validacao','composicao_calculo','4 guias por folha móvel','fonte','W.Vetro PC3 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL414','descricao','BATEDEIRA BAT-FLEX','cor','PRETO','unidade','UN','formula_quantidade','Encontros * 4','quantidade_referencia',8,'status','em_validacao','composicao_calculo','4 batedeiras por encontro em PC3/PC4; PC2 é exceção observada.','fonte','W.Vetro PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FRA820','descricao','FECHADURA BICO DE PAPAGAIO PARA PORTA','cor','PRETO','unidade','UN','quantidade_referencia',2,'status','referencia','composicao_calculo','Quantidade fixa observada nesta montagem com fechadura','fonte','W.Vetro PC3 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','CON409','descricao','CONTRAFECHO LATERAL DA FECHADURA','cor','PRETO','unidade','UN','quantidade_referencia',2,'status','referencia','composicao_calculo','Quantidade fixa observada nesta montagem com fechadura','fonte','W.Vetro PC3 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','RPCS100','descricao','ROLDANA SIMPLES CÔNCAVA SUPREMA/MEGA','cor','NATURAL','unidade','UN','formula_quantidade','Folhas * 2','quantidade_referencia',6,'status','em_validacao','composicao_calculo','2 roldanas por folha móvel','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FIT206','descricao','FITA DE VEDAÇÃO SEM BARREIRA PLÁSTICA 5','cor','PRETO','unidade','MT','formula_quantidade','SU243 * Encontros / 1000','quantidade_referencia',4.132,'status','em_validacao','composicao_calculo','Comprimento da mão-amiga × encontros ÷ 1000','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FIT246','descricao','FITA VEDADORA SEM BARREIRA PLÁSTICA 7,6','cor','PRETO','unidade','MT','formula_quantidade','SU280 * 4 / 1000','quantidade_referencia',8.264,'status','em_validacao','composicao_calculo','4 linhas verticais usando o comprimento do SU280','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FIT212','descricao','FITA DE VEDAÇÃO SEM BARREIRA PLÁSTICA 5','cor','PRETO','unidade','MT','formula_quantidade','Largura * 4 / 1000','quantidade_referencia',8.000,'status','em_validacao','composicao_calculo','4 vezes a largura nominal ÷ 1000','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','GUA258','descricao','GUARNIÇÃO ESPUMA ADESIVA 11 X 4,8 MM','cor','PRETO','unidade','MT','formula_quantidade','SU280 * Folhas * 2 / 1000','quantidade_referencia',12.396,'status','em_validacao','composicao_calculo','Duas laterais verticais por folha usando o comprimento do SU280','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','GUA171','descricao','GUARNIÇÃO ESPUMA ADESIVA 11 X 3,2 MM','cor','PRETO','unidade','MT','quantidade_referencia',3.542,'status','referencia','composicao_calculo','Consumo horizontal observado. A medida geométrica bruta da folha ainda precisa ser decomposta.','fonte','W.Vetro PC3 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','GUA259','descricao','GUARNIÇÃO CUNHA DO VIDRO 12 X 4,2 - EPDM','cor','PRETO','unidade','MT','formula_quantidade','GUA258 + GUA171','quantidade_referencia',15.938,'status','em_validacao','composicao_calculo','Vedação vertical + vedação horizontal do vidro','fonte','W.Vetro PC3 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR435','descricao','PARAFUSO AA CP PP 4,8 X 32 MM INOX - PAR MARCO','cor','NATURAL','unidade','UN','formula_quantidade','Folhas * 2','quantidade_referencia',6,'status','em_validacao','composicao_calculo','2 parafusos de marco por folha','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR435','descricao','PARAFUSO AA CP PP 4,8 X 32 MM INOX - MONTAR FOLHAS','cor','NATURAL','unidade','UN','formula_quantidade','Folhas * 6','quantidade_referencia',18,'status','em_validacao','composicao_calculo','6 parafusos de montagem por folha','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL042','descricao','BOTÃO TAMPA FURO 3/8 NYLON','cor','PRETO','unidade','UN','formula_quantidade','Folhas * 4','quantidade_referencia',12,'status','em_validacao','composicao_calculo','4 tapa-furos por folha','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR1023','descricao','PARAFUSO AA CP 3,9 X 9,5 MM INOX - FIXAR MATA-JUNTA','cor','NATURAL','unidade','UN','quantidade_referencia',12,'status','referencia','composicao_calculo','PC2/PC3/PC4 mantiveram 12 na mesma medida; regra por marco ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL-10005','descricao','CONEXÃO DE NYLON PARA CONTRAMARCO','cor','PRETO','unidade','UN','quantidade_referencia',2,'status','referencia','composicao_calculo','2 conectores nesta montagem de contramarco','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','CHU838','descricao','CHUMBADOR DE ALUMÍNIO MULTIUSO','cor','FOSCO','unidade','UN','quantidade_referencia',14,'status','referencia','composicao_calculo','PC2/PC3/PC4 mantiveram 14; fórmula por dimensão/espaçamento ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL190','descricao','BOTÃO DE NYL FIXAÇÃO DO ARREMATE','cor','PRETO','unidade','UN','quantidade_referencia',14,'status','referencia','composicao_calculo','Acompanha pontos do arremate; fórmula por dimensão ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR1025','descricao','PARAFUSO AA CP 4,2 X 16 MM INOX - ARREMATE','cor','NATURAL','unidade','UN','quantidade_referencia',14,'status','referencia','composicao_calculo','Acompanha NYL190; fórmula por dimensão ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','SIL-PU','descricao','SILICONE DE POLIURETANO','cor','PRETO','unidade','TB','quantidade_referencia',1.367,'status','referencia','composicao_calculo','Consumo externo observado; fórmula de rendimento ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026')
  )
  when 'Porta De Correr 04 Folhas (L. Suprema)' then jsonb_build_array(
    jsonb_build_object('codigo','NYL335','descricao','VEDAÇÃO SUPERIOR','cor','PRETO','unidade','UN','formula_quantidade','Folhas - 1','quantidade_referencia',3,'status','em_validacao','composicao_calculo','1 por encontro: Folhas - 1','fonte','W.Vetro PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL332','descricao','GUIA DESLIZANTE COM PLACA','cor','PRETO','unidade','UN','formula_quantidade','Folhas * 4','quantidade_referencia',16,'status','em_validacao','composicao_calculo','4 guias por folha móvel','fonte','W.Vetro PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL414','descricao','BATEDEIRA BAT-FLEX','cor','PRETO','unidade','UN','formula_quantidade','Encontros * 4','quantidade_referencia',12,'status','em_validacao','composicao_calculo','4 batedeiras por encontro em PC3/PC4; PC2 é exceção observada.','fonte','W.Vetro PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FRA820','descricao','FECHADURA BICO DE PAPAGAIO PARA PORTA','cor','PRETO','unidade','UN','quantidade_referencia',2,'status','referencia','composicao_calculo','Quantidade fixa observada nesta montagem com fechadura','fonte','W.Vetro PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','CON409','descricao','CONTRAFECHO LATERAL DA FECHADURA','cor','PRETO','unidade','UN','quantidade_referencia',2,'status','referencia','composicao_calculo','Quantidade fixa observada nesta montagem com fechadura','fonte','W.Vetro PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','RPCS100','descricao','ROLDANA SIMPLES CÔNCAVA SUPREMA/MEGA','cor','NATURAL','unidade','UN','formula_quantidade','Folhas * 2','quantidade_referencia',8,'status','em_validacao','composicao_calculo','2 roldanas por folha móvel','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FIT206','descricao','FITA DE VEDAÇÃO SEM BARREIRA PLÁSTICA 5','cor','PRETO','unidade','MT','formula_quantidade','SU243 * Encontros / 1000','quantidade_referencia',6.198,'status','em_validacao','composicao_calculo','Comprimento da mão-amiga × encontros ÷ 1000','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FIT246','descricao','FITA VEDADORA SEM BARREIRA PLÁSTICA 7,6','cor','PRETO','unidade','MT','formula_quantidade','SU280 * 4 / 1000','quantidade_referencia',8.264,'status','em_validacao','composicao_calculo','4 linhas verticais usando o comprimento do SU280','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','FIT212','descricao','FITA DE VEDAÇÃO SEM BARREIRA PLÁSTICA 5','cor','PRETO','unidade','MT','formula_quantidade','Largura * 4 / 1000','quantidade_referencia',8.000,'status','em_validacao','composicao_calculo','4 vezes a largura nominal ÷ 1000','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','GUA258','descricao','GUARNIÇÃO ESPUMA ADESIVA 11 X 4,8 MM','cor','PRETO','unidade','MT','formula_quantidade','SU280 * Folhas * 2 / 1000','quantidade_referencia',16.528,'status','em_validacao','composicao_calculo','Duas laterais verticais por folha usando o comprimento do SU280','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','GUA171','descricao','GUARNIÇÃO ESPUMA ADESIVA 11 X 3,2 MM','cor','PRETO','unidade','MT','quantidade_referencia',3.460,'status','referencia','composicao_calculo','Consumo horizontal observado. A medida geométrica bruta da folha ainda precisa ser decomposta.','fonte','W.Vetro PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','GUA259','descricao','GUARNIÇÃO CUNHA DO VIDRO 12 X 4,2 - EPDM','cor','PRETO','unidade','MT','formula_quantidade','GUA258 + GUA171','quantidade_referencia',19.988,'status','em_validacao','composicao_calculo','Vedação vertical + vedação horizontal do vidro','fonte','W.Vetro PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR435','descricao','PARAFUSO AA CP PP 4,8 X 32 MM INOX - PAR MARCO','cor','NATURAL','unidade','UN','formula_quantidade','Folhas * 2','quantidade_referencia',8,'status','em_validacao','composicao_calculo','2 parafusos de marco por folha','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR435','descricao','PARAFUSO AA CP PP 4,8 X 32 MM INOX - MONTAR FOLHAS','cor','NATURAL','unidade','UN','formula_quantidade','Folhas * 6','quantidade_referencia',24,'status','em_validacao','composicao_calculo','6 parafusos de montagem por folha','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL042','descricao','BOTÃO TAMPA FURO 3/8 NYLON','cor','PRETO','unidade','UN','formula_quantidade','Folhas * 4','quantidade_referencia',16,'status','em_validacao','composicao_calculo','4 tapa-furos por folha','fonte','W.Vetro PC2/PC3/PC4 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR1023','descricao','PARAFUSO AA CP 3,9 X 9,5 MM INOX - FIXAR MATA-JUNTA','cor','NATURAL','unidade','UN','quantidade_referencia',12,'status','referencia','composicao_calculo','PC2/PC3/PC4 mantiveram 12 na mesma medida; regra por marco ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL-10005','descricao','CONEXÃO DE NYLON PARA CONTRAMARCO','cor','PRETO','unidade','UN','quantidade_referencia',2,'status','referencia','composicao_calculo','2 conectores nesta montagem de contramarco','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','CHU838','descricao','CHUMBADOR DE ALUMÍNIO MULTIUSO','cor','FOSCO','unidade','UN','quantidade_referencia',14,'status','referencia','composicao_calculo','PC2/PC3/PC4 mantiveram 14; fórmula por dimensão/espaçamento ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','NYL190','descricao','BOTÃO DE NYL FIXAÇÃO DO ARREMATE','cor','PRETO','unidade','UN','quantidade_referencia',14,'status','referencia','composicao_calculo','Acompanha pontos do arremate; fórmula por dimensão ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','PAR1025','descricao','PARAFUSO AA CP 4,2 X 16 MM INOX - ARREMATE','cor','NATURAL','unidade','UN','quantidade_referencia',14,'status','referencia','composicao_calculo','Acompanha NYL190; fórmula por dimensão ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026'),
    jsonb_build_object('codigo','SIL-PU','descricao','SILICONE DE POLIURETANO','cor','PRETO','unidade','TB','quantidade_referencia',1.367,'status','referencia','composicao_calculo','Consumo externo observado; fórmula de rendimento ainda a validar.','fonte','W.Vetro 2000x2100 · 22/08/2026')
  )
  else f.acessorios
end,
updated_at = now()
from alvo a
where f.id = a.id;
