-- Central de Melhorias Atlas
-- Relatos originados da IA ou da interface, com triagem, aprovação e auditoria.

create table if not exists public.atlas_melhorias (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  criado_por_id uuid not null references public.usuarios(id) on delete restrict,
  criado_por_nome text,
  tipo text not null default 'melhoria'
    check (tipo in ('bug', 'melhoria', 'ideia')),
  titulo text not null,
  descricao text not null,
  tela text,
  area text,
  resultado_atual text,
  resultado_esperado text,
  impacto text,
  urgencia text not null default 'media'
    check (urgencia in ('baixa', 'media', 'alta', 'critica')),
  status text not null default 'novo'
    check (status in (
      'novo',
      'ia_analisando',
      'informacao_necessaria',
      'solucao_proposta',
      'aguardando_aprovacao',
      'aprovado',
      'em_desenvolvimento',
      'teste',
      'pronto_publicar',
      'publicado',
      'rejeitado'
    )),
  risco text not null default 'nao_avaliado'
    check (risco in ('nao_avaliado', 'baixo', 'medio', 'alto', 'critico')),
  exige_aprovacao boolean not null default true,
  justificativa_risco text,
  analise_ia jsonb not null default '{}'::jsonb,
  aprovacao_status text not null default 'pendente'
    check (aprovacao_status in ('pendente', 'aprovado', 'rejeitado')),
  aprovado_por_id uuid references public.usuarios(id) on delete set null,
  aprovado_por_nome text,
  aprovado_em timestamptz,
  responsavel_id uuid references public.usuarios(id) on delete set null,
  responsavel_nome text,
  observacoes_admin text,
  origem text not null default 'atlas_ia',
  dedupe_key text,
  relatos_count integer not null default 1 check (relatos_count >= 1),
  contexto_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_atlas_melhorias_empresa_status
  on public.atlas_melhorias (empresa_id, status, created_at desc);

create index if not exists idx_atlas_melhorias_empresa_tipo
  on public.atlas_melhorias (empresa_id, tipo, created_at desc);

create index if not exists idx_atlas_melhorias_empresa_dedupe
  on public.atlas_melhorias (empresa_id, dedupe_key)
  where dedupe_key is not null;

create table if not exists public.atlas_melhorias_eventos (
  id uuid primary key default gen_random_uuid(),
  melhoria_id uuid not null references public.atlas_melhorias(id) on delete cascade,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  usuario_id uuid references public.usuarios(id) on delete set null,
  usuario_nome text,
  evento text not null,
  detalhe jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_atlas_melhorias_eventos_melhoria
  on public.atlas_melhorias_eventos (melhoria_id, created_at desc);

alter table public.atlas_melhorias enable row level security;
alter table public.atlas_melhorias_eventos enable row level security;

-- Sem policies para clientes. O acesso passa pelas rotas autenticadas do servidor
-- com service role, que aplicam tenant e papel do usuario explicitamente.

create or replace function public.atlas_melhorias_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_atlas_melhorias_updated_at on public.atlas_melhorias;
create trigger trg_atlas_melhorias_updated_at
before update on public.atlas_melhorias
for each row execute function public.atlas_melhorias_touch_updated_at();

comment on table public.atlas_melhorias is
  'Backlog de bugs, melhorias e ideias relatados pelos usuarios do Atlas, com triagem e aprovacao.';