-- Atlas One — PDV Balcão v1
-- Dependência: estoque/precificação da PR #255.

create table if not exists public.balcao_caixas (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'aberto' check (status in ('aberto','fechado')),
  operador_id uuid not null references auth.users(id),
  operador_nome text not null,
  aberto_em timestamptz not null default now(),
  saldo_inicial numeric not null default 0 check (saldo_inicial >= 0),
  fechado_em timestamptz,
  fechado_por_id uuid references auth.users(id),
  fechado_por_nome text,
  saldo_esperado numeric,
  saldo_contado numeric,
  diferenca numeric,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists uq_balcao_caixa_operador_aberto
  on public.balcao_caixas(operador_id) where status='aberto';

create table if not exists public.balcao_vendas (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  status text not null default 'finalizada' check (status in ('finalizada','cancelada','devolvida_parcial')),
  cliente_id uuid references public.clientes(id) on delete set null,
  cliente_nome text,
  vendedor_id uuid not null references auth.users(id),
  vendedor_nome text not null,
  caixa_id uuid not null references public.balcao_caixas(id),
  subtotal numeric not null check (subtotal >= 0),
  desconto numeric not null default 0 check (desconto >= 0),
  total numeric not null check (total >= 0),
  observacoes text,
  finalizada_em timestamptz not null default now(),
  cancelada_em timestamptz,
  cancelada_por_id uuid references auth.users(id),
  cancelada_por_nome text,
  motivo_cancelamento text,
  created_at timestamptz not null default now()
);
create index if not exists idx_balcao_vendas_data on public.balcao_vendas(finalizada_em desc);
create index if not exists idx_balcao_vendas_cliente on public.balcao_vendas(cliente_id, finalizada_em desc);

create table if not exists public.balcao_venda_itens (
  id uuid primary key default gen_random_uuid(),
  venda_id uuid not null references public.balcao_vendas(id) on delete restrict,
  produto_id uuid not null references public.produtos(id),
  produto_codigo text,
  produto_nome text not null,
  unidade text,
  quantidade numeric not null check (quantidade > 0),
  custo_unitario_snapshot numeric,
  preco_tabela_snapshot numeric,
  preco_unitario numeric not null check (preco_unitario >= 0),
  preco_minimo_snapshot numeric,
  total_item numeric not null check (total_item >= 0),
  margem_real_percentual numeric,
  created_at timestamptz not null default now()
);
create index if not exists idx_balcao_venda_itens_venda on public.balcao_venda_itens(venda_id);
create index if not exists idx_balcao_venda_itens_produto on public.balcao_venda_itens(produto_id, created_at desc);

create table if not exists public.balcao_pagamentos (
  id uuid primary key default gen_random_uuid(),
  venda_id uuid not null references public.balcao_vendas(id) on delete restrict,
  forma text not null check (forma in ('dinheiro','pix','cartao_debito','cartao_credito','boleto','a_prazo','outros')),
  valor numeric not null check (valor > 0),
  parcelas integer not null default 1 check (parcelas > 0),
  detalhes text,
  created_at timestamptz not null default now()
);
create index if not exists idx_balcao_pagamentos_venda on public.balcao_pagamentos(venda_id);

create table if not exists public.balcao_caixa_movimentos (
  id uuid primary key default gen_random_uuid(),
  caixa_id uuid not null references public.balcao_caixas(id),
  venda_id uuid references public.balcao_vendas(id) on delete set null,
  tipo text not null check (tipo in ('abertura','recebimento','suprimento','sangria','estorno','ajuste','fechamento')),
  forma_pagamento text,
  entrada numeric not null default 0 check (entrada >= 0),
  saida numeric not null default 0 check (saida >= 0),
  descricao text,
  criado_por_id uuid not null references auth.users(id),
  criado_por_nome text not null,
  created_at timestamptz not null default now(),
  constraint balcao_caixa_movimento_valor check (entrada > 0 or saida > 0 or tipo in ('abertura','fechamento'))
);
create index if not exists idx_balcao_caixa_movimentos_caixa on public.balcao_caixa_movimentos(caixa_id, created_at desc);

create table if not exists public.financeiro_contas_receber (
  id uuid primary key default gen_random_uuid(),
  venda_balcao_id uuid references public.balcao_vendas(id) on delete set null,
  cliente_id uuid references public.clientes(id) on delete set null,
  cliente_nome text,
  documento text,
  parcela integer not null default 1,
  total_parcelas integer not null default 1,
  data_emissao date not null default current_date,
  vencimento date,
  valor numeric not null check (valor >= 0),
  status text not null default 'aberto' check (status in ('aberto','pago','cancelado','vencido')),
  forma text,
  data_pagamento date,
  valor_pago numeric,
  observacoes text,
  criado_por_id uuid references auth.users(id),
  criado_por_nome text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_contas_receber_status_venc on public.financeiro_contas_receber(status, vencimento);

-- Setores/permissões independentes para o computador do balcão.
insert into public.setores(id,nome,grupo,ordem,ativo,rota,descricao)
values
  ('venda-balcao','Venda Balcão','Comercial',35,true,'/balcao','PDV, orçamento balcão e consulta de preço.'),
  ('caixa-balcao','Caixa Balcão','Administrativo',35,true,'/balcao/caixa','Abertura, suprimento, sangria e fechamento do caixa.'),
  ('relatorios-balcao','Relatórios Balcão','Administrativo',36,true,'/balcao/relatorios','Indicadores, margens e relatórios gerenciais do PDV.')
on conflict (id) do update set nome=excluded.nome, grupo=excluded.grupo, ativo=true, rota=excluded.rota, descricao=excluded.descricao;

alter table public.balcao_caixas enable row level security;
alter table public.balcao_vendas enable row level security;
alter table public.balcao_venda_itens enable row level security;
alter table public.balcao_pagamentos enable row level security;
alter table public.balcao_caixa_movimentos enable row level security;
alter table public.financeiro_contas_receber enable row level security;

revoke all on public.balcao_caixas, public.balcao_vendas, public.balcao_venda_itens,
  public.balcao_pagamentos, public.balcao_caixa_movimentos, public.financeiro_contas_receber
  from anon, authenticated;
grant all on public.balcao_caixas, public.balcao_vendas, public.balcao_venda_itens,
  public.balcao_pagamentos, public.balcao_caixa_movimentos, public.financeiro_contas_receber
  to service_role;

-- Finalização atômica: venda + pagamentos + estoque + caixa + contas a receber.
create or replace function public.finalizar_venda_balcao(
  p_caixa_id uuid,
  p_usuario_id uuid,
  p_usuario_nome text,
  p_usuario_role text,
  p_cliente_id uuid,
  p_cliente_nome text,
  p_itens jsonb,
  p_pagamentos jsonb,
  p_desconto numeric default 0,
  p_observacoes text default null,
  p_permitir_abaixo_minimo boolean default false
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caixa record;
  v_item jsonb;
  v_pag jsonb;
  v_prod record;
  v_saldo record;
  v_venda_id uuid;
  v_numero bigint;
  v_qtd numeric;
  v_preco numeric;
  v_subtotal numeric := 0;
  v_total numeric;
  v_pagamentos_total numeric := 0;
  v_custo numeric;
  v_margem numeric;
  v_forma text;
  v_valor numeric;
  v_parcelas integer;
  v_parcela_valor numeric;
  i integer;
begin
  select * into v_caixa from public.balcao_caixas where id=p_caixa_id for update;
  if v_caixa.id is null or v_caixa.status <> 'aberto' then raise exception 'Caixa não está aberto.'; end if;
  if coalesce(p_usuario_role,'') <> 'master' and v_caixa.operador_id <> p_usuario_id then
    raise exception 'Este caixa foi aberto por outro operador.';
  end if;
  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens)=0 then raise exception 'Venda sem itens.'; end if;

  -- Primeira passada valida produto, preço mínimo e saldo sob lock.
  for v_item in select * from jsonb_array_elements(p_itens) loop
    v_qtd := nullif(v_item->>'quantidade','')::numeric;
    v_preco := nullif(v_item->>'precoUnitario','')::numeric;
    if v_qtd is null or v_qtd <= 0 then raise exception 'Quantidade inválida.'; end if;
    if v_preco is null or v_preco < 0 then raise exception 'Preço inválido.'; end if;

    select id,codigo,nome,unidade,custo,preco,preco_minimo into v_prod
      from public.produtos where id=(v_item->>'produtoId')::uuid and ativo=true;
    if v_prod.id is null then raise exception 'Produto não encontrado ou inativo.'; end if;
    if v_prod.preco_minimo is not null and v_preco < v_prod.preco_minimo and not p_permitir_abaixo_minimo then
      raise exception 'Preço abaixo do mínimo permitido para %.', v_prod.nome;
    end if;
    select * into v_saldo from public.estoque_saldos where produto_id=v_prod.id for update;
    if v_saldo.produto_id is null then raise exception 'Produto % ainda não possui saldo de estoque.', v_prod.nome; end if;
    if v_saldo.quantidade < v_qtd then raise exception 'Estoque insuficiente para %. Disponível: %.', v_prod.nome, v_saldo.quantidade; end if;
    v_subtotal := v_subtotal + (v_qtd * v_preco);
  end loop;

  if coalesce(p_desconto,0) < 0 or coalesce(p_desconto,0) > v_subtotal then raise exception 'Desconto inválido.'; end if;
  v_total := round(v_subtotal - coalesce(p_desconto,0), 2);

  if jsonb_typeof(p_pagamentos) <> 'array' or jsonb_array_length(p_pagamentos)=0 then raise exception 'Informe o pagamento.'; end if;
  for v_pag in select * from jsonb_array_elements(p_pagamentos) loop
    v_valor := nullif(v_pag->>'valor','')::numeric;
    if v_valor is null or v_valor <= 0 then raise exception 'Valor de pagamento inválido.'; end if;
    v_pagamentos_total := v_pagamentos_total + v_valor;
  end loop;
  if abs(v_pagamentos_total - v_total) > 0.01 then raise exception 'Pagamentos não fecham com o total da venda.'; end if;

  insert into public.balcao_vendas(cliente_id,cliente_nome,vendedor_id,vendedor_nome,caixa_id,subtotal,desconto,total,observacoes)
  values(p_cliente_id,nullif(trim(p_cliente_nome),''),p_usuario_id,p_usuario_nome,p_caixa_id,round(v_subtotal,2),coalesce(p_desconto,0),v_total,p_observacoes)
  returning id,numero into v_venda_id,v_numero;

  for v_item in select * from jsonb_array_elements(p_itens) loop
    v_qtd := (v_item->>'quantidade')::numeric;
    v_preco := (v_item->>'precoUnitario')::numeric;
    select id,codigo,nome,unidade,custo,preco,preco_minimo into v_prod from public.produtos where id=(v_item->>'produtoId')::uuid;
    select * into v_saldo from public.estoque_saldos where produto_id=v_prod.id for update;
    v_custo := coalesce(v_saldo.custo_medio,v_prod.custo,0);
    v_margem := case when v_preco > 0 then round(((v_preco-v_custo)/v_preco*100)::numeric,4) else null end;

    insert into public.balcao_venda_itens(venda_id,produto_id,produto_codigo,produto_nome,unidade,quantidade,custo_unitario_snapshot,preco_tabela_snapshot,preco_unitario,preco_minimo_snapshot,total_item,margem_real_percentual)
    values(v_venda_id,v_prod.id,v_prod.codigo,v_prod.nome,coalesce(v_saldo.unidade,v_prod.unidade),v_qtd,v_custo,v_prod.preco,v_preco,v_prod.preco_minimo,round(v_qtd*v_preco,2),v_margem);

    update public.estoque_saldos set quantidade=quantidade-v_qtd,
      valor_estoque=greatest(0,(quantidade-v_qtd)*coalesce(custo_medio,0)), updated_at=now()
      where produto_id=v_prod.id;
    insert into public.estoque_movimentos(produto_id,tipo,quantidade,unidade,custo_unitario,valor_total,origem_tipo,origem_id,observacoes,criado_por_id,criado_por_nome)
    values(v_prod.id,'saida',v_qtd,coalesce(v_saldo.unidade,v_prod.unidade),v_custo,v_qtd*v_custo,'venda_balcao',v_venda_id,'Venda balcão #'||v_numero,p_usuario_id,p_usuario_nome);
    update public.produtos set ultimo_preco_vendido=v_preco, ultimo_preco_vendido_em=now(), updated_at=now() where id=v_prod.id;
  end loop;

  for v_pag in select * from jsonb_array_elements(p_pagamentos) loop
    v_forma := lower(trim(v_pag->>'forma'));
    v_valor := (v_pag->>'valor')::numeric;
    v_parcelas := greatest(1,coalesce(nullif(v_pag->>'parcelas','')::integer,1));
    if v_forma not in ('dinheiro','pix','cartao_debito','cartao_credito','boleto','a_prazo','outros') then raise exception 'Forma de pagamento inválida.'; end if;
    insert into public.balcao_pagamentos(venda_id,forma,valor,parcelas,detalhes)
    values(v_venda_id,v_forma,v_valor,v_parcelas,nullif(v_pag->>'detalhes',''));

    if v_forma in ('dinheiro','pix','cartao_debito','cartao_credito','outros') then
      insert into public.balcao_caixa_movimentos(caixa_id,venda_id,tipo,forma_pagamento,entrada,descricao,criado_por_id,criado_por_nome)
      values(p_caixa_id,v_venda_id,'recebimento',v_forma,v_valor,'Venda balcão #'||v_numero,p_usuario_id,p_usuario_nome);
    else
      v_parcela_valor := round(v_valor / v_parcelas, 2);
      for i in 1..v_parcelas loop
        insert into public.financeiro_contas_receber(venda_balcao_id,cliente_id,cliente_nome,documento,parcela,total_parcelas,vencimento,valor,forma,observacoes,criado_por_id,criado_por_nome)
        values(v_venda_id,p_cliente_id,nullif(trim(p_cliente_nome),''),'VBC-'||v_numero,i,v_parcelas,
          current_date + ((i-1)*30),
          case when i=v_parcelas then v_valor - (v_parcela_valor*(v_parcelas-1)) else v_parcela_valor end,
          v_forma,'Gerado pela venda balcão #'||v_numero,p_usuario_id,p_usuario_nome);
      end loop;
    end if;
  end loop;

  return jsonb_build_object('ok',true,'vendaId',v_venda_id,'numero',v_numero,'subtotal',round(v_subtotal,2),'total',v_total);
end;
$$;
revoke all on function public.finalizar_venda_balcao(uuid,uuid,text,text,uuid,text,jsonb,jsonb,numeric,text,boolean) from public,anon,authenticated;
grant execute on function public.finalizar_venda_balcao(uuid,uuid,text,text,uuid,text,jsonb,jsonb,numeric,text,boolean) to service_role;
