'use client'

import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Building2, CalendarDays, DollarSign, FileText, MapPin, Plus, Receipt, Save, ShoppingCart, Upload, UserRound, Wallet, Wrench, X } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { adicionarDocumentoCliente, DocumentoCliente360, registrarRecebimentoCliente } from '@/lib/cliente360'

type Obra = {
  id: string; numero: number; cliente_id: string; nome: string; status: string;
  endereco?: string|null; numero_endereco?: string|null; complemento?: string|null; bairro?: string|null; cidade?: string|null; uf?: string|null; cep?: string|null;
  responsavel?: string|null; data_inicio?: string|null; previsao_entrega?: string|null; observacoes?: string|null; created_at: string; updated_at: string;
  clientes?: { id:string; nome:string; whatsapp?:string|null; telefone?:string|null; email?:string|null; cidade?:string|null } | null
}
type Orcamento = { id:string; numero?:number|null; created_at:string; valor_estimado?:number|null; status?:string|null; tipo_esquadria?:string|null }
type BalcaoOrcamento = { id:string; numero?:number|null; created_at:string; valor_estimado?:number|null; status?:string|null }
type Venda = { id:string; numero:number; created_at:string; finalizada_em?:string|null; total:number; status:string }
type Conta = { id:string; documento?:string|null; parcela:number; total_parcelas:number; vencimento?:string|null; valor:number; valor_pago?:number|null; status:string; forma?:string|null; data_pagamento?:string|null }
type Assistencia = { id:string; numero?:string|null; created_at:string; descricao_problema?:string|null; status?:string|null; data_atendimento?:string|null }
type Medicao = { id:string; created_at:string; orcamento_id?:string|null; status_operacional?:string|null }
type Alocacao = { id:string; recebimento_id:string; valor:number; tipo:string; created_at:string }

type Aba = 'resumo'|'orcamentos'|'financeiro'|'medicoes'|'assistencias'|'documentos'

const STATUS: Record<string,{label:string;cls:string}> = {
  planejamento:{label:'Planejamento',cls:'bg-slate-100 text-slate-600'}, orcamento:{label:'Orçamento',cls:'bg-blue-50 text-blue-700'}, medicao:{label:'Medição',cls:'bg-cyan-50 text-cyan-700'}, engenharia:{label:'Engenharia',cls:'bg-purple-50 text-purple-700'}, compras:{label:'Compras',cls:'bg-amber-50 text-amber-700'}, producao:{label:'Produção',cls:'bg-orange-50 text-orange-700'}, instalacao:{label:'Instalação',cls:'bg-indigo-50 text-indigo-700'}, concluida:{label:'Concluída',cls:'bg-emerald-50 text-emerald-700'}, pausada:{label:'Pausada',cls:'bg-red-50 text-red-700'},
}
function moeda(v:number|null|undefined){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function dataBR(v?:string|null){if(!v)return '—';const base=v.length===10?`${v}T12:00:00`:v;const d=new Date(base);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('pt-BR')}
function statusLabel(v?:string|null){return v?String(v).replace(/_/g,' ').replace(/^./,s=>s.toUpperCase()):'—'}
function saldo(c:Conta){return Math.max(0,Number(c.valor||0)-Number(c.valor_pago||0))}

function Kpi({titulo,valor,detalhe}:{titulo:string;valor:string;detalhe?:string}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{titulo}</p><p className="mt-1 text-xl font-bold text-slate-800">{valor}</p>{detalhe&&<p className="mt-1 text-xs text-slate-500">{detalhe}</p>}</div>}
function Secao({titulo,children,acao}:{titulo:string;children:React.ReactNode;acao?:React.ReactNode}){return <section className="rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between gap-3 border-b px-5 py-4"><h2 className="font-semibold text-slate-800">{titulo}</h2>{acao}</div><div className="p-5">{children}</div></section>}

export default function ObraPage(){
  const params=useParams(); const obraId=String(params?.id||'')
  const [obra,setObra]=useState<Obra|null>(null),[orcamentos,setOrcamentos]=useState<Orcamento[]>([]),[balcaoOrcamentos,setBalcaoOrcamentos]=useState<BalcaoOrcamento[]>([]),[vendas,setVendas]=useState<Venda[]>([]),[contas,setContas]=useState<Conta[]>([]),[assistencias,setAssistencias]=useState<Assistencia[]>([]),[medicoes,setMedicoes]=useState<Medicao[]>([]),[alocacoes,setAlocacoes]=useState<Alocacao[]>([]),[documentos,setDocumentos]=useState<DocumentoCliente360[]>([])
  const [aba,setAba]=useState<Aba>('resumo'),[carregando,setCarregando]=useState(true),[erro,setErro]=useState(''),[modalRecebimento,setModalRecebimento]=useState(false),[salvando,setSalvando]=useState(false)
  const [recebimento,setRecebimento]=useState({valor:'',forma:'pix',data:new Date().toISOString().slice(0,10),referencia:'',observacoes:''})
  const [doc,setDoc]=useState({titulo:'',tipo:'documento',observacoes:''}),[arquivo,setArquivo]=useState<File|null>(null)

  useEffect(()=>{if(obraId)void carregar()},[obraId])
  async function carregar(){
    setCarregando(true);setErro('')
    const [o,orc,bo,v,c,a,m,al,d]=await Promise.all([
      supabase.from('obras').select('*,clientes(id,nome,whatsapp,telefone,email,cidade)').eq('id',obraId).maybeSingle(),
      supabase.from('orcamentos').select('id,numero,created_at,valor_estimado,status,tipo_esquadria').eq('obra_id',obraId).order('created_at',{ascending:false}),
      supabase.from('balcao_orcamentos').select('id,numero,created_at,valor_estimado,status').eq('obra_id',obraId).order('created_at',{ascending:false}),
      supabase.from('balcao_vendas').select('id,numero,created_at,finalizada_em,total,status').eq('obra_id',obraId).order('created_at',{ascending:false}),
      supabase.from('financeiro_contas_receber').select('id,documento,parcela,total_parcelas,vencimento,valor,valor_pago,status,forma,data_pagamento').eq('obra_id',obraId).order('vencimento',{ascending:true}),
      supabase.from('assistencias').select('id,numero,created_at,descricao_problema,status,data_atendimento').eq('obra_id',obraId).order('created_at',{ascending:false}),
      supabase.from('medicoes_finais').select('id,created_at,orcamento_id,status_operacional').eq('obra_id',obraId).order('created_at',{ascending:false}),
      supabase.from('financeiro_recebimento_alocacoes').select('id,recebimento_id,valor,tipo,created_at').eq('obra_id',obraId).order('created_at',{ascending:false}),
      supabase.from('cliente_documentos').select('*').eq('obra_id',obraId).order('created_at',{ascending:false}),
    ])
    if(o.error||!o.data){setErro('Obra não encontrada.');setCarregando(false);return}
    setObra(o.data as Obra);setOrcamentos((orc.data||[]) as Orcamento[]);setBalcaoOrcamentos((bo.data||[]) as BalcaoOrcamento[]);setVendas((v.data||[]) as Venda[]);setContas((c.data||[]) as Conta[]);setAssistencias((a.data||[]) as Assistencia[]);setMedicoes((m.data||[]) as Medicao[]);setAlocacoes((al.data||[]) as Alocacao[]);setDocumentos((d.data||[]) as DocumentoCliente360[]);setCarregando(false)
  }

  const totalOrcado=useMemo(()=>orcamentos.reduce((s,x)=>s+Number(x.valor_estimado||0),0)+balcaoOrcamentos.reduce((s,x)=>s+Number(x.valor_estimado||0),0),[orcamentos,balcaoOrcamentos])
  const totalVendas=useMemo(()=>vendas.filter(v=>v.status!=='cancelada').reduce((s,v)=>s+Number(v.total||0),0),[vendas])
  const totalContas=useMemo(()=>contas.filter(c=>c.status!=='cancelado').reduce((s,c)=>s+Number(c.valor||0),0),[contas])
  const totalPago=useMemo(()=>contas.reduce((s,c)=>s+Number(c.valor_pago||0),0),[contas])
  const totalReceber=useMemo(()=>contas.filter(c=>c.status!=='cancelado').reduce((s,c)=>s+saldo(c),0),[contas])
  const totalAlocado=useMemo(()=>alocacoes.reduce((s,a)=>s+Number(a.valor||0),0),[alocacoes])
  const assistenciasAbertas=assistencias.filter(a=>!['concluido','concluida','resolvido'].includes(String(a.status||''))).length

  async function salvarRecebimento(){if(!obra?.clientes)return;const valor=Number(recebimento.valor.replace(',','.'));setSalvando(true);setErro('');const r=await registrarRecebimentoCliente({clienteId:obra.cliente_id,clienteNome:obra.clientes.nome,obraId:obra.id,valor,dataRecebimento:recebimento.data,forma:recebimento.forma,referencia:recebimento.referencia,observacoes:recebimento.observacoes});setSalvando(false);if(!r.ok){setErro(r.error||'Erro ao receber.');return}setModalRecebimento(false);setRecebimento({valor:'',forma:'pix',data:new Date().toISOString().slice(0,10),referencia:'',observacoes:''});await carregar()}
  async function salvarDocumento(){if(!obra||!arquivo)return;setSalvando(true);setErro('');const r=await adicionarDocumentoCliente({clienteId:obra.cliente_id,obraId:obra.id,titulo:doc.titulo,arquivo,tipo:doc.tipo,observacoes:doc.observacoes});setSalvando(false);if(!r.ok){setErro(r.error||'Erro ao anexar documento.');return}setDoc({titulo:'',tipo:'documento',observacoes:''});setArquivo(null);await carregar()}

  if(carregando)return <div className="min-h-screen bg-slate-50 flex items-center justify-center text-slate-400">Carregando obra...</div>
  if(!obra)return <div className="min-h-screen bg-slate-50 flex items-center justify-center text-slate-400">{erro||'Obra não encontrada.'}</div>
  const cliente=obra.clientes
  const abas:{id:Aba;label:string}[]=[{id:'resumo',label:'Resumo'},{id:'orcamentos',label:'Orçamentos e Vendas'},{id:'financeiro',label:'Financeiro'},{id:'medicoes',label:'Medições'},{id:'assistencias',label:'Assistências'},{id:'documentos',label:'Documentos'}]

  return <div className="min-h-screen bg-slate-50">
    <header className="border-b bg-white"><div className="mx-auto max-w-7xl px-4 py-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-3"><Link href="/obras" className="mt-1 rounded-lg p-2 text-slate-500 hover:bg-slate-100"><ArrowLeft size={20}/></Link><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-slate-900">{obra.nome}</h1><span className={`rounded-full px-2 py-1 text-xs font-semibold ${STATUS[obra.status]?.cls||'bg-slate-100 text-slate-600'}`}>{STATUS[obra.status]?.label||statusLabel(obra.status)}</span></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-slate-500"><span>Obra #{obra.numero}</span>{cliente&&<Link href={`/clientes/${obra.cliente_id}/central`} className="inline-flex items-center gap-1 font-medium text-brand-navy"><UserRound size={13}/>{cliente.nome}</Link>}{(obra.bairro||obra.cidade)&&<span className="inline-flex items-center gap-1"><MapPin size={13}/>{[obra.bairro,obra.cidade].filter(Boolean).join(' · ')}</span>}{obra.previsao_entrega&&<span className="inline-flex items-center gap-1"><CalendarDays size={13}/>Previsão {dataBR(obra.previsao_entrega)}</span>}</div></div></div><div className="flex flex-wrap gap-2"><Link href={`/orcamento-rapido?cliente=${obra.cliente_id}&obra=${obra.id}`} className="inline-flex items-center gap-1 rounded-xl bg-brand-navy px-3 py-2 text-sm font-semibold text-white"><Plus size={15}/> Orçamento sob medida</Link><Link href={`/balcao/orcamentos/novo?cliente=${obra.cliente_id}&obra=${obra.id}`} className="inline-flex items-center gap-1 rounded-xl border bg-white px-3 py-2 text-sm font-semibold"><Receipt size={15}/> Orçamento Balcão</Link><Link href={`/balcao?cliente=${obra.cliente_id}&obra=${obra.id}`} className="inline-flex items-center gap-1 rounded-xl border bg-white px-3 py-2 text-sm font-semibold"><ShoppingCart size={15}/> Venda Balcão</Link><Link href={`/assistencia?cliente=${obra.cliente_id}&obra=${obra.id}`} className="inline-flex items-center gap-1 rounded-xl border bg-white px-3 py-2 text-sm font-semibold"><Wrench size={15}/> Assistência</Link><button onClick={()=>setModalRecebimento(true)} className="inline-flex items-center gap-1 rounded-xl bg-brand-teal px-3 py-2 text-sm font-semibold text-white"><Wallet size={15}/> Receber</button></div></div></div></header>

    <main className="mx-auto max-w-7xl px-4 py-5">{erro&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{erro}</div>}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Kpi titulo="Total orçado" valor={moeda(totalOrcado)} detalhe={`${orcamentos.length+balcaoOrcamentos.length} orçamento(s)`}/><Kpi titulo="Vendas balcão" valor={moeda(totalVendas)} detalhe={`${vendas.length} venda(s)`}/><Kpi titulo="Contas geradas" valor={moeda(totalContas)}/><Kpi titulo="Pago" valor={moeda(totalPago)}/><Kpi titulo="A receber" valor={moeda(totalReceber)}/><Kpi titulo="Recebido/alocado" valor={moeda(totalAlocado)}/></div>
      <div className="mt-5 overflow-x-auto border-b"><div className="flex min-w-max gap-1">{abas.map(a=><button key={a.id} onClick={()=>setAba(a.id)} className={`border-b-2 px-3 py-3 text-sm font-medium ${aba===a.id?'border-brand-navy text-brand-navy':'border-transparent text-slate-500'}`}>{a.label}</button>)}</div></div>
      <div className="mt-5 space-y-5">
        {aba==='resumo'&&<div className="grid gap-5 xl:grid-cols-3"><Secao titulo="Dados da obra"><div className="space-y-3 text-sm"><div><p className="text-xs text-slate-400">Cliente</p><p className="font-semibold">{cliente?.nome||'—'}</p></div><div><p className="text-xs text-slate-400">Endereço</p><p>{[obra.endereco,obra.numero_endereco,obra.bairro,obra.cidade,obra.uf].filter(Boolean).join(', ')||'—'}</p></div><div><p className="text-xs text-slate-400">Responsável</p><p>{obra.responsavel||'—'}</p></div><div className="grid grid-cols-2 gap-3"><div><p className="text-xs text-slate-400">Início</p><p>{dataBR(obra.data_inicio)}</p></div><div><p className="text-xs text-slate-400">Previsão</p><p>{dataBR(obra.previsao_entrega)}</p></div></div>{obra.observacoes&&<div><p className="text-xs text-slate-400">Observações</p><p className="whitespace-pre-wrap">{obra.observacoes}</p></div>}</div></Secao><Secao titulo="Financeiro da obra"><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Contas geradas</span><strong>{moeda(totalContas)}</strong></div><div className="flex justify-between"><span className="text-slate-500">Pago</span><strong>{moeda(totalPago)}</strong></div><div className="flex justify-between"><span className="text-slate-500">A receber</span><strong className="text-brand-teal">{moeda(totalReceber)}</strong></div><div className="flex justify-between border-t pt-3"><span className="text-slate-500">Recebimentos alocados</span><strong>{moeda(totalAlocado)}</strong></div></div></Secao><Secao titulo="Operação"><div className="grid grid-cols-2 gap-3 text-center"><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-bold">{medicoes.length}</p><p className="text-xs text-slate-500">Medições</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-bold">{assistencias.length}</p><p className="text-xs text-slate-500">Assistências</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-bold">{documentos.length}</p><p className="text-xs text-slate-500">Documentos</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-bold text-red-500">{assistenciasAbertas}</p><p className="text-xs text-slate-500">Assistências abertas</p></div></div></Secao></div>}

        {aba==='orcamentos'&&<div className="grid gap-5 xl:grid-cols-2"><Secao titulo="Orçamentos sob medida"><div className="space-y-2">{orcamentos.length===0?<p className="text-sm text-slate-400">Nenhum orçamento.</p>:orcamentos.map(o=><div key={o.id} className="flex items-center justify-between rounded-xl border p-3"><div><p className="text-sm font-semibold">Orçamento {o.numero?`#${o.numero}`:''}</p><p className="text-xs text-slate-500">{dataBR(o.created_at)} · {statusLabel(o.status)}</p></div><strong className="text-sm">{moeda(o.valor_estimado)}</strong></div>)}</div></Secao><Secao titulo="Balcão"><div className="space-y-2">{[...balcaoOrcamentos.map(o=>({id:`o-${o.id}`,titulo:`Orçamento Balcão #${o.numero||'—'}`,data:o.created_at,valor:o.valor_estimado,status:o.status})),...vendas.map(v=>({id:`v-${v.id}`,titulo:`Venda Balcão #${v.numero}`,data:v.finalizada_em||v.created_at,valor:v.total,status:v.status}))].sort((a,b)=>new Date(b.data).getTime()-new Date(a.data).getTime()).map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border p-3"><div><p className="text-sm font-semibold">{x.titulo}</p><p className="text-xs text-slate-500">{dataBR(x.data)} · {statusLabel(x.status)}</p></div><strong className="text-sm">{moeda(x.valor)}</strong></div>)}</div></Secao></div>}

        {aba==='financeiro'&&<Secao titulo="Contas a receber da obra" acao={<button onClick={()=>setModalRecebimento(true)} className="rounded-lg bg-brand-teal px-3 py-2 text-xs font-semibold text-white">Registrar recebimento</button>}><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="pb-2">Documento</th><th className="pb-2">Vencimento</th><th className="pb-2">Valor</th><th className="pb-2">Pago</th><th className="pb-2">Saldo</th><th className="pb-2">Status</th></tr></thead><tbody>{contas.map(c=><tr key={c.id} className="border-b border-slate-100"><td className="py-3">{c.documento||`Parcela ${c.parcela}/${c.total_parcelas}`}</td><td>{dataBR(c.vencimento)}</td><td>{moeda(c.valor)}</td><td>{moeda(c.valor_pago)}</td><td className="font-semibold">{moeda(saldo(c))}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{statusLabel(c.status)}</span></td></tr>)}</tbody></table>{contas.length===0&&<p className="py-8 text-center text-sm text-slate-400">Nenhuma conta vinculada a esta obra.</p>}</div><div className="mt-5 border-t pt-4"><p className="text-sm font-semibold">Recebimentos alocados nesta obra</p><div className="mt-2 space-y-2">{alocacoes.length===0?<p className="text-sm text-slate-400">Nenhum recebimento alocado.</p>:alocacoes.map(a=><div key={a.id} className="flex justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{dataBR(a.created_at)} · {a.tipo==='credito_obra'?'Crédito da obra':'Baixa de parcela'}</span><strong>{moeda(a.valor)}</strong></div>)}</div></div></Secao>}

        {aba==='medicoes'&&<Secao titulo="Medições finais"><div className="space-y-2">{medicoes.length===0?<p className="text-sm text-slate-400">Nenhuma medição vinculada.</p>:medicoes.map(m=><div key={m.id} className="rounded-xl border p-3"><p className="text-sm font-semibold">Medição {m.orcamento_id?`do orçamento ${m.orcamento_id.slice(0,8)}`:''}</p><p className="mt-1 text-xs text-slate-500">{dataBR(m.created_at)} · {statusLabel(m.status_operacional)}</p></div>)}</div></Secao>}

        {aba==='assistencias'&&<Secao titulo="Assistências da obra" acao={<Link href={`/assistencia?cliente=${obra.cliente_id}&obra=${obra.id}`} className="rounded-lg bg-brand-navy px-3 py-2 text-xs font-semibold text-white">Nova assistência</Link>}><div className="space-y-2">{assistencias.length===0?<p className="text-sm text-slate-400">Nenhuma assistência.</p>:assistencias.map(a=><div key={a.id} className="flex items-start justify-between gap-3 rounded-xl border p-3"><div><p className="text-sm font-semibold">{a.numero?`#${a.numero} · `:''}{a.descricao_problema||'Assistência'}</p><p className="mt-1 text-xs text-slate-500">{dataBR(a.created_at)}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{statusLabel(a.status)}</span></div>)}</div></Secao>}

        {aba==='documentos'&&<div className="grid gap-5 xl:grid-cols-[360px_1fr]"><Secao titulo="Adicionar documento"><div className="space-y-3"><input value={doc.titulo} onChange={e=>setDoc(f=>({...f,titulo:e.target.value}))} className="w-full rounded-lg border px-3 py-2 text-sm" placeholder="Título do documento"/><label className="flex cursor-pointer items-center gap-2 rounded-lg border border-dashed p-3 text-sm text-slate-500"><Upload size={16}/>{arquivo?.name||'Escolher arquivo'}<input type="file" className="hidden" onChange={e=>setArquivo(e.target.files?.[0]||null)}/></label><textarea value={doc.observacoes} onChange={e=>setDoc(f=>({...f,observacoes:e.target.value}))} rows={3} className="w-full rounded-lg border p-3 text-sm" placeholder="Observações"/><button disabled={salvando||!arquivo||!doc.titulo.trim()} onClick={salvarDocumento} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-brand-navy px-3 py-2 text-sm font-semibold text-white disabled:opacity-40"><Save size={15}/>Salvar documento</button></div></Secao><Secao titulo="Documentos da obra"><div className="space-y-2">{documentos.length===0?<p className="text-sm text-slate-400">Nenhum documento.</p>:documentos.map(d=><a key={d.id} href={d.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border p-3 hover:border-brand-navy"><FileText size={18} className="text-brand-navy"/><div className="min-w-0"><p className="truncate text-sm font-semibold">{d.titulo}</p><p className="truncate text-xs text-slate-500">{d.nome_arquivo||'Arquivo'} · {dataBR(d.created_at)}</p></div></a>)}</div></Secao></div>}
      </div>
    </main>

    {modalRecebimento&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/45 p-4"><div className="w-full max-w-xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-lg font-bold">Receber na obra</h2><p className="text-sm text-slate-500">O valor será aplicado às parcelas abertas desta obra, das mais antigas para as mais novas.</p></div><button onClick={()=>setModalRecebimento(false)} className="rounded-lg p-2 hover:bg-slate-100"><X size={20}/></button></div><div className="grid gap-3 p-5 sm:grid-cols-2"><label className="text-xs text-slate-500">Valor *<input value={recebimento.valor} onChange={e=>setRecebimento(f=>({...f,valor:e.target.value}))} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" placeholder="10.000,00"/></label><label className="text-xs text-slate-500">Data<input type="date" value={recebimento.data} onChange={e=>setRecebimento(f=>({...f,data:e.target.value}))} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label><label className="text-xs text-slate-500">Forma<select value={recebimento.forma} onChange={e=>setRecebimento(f=>({...f,forma:e.target.value}))} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"><option value="pix">PIX</option><option value="dinheiro">Dinheiro</option><option value="transferencia">Transferência</option><option value="boleto">Boleto</option><option value="cheque">Cheque</option><option value="outros">Outros</option></select></label><label className="text-xs text-slate-500">Referência<input value={recebimento.referencia} onChange={e=>setRecebimento(f=>({...f,referencia:e.target.value}))} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" placeholder="Ex.: PIX identificado"/></label><label className="sm:col-span-2 text-xs text-slate-500">Observações<textarea value={recebimento.observacoes} onChange={e=>setRecebimento(f=>({...f,observacoes:e.target.value}))} rows={3} className="mt-1 w-full rounded-lg border p-3 text-sm"/></label></div><div className="flex justify-end gap-2 border-t p-4"><button onClick={()=>setModalRecebimento(false)} className="rounded-lg border px-4 py-2 text-sm">Cancelar</button><button disabled={salvando||!recebimento.valor.trim()} onClick={salvarRecebimento} className="inline-flex items-center gap-2 rounded-lg bg-brand-teal px-4 py-2 text-sm font-semibold text-white disabled:opacity-40"><DollarSign size={15}/>{salvando?'Registrando...':'Registrar recebimento'}</button></div></div></div>}
  </div>
}
